import {
  TrendingUp, Wine, BarChart3, Sparkles, BookOpen, Globe,
  Target, RefreshCw, Search, DollarSign, Users, Layers,
} from "lucide-react";
import VerticalTemplate, { type VerticalContent } from "@/components/templates/VerticalTemplate";
import { useLanguage } from "@/i18n/LanguageContext";
import type { SupportedLang } from "@/i18n/types";

const ES: VerticalContent = {
  metaTitle: "Winerim para Cartas de 80–250 Referencias | Optimización con Criterio",
  metaDescription: "Tu carta tiene la profundidad suficiente para beneficiarse de Winerim: mejor pricing, rotación equilibrada.",
  canonicalUrl: "https://winerim.wine/soluciones/carta-crecimiento",
  schemaId: "carta-crecimiento",
  badgeLabel: "Profundidad con criterio", badgeIcon: TrendingUp,
  breadSolutions: "Soluciones", breadLabel: "Carta con ambición",
  heroTitle1: "Tu carta ya tiene suficiente complejidad. Lo que necesita es ", heroTitleHighlight: "inteligencia para crecer bien",
  heroDesc: "80–250 referencias no es una carta pequeña. Es una carta con potencial real para vender mejor, rotar más y crecer sin perder el control.",
  ctaDemo: "Solicitar demo", ctaContact: "Hablar con el equipo",
  heroSummary: "Una carta de 80 a 250 referencias ya tiene la complejidad comercial suficiente para que las decisiones de surtido, pricing y rotación marquen una diferencia real. Winerim aporta el criterio analítico para que cada referencia justifique su sitio.",
  forTitle: "¿Es Winerim para tu carta?", forLabel: "Encaja perfecto si…", notForLabel: "Quizá no sea para ti si…",
  forItems: [
    "Tu carta tiene entre 80 y 250 referencias y quieres optimizar antes de crecer",
    "Sospechas que tu pricing se basa en multiplicadores genéricos",
    "No tienes datos claros de qué vinos generan margen",
    "Tu estrategia de vino por copa es intuitiva",
    "Quieres crecer con criterio, sin desordenar la carta",
  ],
  notForItems: [
    "Tu carta tiene menos de 80 referencias y la controlas sin dificultad",
    "No consideras el vino una categoría estratégica",
    "No tienes intención de optimizar pricing ni rotación",
  ],
  painLabel: "El problema", painTitle1: "Los retos de una carta con ", painTitleHighlight: "profundidad real pero sin herramientas",
  pains: [
    { text: "Pricing lineal: el mismo multiplicador para todos los vinos." },
    { text: "Rotación desigual: algunas referencias venden siempre y otras se estancan." },
    { text: "Desequilibrio de surtido: demasiada representación de una zona, huecos en franjas clave." },
    { text: "Vino por copa sin estrategia: la selección se decide por comodidad." },
    { text: "Crecimiento desordenado: se añaden referencias por relación con distribuidores." },
    { text: "Formación insuficiente: el equipo de sala no puede conocer 100+ referencias." },
  ],
  tableLabel: "Comparativa", tableTitle: "Gestión de carta media-alta: intuición vs. datos",
  tableHeaders: ["Decisión", "Por intuición", "Con Winerim"],
  tableRows: [
    { area: "Qué precio poner", without: "Coste × multiplicador fijo", with_w: "Precio óptimo según rol, demanda y margen" },
    { area: "Qué vinos por copa", without: "Los más fáciles de servir", with_w: "Los de mejor ratio rentabilidad-rotación-vida útil" },
    { area: "Cuándo rotar", without: "Cuando el distribuidor lo sugiere", with_w: "Cuando los datos de venta y margen lo indican" },
    { area: "Cómo equilibrar", without: "Por intuición del sumiller", with_w: "Mapeo de estilos, precios y demanda" },
    { area: "Si crecer", without: "Si hay hueco en la bodega", with_w: "Si hay demanda real sin canibalización" },
    { area: "Cómo formar al equipo", without: "Briefing verbal", with_w: "Fichas enriquecidas accesibles" },
  ],
  solLabel: "La solución", solTitle1: "Lo que Winerim aporta a una carta con ", solTitleHighlight: "ambición de crecimiento",
  advantages: [
    { title: "Pricing diferenciado", desc: "Cada referencia tiene su precio óptimo. Abandona el multiplicador genérico." },
    { title: "Rotación bajo control", desc: "Visualiza la velocidad de rotación. Detecta estancamientos." },
    { title: "Equilibrio inteligente", desc: "Mapea tu carta por estilo, región, precio y demanda." },
    { title: "Copa estratégica", desc: "Selecciona copas por rentabilidad, vida útil y demanda." },
    { title: "Criterio para crecer", desc: "Winerim muestra si hay demanda real antes de añadir." },
    { title: "Equipo preparado", desc: "Fichas enriquecidas y recomendaciones contextuales." },
  ],
  advIcons: [DollarSign, RefreshCw, Layers, Wine, TrendingUp, Users],
  howLabel: "En la práctica", howTitle: "Cómo funciona con 80–250 referencias",
  useCases: [
    { title: "Optimización de pricing", scenario: "120 referencias con el mismo ×3,2.", result: "Escalera de precios diferenciada: margen global +12%." },
    { title: "Estrategia de copa", scenario: "8 copas sin saber cuáles son rentables.", result: "3 copas generaban pérdida por merma. Margen neto de copas +22%." },
    { title: "Crecimiento con criterio", scenario: "De 150 a 180 referencias: ¿en qué estilos?", result: "Demanda insatisfecha en blancos 20-30€ y tintos naturales." },
  ],
  ucIcons: [DollarSign, Wine, TrendingUp],
  impactLabel: "Resultados", impactTitle: "Impacto medible en cartas de 80–250",
  impactSubtitle: "Resultados basados en restaurantes que optimizaron con Winerim.",
  impacts: [
    { label: "Margen +8–15%", desc: "Con pricing diferenciado y mejor selección de copas." },
    { label: "Rotación +20% más equilibrada", desc: "Redistribución de demanda entre referencias." },
    { label: "Copa rentable desde el día 1", desc: "Selección basada en datos reduce merma." },
    { label: "Crecimiento sin canibalización", desc: "Cada nueva referencia se incorpora con criterio." },
    { label: "Equipo más seguro", desc: "Fichas enriquecidas y menos ambigüedad." },
    { label: "Decisiones más rápidas", desc: "Minutos en vez de semanas." },
  ],
  impactIcons: [DollarSign, RefreshCw, Wine, TrendingUp, Users, Sparkles],
  doesLabel: "Lo que Winerim sí hace", doesNotLabel: "Lo que Winerim no hace", doesTitle: "Expectativas claras",
  doesItems: [
    "Analiza el rendimiento con datos reales",
    "Optimiza pricing referencia a referencia",
    "Evalúa equilibrio por estilo, precio y demanda",
    "Indica si una nueva referencia aporta o canibaliza",
    "Profesionaliza la estrategia de copa",
    "Proporciona fichas enriquecidas para sala",
  ],
  doesNotItems: [
    "No decide qué vinos comprar",
    "No gestiona el almacén",
    "No modifica la carta sin tu aprobación",
    "No es un TPV",
  ],
  faqs: [
    { q: "¿80 referencias son suficientes?", a: "Sí. Desde 80 hay complejidad suficiente para que pricing, copas y equilibrio generen impacto." },
    { q: "¿En qué se diferencia de la solución +250?", a: "En 250+ el foco está en stock muerto y canibalización masiva. En 80-250, en pricing, rotación, copa y crecimiento con criterio." },
    { q: "¿Me ayuda a decidir si debo crecer?", a: "Sí. Antes de añadir, Winerim muestra demanda real y riesgo de canibalización." },
    { q: "¿Funciona para wine bars?", a: "Sí. Los wine bars se benefician especialmente de la optimización de copas." },
    { q: "¿Cuánto tarda la implantación?", a: "2-5 días con soporte completo." },
    { q: "¿Puedo probar antes?", a: "Sí. Análisis gratuito de tu carta actual." },
  ],
  ctaLabel: "Da el siguiente paso",
  ctaTitle: "¿Tu carta de 80–250 referencias está rindiendo al máximo?",
  ctaDesc: "Solicita un análisis gratuito y descubre oportunidades de pricing, rotación y copas.",
  ctaPrimary: "Analizar mi carta gratis", ctaSecondary: "Solicitar demo",
  ctaMicro: "Sin compromiso. Informe personalizado en menos de 48 horas.",
  nextStepsTitle: "Siguientes pasos",
  nextSteps: [
    { label: "Análisis gratuito", to: "/analisis-carta", description: "Evalúa tu carta", type: "tool" as const },
    { label: "Calculadora de margen", to: "/calculadora-margen-vino", description: "Calcula margen por referencia", type: "tool" as const },
    { label: "Guía vino por copa", to: "/guias/como-fijar-estrategia-rentable-vino-por-copa", description: "Estrategia completa de copas", type: "guide" as const },
  ],
  internalLinks: [
    { to: "/analisis-carta", label: "Análisis gratuito de carta", type: "tool" },
    { to: "/calculadora-margen-vino", label: "Calculadora de margen", type: "tool" },
    { to: "/soluciones/carta-amplia", label: "Cartas amplias (+250 ref.)", type: "solution" },
    { to: "/casos-exito", label: "Casos de éxito", type: "resource" },
  ],
};

const EN: VerticalContent = {
  ...ES,
  metaTitle: "Winerim for Mid-Size Wine Lists | 80–250 References Optimised",
  metaDescription: "Your wine list has enough depth to benefit from Winerim: better pricing, balanced rotation, strategic by-the-glass and growth without disorder.",
  canonicalUrl: "https://winerim.wine/en/solutions/growing-wine-list",
  badgeLabel: "Depth with purpose",
  breadSolutions: "Solutions", breadLabel: "Growing wine list",
  heroTitle1: "Your list already has enough complexity. What it needs is ", heroTitleHighlight: "intelligence to grow well",
  heroDesc: "80–250 references is not a small list. It's a list with real potential to sell better, rotate more and grow without losing control.",
  ctaDemo: "Request demo", ctaContact: "Talk to the team",
  heroSummary: "A list of 80–250 references already has enough commercial complexity for assortment, pricing and rotation decisions to make a real difference. Winerim provides the analytical framework so every reference justifies its place.",
  forTitle: "Is Winerim for your list?", forLabel: "Perfect fit if…", notForLabel: "Maybe not for you if…",
  forItems: [
    "Your list has 80–250 references and you want to optimise before growing",
    "You suspect your pricing relies on generic multipliers",
    "You lack clear data on which wines generate margin",
    "Your by-the-glass strategy is intuitive",
    "You want to grow with purpose, without cluttering the list",
  ],
  notForItems: [
    "Your list has fewer than 80 references and you manage it easily",
    "You don't consider wine a strategic category",
    "You have no intention of optimising pricing or rotation",
  ],
  painLabel: "The problem", painTitle1: "The challenges of a list with ", painTitleHighlight: "real depth but no tools",
  pains: [
    { text: "Linear pricing: the same multiplier for every wine." },
    { text: "Uneven rotation: some references always sell, others stagnate." },
    { text: "Assortment imbalance: over-representation of one region, gaps in key price bands." },
    { text: "By-the-glass without strategy: selection driven by convenience." },
    { text: "Disordered growth: references added through distributor relationships." },
    { text: "Insufficient training: the floor team can't know 100+ references." },
  ],
  tableLabel: "Comparison", tableTitle: "Mid-size list management: intuition vs. data",
  tableHeaders: ["Decision", "By intuition", "With Winerim"],
  tableRows: [
    { area: "What price to set", without: "Cost × fixed multiplier", with_w: "Optimal price by role, demand and margin" },
    { area: "Which by-the-glass", without: "Easiest to serve", with_w: "Best profitability-rotation-shelf life ratio" },
    { area: "When to rotate", without: "When the distributor suggests", with_w: "When sales and margin data indicate" },
    { area: "How to balance", without: "Sommelier's intuition", with_w: "Style, price and demand mapping" },
    { area: "Whether to grow", without: "If there's cellar space", with_w: "If there's real demand without cannibalisation" },
    { area: "How to train the team", without: "Verbal briefing", with_w: "Enriched cards accessible during service" },
  ],
  solLabel: "The solution", solTitle1: "What Winerim brings to a list with ", solTitleHighlight: "growth ambition",
  advantages: [
    { title: "Differentiated pricing", desc: "Each reference gets its optimal price. Ditch the generic multiplier." },
    { title: "Rotation under control", desc: "Visualise rotation speed. Detect stagnation early." },
    { title: "Intelligent balance", desc: "Map your list by style, region, price and demand." },
    { title: "Strategic by-the-glass", desc: "Select glasses by profitability, shelf life and demand." },
    { title: "Criteria for growth", desc: "Winerim shows if there's real demand before you add." },
    { title: "Prepared team", desc: "Enriched cards and contextual recommendations." },
  ],
  howLabel: "In practice", howTitle: "How it works with 80–250 references",
  useCases: [
    { title: "Pricing optimisation", scenario: "120 references all at ×3.2.", result: "Differentiated price ladder: overall margin +12%." },
    { title: "Glass strategy", scenario: "8 glasses with unknown profitability.", result: "3 glasses were loss-making. Net glass margin +22%." },
    { title: "Growth with purpose", scenario: "From 150 to 180: which styles?", result: "Unmet demand in whites €20-30 and natural reds." },
  ],
  impactLabel: "Results", impactTitle: "Measurable impact on 80–250 lists",
  impactSubtitle: "Based on restaurants that optimised with Winerim.",
  impacts: [
    { label: "Margin +8–15%", desc: "With differentiated pricing and better glass selection." },
    { label: "Rotation +20% more balanced", desc: "Demand redistributed across references." },
    { label: "Profitable glass from day 1", desc: "Data-based selection reduces waste." },
    { label: "Growth without cannibalisation", desc: "Every new reference added with purpose." },
    { label: "More confident team", desc: "Enriched cards and less ambiguity." },
    { label: "Faster decisions", desc: "Minutes instead of weeks." },
  ],
  doesLabel: "What Winerim does", doesNotLabel: "What Winerim doesn't do", doesTitle: "Clear expectations",
  doesItems: [
    "Analyses performance with real data",
    "Optimises pricing reference by reference",
    "Evaluates balance by style, price and demand",
    "Shows if a new reference adds value or cannibalises",
    "Professionalises by-the-glass strategy",
    "Provides enriched cards for the floor team",
  ],
  doesNotItems: [
    "Doesn't decide which wines to buy",
    "Doesn't manage the cellar",
    "Doesn't modify the list without your approval",
    "Is not a POS system",
  ],
  faqs: [
    { q: "Are 80 references enough?", a: "Yes. From 80, pricing, glass and balance optimisation generate measurable impact." },
    { q: "How does this differ from the 250+ solution?", a: "At 250+ the focus is dead stock and mass cannibalisation. At 80-250, it's pricing, rotation, glass and purposeful growth." },
    { q: "Does it help me decide whether to grow?", a: "Yes. Before adding, Winerim shows real demand and cannibalisation risk." },
    { q: "Does it work for wine bars?", a: "Yes. Wine bars particularly benefit from glass optimisation." },
    { q: "How long does implementation take?", a: "2-5 days with full support." },
    { q: "Can I try first?", a: "Yes. Free analysis of your current list." },
  ],
  ctaLabel: "Take the next step",
  ctaTitle: "Is your 80–250 reference list performing at its best?",
  ctaDesc: "Request a free analysis and discover pricing, rotation and glass opportunities.",
  ctaPrimary: "Analyse my list free", ctaSecondary: "Request demo",
  ctaMicro: "No commitment. Personalised report within 48 hours.",
  nextStepsTitle: "Next steps",
  nextSteps: ES.nextSteps,
  internalLinks: ES.internalLinks,
};

const IT: VerticalContent = {
  ...ES,
  metaTitle: "Winerim per Carte di 80–250 Referenze | Ottimizzazione con Criterio",
  metaDescription: "La tua carta ha la profondità sufficiente per beneficiare di Winerim: pricing migliore, rotazione equilibrata.",
  canonicalUrl: "https://winerim.wine/it/soluzioni/carta-vini-crescita",
  badgeLabel: "Profondità con criterio",
  breadSolutions: "Soluzioni", breadLabel: "Carta in crescita",
  heroTitle1: "La tua carta ha già abbastanza complessità. Ciò che le serve è ", heroTitleHighlight: "intelligenza per crescere bene",
  heroDesc: "80–250 referenze non è una carta piccola. È una carta con potenziale reale per vendere meglio, ruotare di più e crescere senza perdere il controllo.",
  ctaDemo: "Richiedi demo", ctaContact: "Parla con il team",
  heroSummary: "Una carta di 80-250 referenze ha già la complessità commerciale sufficiente perché le decisioni di assortimento, pricing e rotazione facciano la differenza. Winerim fornisce il criterio analitico perché ogni referenza giustifichi il suo posto.",
  forTitle: "Winerim fa per la tua carta?", forLabel: "Perfetto se…", notForLabel: "Forse non per te se…",
  forItems: [
    "La tua carta ha 80-250 referenze e vuoi ottimizzare prima di crescere",
    "Sospetti che il tuo pricing si basi su moltiplicatori generici",
    "Non hai dati chiari su quali vini generano margine",
    "La tua strategia al calice è intuitiva",
    "Vuoi crescere con criterio, senza disordinare la carta",
  ],
  notForItems: [
    "La tua carta ha meno di 80 referenze e la gestisci senza difficoltà",
    "Non consideri il vino una categoria strategica",
    "Non hai intenzione di ottimizzare pricing o rotazione",
  ],
  painLabel: "Il problema", painTitle1: "Le sfide di una carta con ", painTitleHighlight: "profondità reale ma senza strumenti",
  pains: [
    { text: "Pricing lineare: lo stesso moltiplicatore per tutti i vini." },
    { text: "Rotazione disuguale: alcune referenze vendono sempre, altre ristagnano." },
    { text: "Squilibrio di assortimento: troppa rappresentazione di una zona, lacune nelle fasce chiave." },
    { text: "Calice senza strategia: la selezione è dettata dalla comodità." },
    { text: "Crescita disordinata: referenze aggiunte tramite rapporti con i distributori." },
    { text: "Formazione insufficiente: il team di sala non può conoscere 100+ referenze." },
  ],
  tableLabel: "Confronto", tableTitle: "Gestione carta media-alta: intuizione vs. dati",
  tableHeaders: ["Decisione", "Per intuizione", "Con Winerim"],
  tableRows: [
    { area: "Che prezzo mettere", without: "Costo × moltiplicatore fisso", with_w: "Prezzo ottimale per ruolo, domanda e margine" },
    { area: "Quali vini al calice", without: "I più facili da servire", with_w: "I migliori per rapporto redditività-rotazione-durata" },
    { area: "Quando ruotare", without: "Quando lo suggerisce il distributore", with_w: "Quando i dati di vendita e margine lo indicano" },
    { area: "Come equilibrare", without: "Per intuizione del sommelier", with_w: "Mappatura di stili, prezzi e domanda" },
    { area: "Se crescere", without: "Se c'è spazio in cantina", with_w: "Se c'è domanda reale senza cannibalizzazione" },
    { area: "Come formare il team", without: "Briefing verbale", with_w: "Schede arricchite accessibili" },
  ],
  solLabel: "La soluzione", solTitle1: "Cosa porta Winerim a una carta con ", solTitleHighlight: "ambizione di crescita",
  advantages: [
    { title: "Pricing differenziato", desc: "Ogni referenza ha il suo prezzo ottimale." },
    { title: "Rotazione sotto controllo", desc: "Visualizza la velocità di rotazione. Rileva stagnazioni." },
    { title: "Equilibrio intelligente", desc: "Mappa la carta per stile, regione, prezzo e domanda." },
    { title: "Calice strategico", desc: "Selezione calici per redditività, durata e domanda." },
    { title: "Criterio per crescere", desc: "Winerim mostra se c'è domanda reale prima di aggiungere." },
    { title: "Team preparato", desc: "Schede arricchite e raccomandazioni contestuali." },
  ],
  howLabel: "In pratica", howTitle: "Come funziona con 80–250 referenze",
  useCases: [
    { title: "Ottimizzazione pricing", scenario: "120 referenze tutte a ×3,2.", result: "Scala prezzi differenziata: margine globale +12%." },
    { title: "Strategia al calice", scenario: "8 calici senza sapere quali sono redditizi.", result: "3 calici in perdita per scarto. Margine netto calici +22%." },
    { title: "Crescita con criterio", scenario: "Da 150 a 180: in quali stili?", result: "Domanda insoddisfatta in bianchi 20-30€ e rossi naturali." },
  ],
  impactLabel: "Risultati", impactTitle: "Impatto misurabile su carte di 80–250",
  impactSubtitle: "Basato su ristoranti che hanno ottimizzato con Winerim.",
  impacts: [
    { label: "Margine +8–15%", desc: "Con pricing differenziato e migliore selezione calici." },
    { label: "Rotazione +20% più equilibrata", desc: "Domanda ridistribuita tra referenze." },
    { label: "Calice redditizio dal giorno 1", desc: "Selezione basata sui dati riduce lo scarto." },
    { label: "Crescita senza cannibalizzazione", desc: "Ogni nuova referenza aggiunta con criterio." },
    { label: "Team più sicuro", desc: "Schede arricchite e meno ambiguità." },
    { label: "Decisioni più rapide", desc: "Minuti anziché settimane." },
  ],
  doesLabel: "Cosa fa Winerim", doesNotLabel: "Cosa non fa Winerim", doesTitle: "Aspettative chiare",
  doesItems: [
    "Analizza le performance con dati reali",
    "Ottimizza il pricing referenza per referenza",
    "Valuta l'equilibrio per stile, prezzo e domanda",
    "Indica se una nuova referenza aggiunge valore o cannibalizza",
    "Professionalizza la strategia al calice",
    "Fornisce schede arricchite per il team di sala",
  ],
  doesNotItems: [
    "Non decide quali vini comprare",
    "Non gestisce la cantina",
    "Non modifica la carta senza la tua approvazione",
    "Non è un POS",
  ],
  faqs: [
    { q: "80 referenze sono sufficienti?", a: "Sì. Da 80, pricing, calici ed equilibrio generano impatto misurabile." },
    { q: "Come si differenzia dalla soluzione 250+?", a: "A 250+ il focus è stock morto e cannibalizzazione massiva. A 80-250, pricing, rotazione, calice e crescita con criterio." },
    { q: "Mi aiuta a decidere se crescere?", a: "Sì. Prima di aggiungere, Winerim mostra domanda reale e rischio di cannibalizzazione." },
    { q: "Funziona per wine bar?", a: "Sì. I wine bar beneficiano particolarmente dell'ottimizzazione calici." },
    { q: "Quanto tempo richiede l'implementazione?", a: "2-5 giorni con supporto completo." },
    { q: "Posso provare prima?", a: "Sì. Analisi gratuita della tua carta attuale." },
  ],
  ctaLabel: "Fai il prossimo passo",
  ctaTitle: "La tua carta di 80–250 referenze sta rendendo al massimo?",
  ctaDesc: "Richiedi un'analisi gratuita e scopri opportunità di pricing, rotazione e calici.",
  ctaPrimary: "Analizza la mia carta gratis", ctaSecondary: "Richiedi demo",
  ctaMicro: "Senza impegno. Report personalizzato entro 48 ore.",
  nextStepsTitle: "Prossimi passi",
  nextSteps: ES.nextSteps,
  internalLinks: ES.internalLinks,
};

const FR: VerticalContent = {
  ...ES,
  metaTitle: "Winerim pour Cartes de 80–250 Références | Optimisation Raisonnée",
  metaDescription: "Votre carte a assez de profondeur pour bénéficier de Winerim : pricing optimisé, rotation équilibrée, verre stratégique et croissance maîtrisée.",
  canonicalUrl: "https://winerim.wine/fr/solutions/carte-en-croissance",
  badgeLabel: "Profondeur raisonnée",
  breadSolutions: "Solutions", breadLabel: "Carte en croissance",
  heroTitle1: "Votre carte a déjà assez de complexité. Ce qu'il lui faut, c'est ", heroTitleHighlight: "l'intelligence pour bien grandir",
  heroDesc: "80–250 références, ce n'est pas une petite carte. C'est une carte avec un potentiel réel pour mieux vendre, mieux tourner et croître sans perdre le contrôle.",
  ctaDemo: "Demander une démo", ctaContact: "Parler à l'équipe",
  heroSummary: "Une carte de 80 à 250 références a déjà la complexité commerciale suffisante pour que les décisions d'assortiment, pricing et rotation fassent une vraie différence. Winerim apporte le cadre analytique pour que chaque référence justifie sa place.",
  forTitle: "Winerim est-il pour votre carte ?", forLabel: "Parfait si…", notForLabel: "Peut-être pas si…",
  forItems: [
    "Votre carte a 80-250 références et vous voulez optimiser avant de grandir",
    "Vous soupçonnez que votre pricing repose sur des multiplicateurs génériques",
    "Vous manquez de données claires sur les vins qui génèrent de la marge",
    "Votre stratégie au verre est intuitive",
    "Vous voulez grandir avec méthode, sans encombrer la carte",
  ],
  notForItems: [
    "Votre carte a moins de 80 références et vous la gérez facilement",
    "Vous ne considérez pas le vin comme une catégorie stratégique",
    "Vous n'avez pas l'intention d'optimiser le pricing ou la rotation",
  ],
  painLabel: "Le problème", painTitle1: "Les défis d'une carte avec ", painTitleHighlight: "de la profondeur mais pas d'outils",
  pains: [
    { text: "Pricing linéaire : le même multiplicateur pour tous les vins." },
    { text: "Rotation inégale : certaines références vendent toujours, d'autres stagnent." },
    { text: "Déséquilibre d'assortiment : surreprésentation d'une région, lacunes dans les tranches clés." },
    { text: "Verre sans stratégie : la sélection est dictée par la commodité." },
    { text: "Croissance désordonnée : références ajoutées par relation avec les distributeurs." },
    { text: "Formation insuffisante : l'équipe de salle ne peut pas connaître 100+ références." },
  ],
  tableLabel: "Comparatif", tableTitle: "Gestion carte moyenne-haute : intuition vs. données",
  tableHeaders: ["Décision", "Par intuition", "Avec Winerim"],
  tableRows: [
    { area: "Quel prix fixer", without: "Coût × multiplicateur fixe", with_w: "Prix optimal par rôle, demande et marge" },
    { area: "Quels vins au verre", without: "Les plus faciles à servir", with_w: "Meilleur ratio rentabilité-rotation-durée" },
    { area: "Quand tourner", without: "Quand le distributeur le suggère", with_w: "Quand les données de vente l'indiquent" },
    { area: "Comment équilibrer", without: "Par intuition du sommelier", with_w: "Cartographie des styles, prix et demande" },
    { area: "S'il faut grandir", without: "S'il y a de la place en cave", with_w: "S'il y a une demande réelle sans cannibalisation" },
    { area: "Comment former l'équipe", without: "Briefing verbal", with_w: "Fiches enrichies accessibles" },
  ],
  solLabel: "La solution", solTitle1: "Ce que Winerim apporte à une carte avec ", solTitleHighlight: "une ambition de croissance",
  advantages: [
    { title: "Pricing différencié", desc: "Chaque référence a son prix optimal." },
    { title: "Rotation sous contrôle", desc: "Visualisez la vitesse de rotation. Détectez les stagnations." },
    { title: "Équilibre intelligent", desc: "Cartographiez votre carte par style, région, prix et demande." },
    { title: "Verre stratégique", desc: "Sélection au verre par rentabilité, durée et demande." },
    { title: "Critère pour grandir", desc: "Winerim montre la demande réelle avant d'ajouter." },
    { title: "Équipe préparée", desc: "Fiches enrichies et recommandations contextuelles." },
  ],
  howLabel: "En pratique", howTitle: "Comment ça fonctionne avec 80–250 références",
  useCases: [
    { title: "Optimisation pricing", scenario: "120 références toutes à ×3,2.", result: "Échelle de prix différenciée : marge globale +12%." },
    { title: "Stratégie au verre", scenario: "8 verres sans savoir lesquels sont rentables.", result: "3 verres en perte par casse. Marge nette verres +22%." },
    { title: "Croissance raisonnée", scenario: "De 150 à 180 : quels styles ?", result: "Demande insatisfaite en blancs 20-30€ et rouges nature." },
  ],
  impactLabel: "Résultats", impactTitle: "Impact mesurable sur les cartes de 80–250",
  impactSubtitle: "Basé sur des restaurants ayant optimisé avec Winerim.",
  impacts: [
    { label: "Marge +8–15%", desc: "Avec pricing différencié et meilleure sélection au verre." },
    { label: "Rotation +20% plus équilibrée", desc: "Demande redistribuée entre les références." },
    { label: "Verre rentable dès le jour 1", desc: "Sélection basée sur les données réduit la casse." },
    { label: "Croissance sans cannibalisation", desc: "Chaque nouvelle référence ajoutée avec méthode." },
    { label: "Équipe plus confiante", desc: "Fiches enrichies et moins d'ambiguïté." },
    { label: "Décisions plus rapides", desc: "Des minutes au lieu de semaines." },
  ],
  doesLabel: "Ce que Winerim fait", doesNotLabel: "Ce que Winerim ne fait pas", doesTitle: "Attentes claires",
  doesItems: [
    "Analyse les performances avec des données réelles",
    "Optimise le pricing référence par référence",
    "Évalue l'équilibre par style, prix et demande",
    "Indique si une nouvelle référence apporte de la valeur ou cannibalise",
    "Professionnalise la stratégie au verre",
    "Fournit des fiches enrichies pour l'équipe de salle",
  ],
  doesNotItems: [
    "Ne décide pas quels vins acheter",
    "Ne gère pas la cave",
    "Ne modifie pas la carte sans votre approbation",
    "N'est pas un POS",
  ],
  faqs: [
    { q: "80 références suffisent-elles ?", a: "Oui. À partir de 80, pricing, verre et équilibre génèrent un impact mesurable." },
    { q: "En quoi diffère la solution 250+ ?", a: "À 250+, le focus est le stock mort et la cannibalisation massive. À 80-250, pricing, rotation, verre et croissance raisonnée." },
    { q: "Ça m'aide à décider si je dois grandir ?", a: "Oui. Avant d'ajouter, Winerim montre la demande réelle et le risque de cannibalisation." },
    { q: "Ça fonctionne pour les bars à vin ?", a: "Oui. Les bars à vin bénéficient particulièrement de l'optimisation au verre." },
    { q: "Combien de temps prend l'implémentation ?", a: "2-5 jours avec support complet." },
    { q: "Puis-je essayer d'abord ?", a: "Oui. Analyse gratuite de votre carte actuelle." },
  ],
  ctaLabel: "Passez à l'étape suivante",
  ctaTitle: "Votre carte de 80–250 références performe-t-elle au maximum ?",
  ctaDesc: "Demandez une analyse gratuite et découvrez des opportunités de pricing, rotation et verres.",
  ctaPrimary: "Analyser ma carte gratuitement", ctaSecondary: "Demander une démo",
  ctaMicro: "Sans engagement. Rapport personnalisé sous 48 heures.",
  nextStepsTitle: "Prochaines étapes",
  nextSteps: ES.nextSteps,
  internalLinks: ES.internalLinks,
};

const i18n: Record<SupportedLang, VerticalContent> = { es: ES, en: EN, it: IT, fr: FR };

const CartaCrecimiento = () => {
  const { lang } = useLanguage();
  const t = i18n[lang] || i18n.es;
  return <VerticalTemplate t={t} />;
};
export default CartaCrecimiento;
