import {
  Layers, Wine, BarChart3, Sparkles, BookOpen, Globe,
  TrendingUp, Users, DollarSign, Target, RefreshCw, Search,
} from "lucide-react";
import VerticalTemplate, { type VerticalContent } from "@/components/templates/VerticalTemplate";
import { useLanguage } from "@/i18n/LanguageContext";
import type { SupportedLang, I18nMap, I18nMap } from "@/i18n/types";

const ES: VerticalContent = {
  metaTitle: "Winerim para Cartas de Vinos Extensas | +250 Referencias bajo Control",
  metaDescription: "Gestiona cartas de vinos de alta complejidad con Winerim: detecta stock muerto, optimiza rotación.",
  canonicalUrl: "https://winerim.wine/soluciones/carta-amplia",
  schemaId: "carta-amplia",
  badgeLabel: "Alta complejidad", badgeIcon: Layers,
  breadSolutions: "Soluciones", breadLabel: "Carta amplia",
  heroTitle1: "Más referencias no significa más ventas. Significa ", heroTitleHighlight: "más riesgo sin control",
  heroDesc: "Winerim convierte cartas amplias y complejas en activos rentables: cada referencia justificada, cada precio optimizado, cada decisión basada en datos.",
  ctaDemo: "Solicitar demo", ctaContact: "Hablar con el equipo",
  heroSummary: "Una carta con más de 250 referencias puede ser una ventaja competitiva o una trampa financiera. Sin analítica, muchas referencias no rotan, canibalizan entre sí y generan stock muerto. Winerim aporta la inteligencia para que cada vino en tu carta tenga una razón de estar ahí — y lo demuestre con datos.",
  forTitle: "¿Es Winerim para tu carta?", forLabel: "Encaja perfecto si…", notForLabel: "Quizá no sea para ti si…",
  forItems: [
    "Tu carta tiene más de 250 referencias y sospechas que muchas no rotan",
    "No tienes datos claros de qué vinos generan margen real",
    "Has detectado vinos que se canibalizan entre sí en precio o estilo",
    "Quieres reducir la carta sin perder profundidad ni atractivo",
    "Necesitas justificar ante dirección o propiedad cada decisión de surtido",
  ],
  notForItems: [
    "Tu carta tiene menos de 80 referencias y la gestionas sin dificultad",
    "No consideras el vino como una categoría estratégica del negocio",
    "Prefieres decidir el surtido exclusivamente por relación con distribuidores",
  ],
  painLabel: "El problema", painTitle1: "Los peligros de una carta ", painTitleHighlight: "demasiado grande sin control",
  pains: [
    { text: "Stock muerto invisible: referencias que llevan meses en carta sin venderse, ocupando capital y espacio sin retorno." },
    { text: "Canibalización silenciosa: vinos de perfil similar compitiendo entre sí, diluyendo ventas y confundiendo al comensal." },
    { text: "Parálisis de elección: el comensal se abruma ante demasiadas opciones y termina pidiendo 'el segundo más barato'." },
    { text: "Imposibilidad de formar al equipo: nadie puede conocer 250+ referencias. El personal evita recomendar vino." },
    { text: "Pricing inconsistente: multiplicadores genéricos aplicados a toda la carta, sin considerar el rol de cada vino." },
    { text: "Revisiones de carta a ciegas: se cambian referencias por intuición, relación con el proveedor o disponibilidad, no por rendimiento." },
    { text: "Coste de oportunidad: cada referencia que no funciona ocupa el lugar de una que podría generar margen y satisfacción." },
  ],
  tableLabel: "Comparativa", tableTitle: "Gestión de carta amplia: intuición vs. datos",
  tableHeaders: ["Decisión", "Por intuición", "Con Winerim"],
  tableRows: [
    { area: "Qué referencias mantener", without: "Las que 'siempre han estado'", with_w: "Las que generan margen, rotan y no canibalizan" },
    { area: "Qué referencias retirar", without: "Las que el distribuidor ya no tiene", with_w: "Las de peor rendimiento según datos reales de venta" },
    { area: "Qué precio poner", without: "Coste × multiplicador igual para todas", with_w: "Precio ajustado por referencia: margen + demanda + posición" },
    { area: "Cuántas referencias tener", without: "Cuantas más, mejor (¿verdad?)", with_w: "Las necesarias para cubrir estilos sin canibalización" },
    { area: "Cómo detectar problemas", without: "Cuando alguien se queja o el stock se acumula", with_w: "Alertas automáticas de baja rotación y stock muerto" },
    { area: "Cómo formar al equipo", without: "Briefing verbal esporádico", with_w: "Fichas técnicas accesibles en cada interacción con el comensal" },
  ],
  solLabel: "La solución", solTitle1: "Lo que Winerim aporta a una ", solTitleHighlight: "carta extensa",
  advantages: [
    { title: "Mapa de rendimiento completo", desc: "Visualiza cada referencia en función de margen, rotación y demanda." },
    { title: "Detección de canibalización", desc: "Winerim cruza perfiles de precio, región, estilo y uva para señalar redundancias." },
    { title: "Alertas de stock muerto", desc: "Notificaciones cuando una referencia lleva demasiado tiempo sin moverse." },
    { title: "Optimización de surtido", desc: "Recomendaciones basadas en datos para reducir, ampliar o reequilibrar la carta." },
    { title: "Pricing por referencia", desc: "Cada vino tiene su precio óptimo basado en su rol dentro de la carta." },
    { title: "Informes de decisión", desc: "Reportes listos para compartir con dirección o propiedad." },
  ],
  advIcons: [BarChart3, Search, RefreshCw, Layers, DollarSign, BookOpen],
  howLabel: "En la práctica", howTitle: "Cómo funciona con una carta extensa",
  useCases: [
    { title: "Auditoría trimestral", scenario: "El responsable necesita decidir qué 15 referencias retirar de 250.", result: "Winerim genera un ranking con las 15 peores y sugiere sustituciones." },
    { title: "Detección de canibalización", scenario: "8 Riojas crianza entre 18-24€ compiten entre sí.", result: "Identifica 3 redundantes y muestra cómo redistribuir ventas." },
    { title: "Justificación de presupuesto", scenario: "Dirección pregunta cuántas referencias son realmente rentables.", result: "Informe automático: el 35% genera el 80% del margen." },
  ],
  ucIcons: [BarChart3, Search, Layers],
  impactLabel: "Resultados", impactTitle: "Impacto medible en cartas extensas",
  impactSubtitle: "Basado en restaurantes con más de 250 referencias.",
  impacts: [
    { label: "Stock muerto detectado: 15–30%", desc: "La mayoría de cartas extensas tienen un 15–30% de referencias sin rotación." },
    { label: "Margen global +10–18%", desc: "Al retirar referencias y ajustar pricing, el margen mejora." },
    { label: "Carta más rentable con menos refs", desc: "Reducir un 20% puede aumentar ventas por menor canibalización." },
    { label: "Decisiones 3× más rápidas", desc: "Con datos de rendimiento, decidir qué incorporar o retirar lleva minutos." },
    { label: "Equipo más seguro", desc: "Con menos referencias y fichas enriquecidas, el personal gana confianza." },
    { label: "Menor capital inmovilizado", desc: "Se reduce el stock dormido y se libera capital." },
  ],
  impactIcons: [Target, DollarSign, TrendingUp, Sparkles, Users, RefreshCw],
  doesLabel: "Lo que Winerim sí hace", doesNotLabel: "Lo que Winerim no hace", doesTitle: "Expectativas claras",
  doesItems: [
    "Analiza el rendimiento de cada referencia con datos reales",
    "Detecta canibalización entre vinos de perfil similar",
    "Genera alertas de stock muerto y baja rotación",
    "Sugiere ajustes de surtido basados en datos",
    "Optimiza pricing por referencia según su rol en carta",
    "Produce informes accionables para dirección",
  ],
  doesNotItems: [
    "No decide por ti qué vinos comprar",
    "No gestiona el almacén ni la logística",
    "No modifica la carta sin tu aprobación",
    "No es un TPV ni un sistema de pedidos",
  ],
  faqs: [
    { q: "¿A partir de cuántas referencias tiene sentido usar Winerim?", a: "A partir de 80 referencias. La solución de carta amplia está diseñada para 250+." },
    { q: "¿Winerim me dice qué vinos retirar?", a: "Te muestra un ranking de rendimiento. La decisión final siempre es tuya." },
    { q: "¿Qué es la canibalización de vinos?", a: "Dos o más referencias de perfil similar compitiendo entre sí, diluyendo ventas." },
    { q: "¿Puedo generar informes para dirección?", a: "Sí. Reportes con métricas claras, oportunidades y propuestas de acción." },
    { q: "¿Cuánto tarda en implantarse?", a: "Para 250–500 referencias, entre 5 y 10 días con soporte completo." },
    { q: "¿Puedo probar antes de contratar?", a: "Sí. Análisis gratuito de tu carta actual." },
  ],
  ctaLabel: "Da el siguiente paso",
  ctaTitle: "¿Cuántas de tus referencias están realmente trabajando para ti?",
  ctaDesc: "Solicita un análisis gratuito y descubre qué parte de tu carta genera margen.",
  ctaPrimary: "Analizar mi carta gratis", ctaSecondary: "Solicitar demo",
  ctaMicro: "Sin compromiso. Informe personalizado en menos de 48 horas.",
  nextStepsTitle: "Siguientes pasos",
  nextSteps: [
    { label: "Análisis gratuito", to: "/analisis-carta", description: "Detecta stock muerto y canibalización", type: "tool" as const },
    { label: "Guía: detectar vinos muertos", to: "/guias/como-detectar-vinos-muertos-referencias-frenan-rentabilidad", description: "Metodología paso a paso", type: "guide" as const },
    { label: "Calculadora stock muerto", to: "/herramientas/calculadora-stock-muerto", description: "Estima capital inmovilizado", type: "tool" as const },
  ],
  internalLinks: [
    { to: "/analisis-carta", label: "Análisis gratuito de carta", type: "tool" },
    { to: "/guias/como-detectar-vinos-muertos-referencias-frenan-rentabilidad", label: "Detectar vinos muertos", type: "guide" },
    { to: "/herramientas/calculadora-stock-muerto", label: "Calculadora stock muerto", type: "tool" },
    { to: "/casos-exito", label: "Casos de éxito", type: "resource" },
    { to: "/soluciones/grupos-restauracion", label: "Grupos de restauración", type: "solution" },
  ],
};

const EN: VerticalContent = {
  ...ES,
  metaTitle: "Winerim for Large Wine Lists | 250+ References under Control",
  metaDescription: "Manage high-complexity wine lists with Winerim: detect dead stock, optimise rotation.",
  canonicalUrl: "https://winerim.wine/en/solutions/large-wine-list",
  badgeLabel: "High complexity",
  breadSolutions: "Solutions", breadLabel: "Large wine list",
  heroTitle1: "More references doesn't mean more sales. It means ", heroTitleHighlight: "more risk without control",
  heroDesc: "Winerim turns large, complex wine lists into profitable assets: every reference justified, every price optimised, every decision data-driven.",
  ctaDemo: "Request demo", ctaContact: "Talk to the team",
  heroSummary: "A wine list with 250+ references can be a competitive advantage or a financial trap. Without analytics, many references don't rotate, cannibalise each other and generate dead stock. Winerim provides the intelligence so every wine on your list has a reason to be there — and proves it with data.",
  forTitle: "Is Winerim for your list?", forLabel: "Perfect fit if…", notForLabel: "Maybe not for you if…",
  forItems: [
    "Your list has 250+ references and you suspect many don't rotate",
    "You lack clear data on which wines generate real margin",
    "You've noticed wines cannibalising each other on price or style",
    "You want to reduce the list without losing depth or appeal",
    "You need to justify every assortment decision to ownership",
  ],
  notForItems: [
    "Your list has fewer than 80 references and you manage it easily",
    "You don't consider wine a strategic business category",
    "You prefer to decide assortment solely through distributor relationships",
  ],
  painLabel: "The problem", painTitle1: "The dangers of a list that's ", painTitleHighlight: "too large without control",
  pains: [
    { text: "Invisible dead stock: references sitting on the list for months without selling, tying up capital and space." },
    { text: "Silent cannibalisation: similar-profile wines competing against each other, diluting sales." },
    { text: "Choice paralysis: guests overwhelmed by too many options, defaulting to 'the second cheapest'." },
    { text: "Impossible staff training: nobody can know 250+ references. Staff avoids recommending wine." },
    { text: "Inconsistent pricing: generic multipliers applied across the board without considering each wine's role." },
    { text: "Blind list reviews: references changed by intuition or distributor availability, not performance." },
    { text: "Opportunity cost: every underperforming reference occupies the slot of one that could generate margin." },
  ],
  tableLabel: "Comparison", tableTitle: "Large list management: intuition vs. data",
  tableHeaders: ["Decision", "By intuition", "With Winerim"],
  tableRows: [
    { area: "Which references to keep", without: "The ones that 'have always been there'", with_w: "Those that generate margin, rotate and don't cannibalise" },
    { area: "Which to remove", without: "The ones the distributor no longer stocks", with_w: "The worst performers based on real sales data" },
    { area: "What price to set", without: "Cost × same multiplier for all", with_w: "Price adjusted per reference: margin + demand + position" },
    { area: "How many references", without: "The more the better (right?)", with_w: "Enough to cover styles without cannibalisation" },
    { area: "How to spot problems", without: "When someone complains or stock piles up", with_w: "Automatic low-rotation and dead-stock alerts" },
    { area: "How to train the team", without: "Occasional verbal briefing", with_w: "Enriched tasting cards accessible during service" },
  ],
  solLabel: "The solution", solTitle1: "What Winerim brings to a ", solTitleHighlight: "large wine list",
  advantages: [
    { title: "Complete performance map", desc: "Visualise every reference by margin, rotation and demand." },
    { title: "Cannibalisation detection", desc: "Winerim cross-references price, region, style and grape to flag redundancies." },
    { title: "Dead-stock alerts", desc: "Notifications when a reference hasn't moved for too long." },
    { title: "Assortment optimisation", desc: "Data-driven recommendations to reduce, expand or rebalance the list." },
    { title: "Per-reference pricing", desc: "Each wine gets its optimal price based on its role within the list." },
    { title: "Decision reports", desc: "Ready-to-share reports for management or ownership." },
  ],
  howLabel: "In practice", howTitle: "How it works with a large wine list",
  useCases: [
    { title: "Quarterly audit", scenario: "The manager needs to drop 15 references from a 250-wine list.", result: "Winerim ranks the bottom 15 and suggests replacements." },
    { title: "Cannibalisation detection", scenario: "8 Rioja crianzas between €18–24 compete with each other.", result: "Identifies 3 redundant ones and shows how to redistribute sales." },
    { title: "Budget justification", scenario: "Ownership asks how many references are truly profitable.", result: "Automatic report: 35% of the list generates 80% of margin." },
  ],
  impactLabel: "Results", impactTitle: "Measurable impact on large lists",
  impactSubtitle: "Based on restaurants with 250+ references.",
  impacts: [
    { label: "Dead stock detected: 15–30%", desc: "Most large lists have 15–30% non-rotating references." },
    { label: "Overall margin +10–18%", desc: "Removing underperformers and adjusting pricing improves margin." },
    { label: "More profitable with fewer refs", desc: "A 20% reduction can boost sales through less cannibalisation." },
    { label: "Decisions 3× faster", desc: "With performance data, assortment decisions take minutes, not weeks." },
    { label: "More confident team", desc: "Fewer references plus enriched cards build staff confidence." },
    { label: "Less tied-up capital", desc: "Optimised assortment frees capital from dormant stock." },
  ],
  doesLabel: "What Winerim does", doesNotLabel: "What Winerim doesn't do", doesTitle: "Clear expectations",
  doesItems: [
    "Analyses every reference's performance with real data",
    "Detects cannibalisation between similar-profile wines",
    "Generates dead-stock and low-rotation alerts",
    "Suggests data-based assortment adjustments",
    "Optimises pricing per reference based on its list role",
    "Produces actionable reports for management",
  ],
  doesNotItems: [
    "Doesn't decide which wines to buy for you",
    "Doesn't manage cellar logistics",
    "Doesn't modify the list without your approval",
    "Is not a POS or supplier ordering system",
  ],
  faqs: [
    { q: "From how many references does Winerim make sense?", a: "From 80 references. The large-list solution is designed for 250+." },
    { q: "Does Winerim tell me which wines to remove?", a: "It shows a performance ranking. The final decision is always yours." },
    { q: "What is wine cannibalisation?", a: "Two or more similar-profile references competing, diluting each other's sales." },
    { q: "Can I generate reports for management?", a: "Yes. Reports with clear metrics, opportunities and action proposals." },
    { q: "How long does implementation take?", a: "For 250–500 references, 5–10 days with full support." },
    { q: "Can I try before subscribing?", a: "Yes. Free analysis of your current wine list." },
  ],
  ctaLabel: "Take the next step",
  ctaTitle: "How many of your references are actually working for you?",
  ctaDesc: "Request a free analysis and discover which part of your list generates margin.",
  ctaPrimary: "Analyse my list free", ctaSecondary: "Request demo",
  ctaMicro: "No commitment. Personalised report within 48 hours.",
  nextStepsTitle: "Next steps",
  nextSteps: [
    { label: "Free analysis", to: "/analisis-carta", description: "Detect dead stock and cannibalisation", type: "tool" as const },
    { label: "Guide: detect dead wines", to: "/guias/como-detectar-vinos-muertos-referencias-frenan-rentabilidad", description: "Step-by-step methodology", type: "guide" as const },
    { label: "Dead stock calculator", to: "/herramientas/calculadora-stock-muerto", description: "Estimate tied-up capital", type: "tool" as const },
  ],
  internalLinks: [
    { to: "/analisis-carta", label: "Free wine list analysis", type: "tool" },
    { to: "/guias/como-detectar-vinos-muertos-referencias-frenan-rentabilidad", label: "Detect dead wines", type: "guide" },
    { to: "/herramientas/calculadora-stock-muerto", label: "Dead stock calculator", type: "tool" },
    { to: "/casos-exito", label: "Case studies", type: "resource" },
    { to: "/soluciones/grupos-restauracion", label: "Restaurant groups", type: "solution" },
  ],
};

const IT: VerticalContent = {
  ...ES,
  metaTitle: "Winerim per Carte dei Vini Ampie | +250 Referenze sotto Controllo",
  metaDescription: "Gestisci carte dei vini ad alta complessità con Winerim: rileva stock morto, ottimizza rotazione.",
  canonicalUrl: "https://winerim.wine/it/soluzioni/carta-vini-ampia",
  badgeLabel: "Alta complessità",
  breadSolutions: "Soluzioni", breadLabel: "Carta ampia",
  heroTitle1: "Più referenze non significa più vendite. Significa ", heroTitleHighlight: "più rischio senza controllo",
  heroDesc: "Winerim trasforma carte ampie e complesse in asset redditizi: ogni referenza giustificata, ogni prezzo ottimizzato, ogni decisione basata sui dati.",
  ctaDemo: "Richiedi demo", ctaContact: "Parla con il team",
  heroSummary: "Una carta con più di 250 referenze può essere un vantaggio competitivo o una trappola finanziaria. Senza analisi, molte referenze non ruotano, si cannibalizzano e generano stock morto. Winerim fornisce l'intelligenza perché ogni vino nella tua carta abbia una ragione di esserci — e lo dimostri con i dati.",
  forTitle: "Winerim fa per la tua carta?", forLabel: "Perfetto se…", notForLabel: "Forse non per te se…",
  forItems: [
    "La tua carta ha più di 250 referenze e sospetti che molte non ruotino",
    "Non hai dati chiari su quali vini generano margine reale",
    "Hai notato vini che si cannibalizzano su prezzo o stile",
    "Vuoi ridurre la carta senza perdere profondità",
    "Devi giustificare ogni decisione di assortimento alla proprietà",
  ],
  notForItems: [
    "La tua carta ha meno di 80 referenze e la gestisci senza difficoltà",
    "Non consideri il vino una categoria strategica",
    "Preferisci decidere l'assortimento solo tramite i distributori",
  ],
  painLabel: "Il problema", painTitle1: "I pericoli di una carta ", painTitleHighlight: "troppo grande senza controllo",
  pains: [
    { text: "Stock morto invisibile: referenze che non si vendono da mesi, immobilizzando capitale e spazio." },
    { text: "Cannibalizzazione silenziosa: vini con profilo simile che competono tra loro, diluendo le vendite." },
    { text: "Paralisi della scelta: il cliente si sente sopraffatto e sceglie 'il secondo più economico'." },
    { text: "Impossibilità di formare il team: nessuno può conoscere 250+ referenze." },
    { text: "Pricing inconsistente: moltiplicatori generici per tutta la carta." },
    { text: "Revisioni alla cieca: cambiamenti basati sull'intuizione, non sui dati." },
    { text: "Costo opportunità: ogni referenza che non funziona occupa il posto di una che potrebbe generare margine." },
  ],
  tableLabel: "Confronto", tableTitle: "Gestione carta ampia: intuizione vs. dati",
  tableHeaders: ["Decisione", "Per intuizione", "Con Winerim"],
  tableRows: [
    { area: "Quali referenze mantenere", without: "Quelle che 'ci sono sempre state'", with_w: "Quelle che generano margine e ruotano" },
    { area: "Quali togliere", without: "Quelle esaurite dal distributore", with_w: "Le peggiori per performance reale" },
    { area: "Che prezzo mettere", without: "Costo × moltiplicatore uguale per tutti", with_w: "Prezzo per referenza: margine + domanda + posizione" },
    { area: "Quante referenze avere", without: "Più sono, meglio è", with_w: "Quante servono per coprire gli stili senza cannibalizzazione" },
    { area: "Come individuare problemi", without: "Quando si accumula stock", with_w: "Allerte automatiche di bassa rotazione" },
    { area: "Come formare il team", without: "Briefing verbale sporadico", with_w: "Schede tecniche accessibili durante il servizio" },
  ],
  solLabel: "La soluzione", solTitle1: "Cosa porta Winerim a una ", solTitleHighlight: "carta ampia",
  advantages: [
    { title: "Mappa completa delle performance", desc: "Visualizza ogni referenza per margine, rotazione e domanda." },
    { title: "Rilevamento cannibalizzazione", desc: "Winerim incrocia prezzo, regione, stile e vitigno per segnalare ridondanze." },
    { title: "Allerte stock morto", desc: "Notifiche quando una referenza resta ferma troppo a lungo." },
    { title: "Ottimizzazione assortimento", desc: "Raccomandazioni basate sui dati per ridurre o riequilibrare." },
    { title: "Pricing per referenza", desc: "Ogni vino ha il suo prezzo ottimale basato sul suo ruolo." },
    { title: "Report decisionali", desc: "Report pronti da condividere con la proprietà." },
  ],
  howLabel: "In pratica", howTitle: "Come funziona con una carta ampia",
  useCases: [
    { title: "Audit trimestrale", scenario: "Il responsabile deve togliere 15 referenze da 250.", result: "Winerim classifica le 15 peggiori e suggerisce sostituzioni." },
    { title: "Rilevamento cannibalizzazione", scenario: "8 Rioja crianza tra 18-24€ competono tra loro.", result: "Identifica 3 ridondanti e mostra come redistribuire le vendite." },
    { title: "Giustificazione budget", scenario: "La proprietà chiede quante referenze sono davvero redditizie.", result: "Report automatico: il 35% genera l'80% del margine." },
  ],
  impactLabel: "Risultati", impactTitle: "Impatto misurabile su carte ampie",
  impactSubtitle: "Basato su ristoranti con più di 250 referenze.",
  impacts: [
    { label: "Stock morto rilevato: 15–30%", desc: "La maggior parte delle carte ampie ha il 15–30% di referenze senza rotazione." },
    { label: "Margine globale +10–18%", desc: "Togliendo le referenze deboli e aggiustando i prezzi." },
    { label: "Più redditizia con meno refs", desc: "Ridurre del 20% può aumentare le vendite per minor cannibalizzazione." },
    { label: "Decisioni 3× più rapide", desc: "Con dati di performance, decidere cosa tenere richiede minuti." },
    { label: "Team più sicuro", desc: "Meno referenze e schede arricchite aumentano la fiducia dello staff." },
    { label: "Meno capitale immobilizzato", desc: "L'assortimento ottimizzato libera capitale dallo stock dormiente." },
  ],
  doesLabel: "Cosa fa Winerim", doesNotLabel: "Cosa non fa Winerim", doesTitle: "Aspettative chiare",
  doesItems: [
    "Analizza le performance di ogni referenza con dati reali",
    "Rileva cannibalizzazione tra vini con profilo simile",
    "Genera allerte di stock morto e bassa rotazione",
    "Suggerisce aggiustamenti basati sui dati",
    "Ottimizza il pricing per referenza",
    "Produce report azionabili per la direzione",
  ],
  doesNotItems: [
    "Non decide quali vini comprare per te",
    "Non gestisce la logistica di cantina",
    "Non modifica la carta senza la tua approvazione",
    "Non è un POS né un sistema ordini",
  ],
  faqs: [
    { q: "Da quante referenze ha senso Winerim?", a: "Da 80 referenze. La soluzione carta ampia è progettata per 250+." },
    { q: "Winerim mi dice quali vini togliere?", a: "Mostra un ranking di performance. La decisione finale è sempre tua." },
    { q: "Cos'è la cannibalizzazione dei vini?", a: "Due o più referenze con profilo simile che competono, diluendo le vendite." },
    { q: "Posso generare report per la direzione?", a: "Sì. Report con metriche chiare e proposte d'azione." },
    { q: "Quanto tempo richiede l'implementazione?", a: "Per 250–500 referenze, 5–10 giorni con supporto completo." },
    { q: "Posso provare prima di abbonarmi?", a: "Sì. Analisi gratuita della tua carta attuale." },
  ],
  ctaLabel: "Fai il prossimo passo",
  ctaTitle: "Quante delle tue referenze stanno davvero lavorando per te?",
  ctaDesc: "Richiedi un'analisi gratuita e scopri quale parte della tua carta genera margine.",
  ctaPrimary: "Analizza la mia carta gratis", ctaSecondary: "Richiedi demo",
  ctaMicro: "Senza impegno. Report personalizzato entro 48 ore.",
  nextStepsTitle: "Prossimi passi",
  nextSteps: ES.nextSteps,
  internalLinks: ES.internalLinks,
};

const FR: VerticalContent = {
  ...ES,
  metaTitle: "Winerim pour Grandes Cartes des Vins | +250 Références sous Contrôle",
  metaDescription: "Gérez les cartes des vins complexes avec Winerim : détectez le stock mort, optimisez la rotation.",
  canonicalUrl: "https://winerim.wine/fr/solutions/grande-carte-des-vins",
  badgeLabel: "Haute complexité",
  breadSolutions: "Solutions", breadLabel: "Grande carte",
  heroTitle1: "Plus de références ne signifie pas plus de ventes. Cela signifie ", heroTitleHighlight: "plus de risques sans contrôle",
  heroDesc: "Winerim transforme les grandes cartes complexes en actifs rentables : chaque référence justifiée, chaque prix optimisé, chaque décision basée sur les données.",
  ctaDemo: "Demander une démo", ctaContact: "Parler à l'équipe",
  heroSummary: "Une carte de plus de 250 références peut être un avantage concurrentiel ou un piège financier. Sans analytique, beaucoup ne tournent pas, se cannibalisent et génèrent du stock mort. Winerim fournit l'intelligence pour que chaque vin ait sa place — et le prouve par les données.",
  forTitle: "Winerim est-il pour votre carte ?", forLabel: "Parfait si…", notForLabel: "Peut-être pas si…",
  forItems: [
    "Votre carte a plus de 250 références et vous soupçonnez que beaucoup ne tournent pas",
    "Vous manquez de données claires sur les vins qui génèrent de la marge",
    "Vous avez remarqué des vins qui se cannibalisent",
    "Vous voulez réduire la carte sans perdre en profondeur",
    "Vous devez justifier chaque décision d'assortiment",
  ],
  notForItems: [
    "Votre carte a moins de 80 références et vous la gérez facilement",
    "Vous ne considérez pas le vin comme une catégorie stratégique",
    "Vous préférez décider de l'assortiment uniquement par relation avec les distributeurs",
  ],
  painLabel: "Le problème", painTitle1: "Les dangers d'une carte ", painTitleHighlight: "trop grande sans contrôle",
  pains: [
    { text: "Stock mort invisible : des références qui ne se vendent pas depuis des mois, immobilisant capital et espace." },
    { text: "Cannibalisation silencieuse : des vins au profil similaire en concurrence, diluant les ventes." },
    { text: "Paralysie du choix : le client est submergé et choisit 'le deuxième moins cher'." },
    { text: "Formation impossible : personne ne peut connaître 250+ références." },
    { text: "Pricing inconsistant : multiplicateurs génériques pour toute la carte." },
    { text: "Révisions à l'aveugle : changements basés sur l'intuition, pas sur les données." },
    { text: "Coût d'opportunité : chaque référence sous-performante occupe la place d'une qui pourrait générer de la marge." },
  ],
  tableLabel: "Comparatif", tableTitle: "Gestion grande carte : intuition vs. données",
  tableHeaders: ["Décision", "Par intuition", "Avec Winerim"],
  tableRows: [
    { area: "Quelles références garder", without: "Celles qui 'ont toujours été là'", with_w: "Celles qui génèrent de la marge et tournent" },
    { area: "Lesquelles retirer", without: "Celles en rupture chez le distributeur", with_w: "Les moins performantes selon les données réelles" },
    { area: "Quel prix fixer", without: "Coût × même multiplicateur pour tous", with_w: "Prix par référence : marge + demande + position" },
    { area: "Combien de références", without: "Plus il y en a, mieux c'est", with_w: "Assez pour couvrir les styles sans cannibalisation" },
    { area: "Comment détecter les problèmes", without: "Quand le stock s'accumule", with_w: "Alertes automatiques de faible rotation" },
    { area: "Comment former l'équipe", without: "Briefing verbal occasionnel", with_w: "Fiches techniques accessibles pendant le service" },
  ],
  solLabel: "La solution", solTitle1: "Ce que Winerim apporte à une ", solTitleHighlight: "grande carte",
  advantages: [
    { title: "Carte de performance complète", desc: "Visualisez chaque référence par marge, rotation et demande." },
    { title: "Détection de cannibalisation", desc: "Winerim croise prix, région, style et cépage pour signaler les redondances." },
    { title: "Alertes stock mort", desc: "Notifications quand une référence reste immobile trop longtemps." },
    { title: "Optimisation de l'assortiment", desc: "Recommandations basées sur les données pour réduire ou rééquilibrer." },
    { title: "Pricing par référence", desc: "Chaque vin a son prix optimal basé sur son rôle." },
    { title: "Rapports de décision", desc: "Rapports prêts à partager avec la direction." },
  ],
  howLabel: "En pratique", howTitle: "Comment ça fonctionne avec une grande carte",
  useCases: [
    { title: "Audit trimestriel", scenario: "Le responsable doit retirer 15 références sur 250.", result: "Winerim classe les 15 pires et suggère des remplacements." },
    { title: "Détection cannibalisation", scenario: "8 Rioja crianza entre 18-24€ en concurrence.", result: "Identifie 3 redondantes et montre comment redistribuer les ventes." },
    { title: "Justification budgétaire", scenario: "La direction demande combien de références sont vraiment rentables.", result: "Rapport automatique : 35% génère 80% de la marge." },
  ],
  impactLabel: "Résultats", impactTitle: "Impact mesurable sur les grandes cartes",
  impactSubtitle: "Basé sur des restaurants avec plus de 250 références.",
  impacts: [
    { label: "Stock mort détecté : 15–30%", desc: "La plupart des grandes cartes ont 15–30% de références sans rotation." },
    { label: "Marge globale +10–18%", desc: "En retirant les sous-performantes et en ajustant le pricing." },
    { label: "Plus rentable avec moins de refs", desc: "Réduire de 20% peut augmenter les ventes par moins de cannibalisation." },
    { label: "Décisions 3× plus rapides", desc: "Avec les données de performance, décider prend des minutes." },
    { label: "Équipe plus confiante", desc: "Moins de références et fiches enrichies renforcent la confiance." },
    { label: "Moins de capital immobilisé", desc: "L'assortiment optimisé libère le capital du stock dormant." },
  ],
  doesLabel: "Ce que Winerim fait", doesNotLabel: "Ce que Winerim ne fait pas", doesTitle: "Attentes claires",
  doesItems: [
    "Analyse la performance de chaque référence avec des données réelles",
    "Détecte la cannibalisation entre vins au profil similaire",
    "Génère des alertes de stock mort et faible rotation",
    "Suggère des ajustements basés sur les données",
    "Optimise le pricing par référence",
    "Produit des rapports actionnables pour la direction",
  ],
  doesNotItems: [
    "Ne décide pas quels vins acheter pour vous",
    "Ne gère pas la logistique de cave",
    "Ne modifie pas la carte sans votre approbation",
    "N'est pas un POS ni un système de commandes",
  ],
  faqs: [
    { q: "À partir de combien de références Winerim a-t-il du sens ?", a: "À partir de 80 références. La solution grande carte est conçue pour 250+." },
    { q: "Winerim me dit quels vins retirer ?", a: "Il montre un classement de performance. La décision finale est toujours la vôtre." },
    { q: "Qu'est-ce que la cannibalisation des vins ?", a: "Deux ou plus références au profil similaire en concurrence, diluant les ventes." },
    { q: "Puis-je générer des rapports pour la direction ?", a: "Oui. Rapports avec métriques claires et propositions d'action." },
    { q: "Combien de temps prend l'implémentation ?", a: "Pour 250–500 références, 5–10 jours avec support complet." },
    { q: "Puis-je essayer avant de m'abonner ?", a: "Oui. Analyse gratuite de votre carte actuelle." },
  ],
  ctaLabel: "Passez à l'étape suivante",
  ctaTitle: "Combien de vos références travaillent vraiment pour vous ?",
  ctaDesc: "Demandez une analyse gratuite et découvrez quelle partie de votre carte génère de la marge.",
  ctaPrimary: "Analyser ma carte gratuitement", ctaSecondary: "Demander une démo",
  ctaMicro: "Sans engagement. Rapport personnalisé sous 48 heures.",
  nextStepsTitle: "Prochaines étapes",
  nextSteps: ES.nextSteps,
  internalLinks: ES.internalLinks,
};

const i18n: I18nMap<VerticalContent> = { es: ES, en: EN, it: IT, fr: FR };

const CartaAmplia = () => {
  const { lang } = useLanguage();
  const t = i18n[lang] || i18n.es;
  return <VerticalTemplate t={t} />;
};
export default CartaAmplia;
