import GuideTemplate from "@/components/templates/GuideTemplate";
import type { GuidePageData } from "@/components/templates/GuideTemplate";
import { useLanguage } from "@/i18n/LanguageContext";
import type { SupportedLang, I18nMap, I18nMap } from "@/i18n/types";

const i18n: I18nMap<GuidePageData> = {
  es: {
    slug: "como-hacer-una-carta-de-vinos",
    metaTitle: "Cómo Hacer una Carta de Vinos Rentable | Guía Completa",
    metaDescription: "Aprende a diseñar una carta de vinos que venda: estructura, selección de referencias, pricing y presentación paso a paso para restaurantes.",
    heroTitle: "Cómo Hacer una Carta de Vinos",
    heroSubtitle: "Guía paso a paso para diseñar una carta de vinos rentable, bien estructurada y pensada para vender más en tu restaurante.",
    heroBadge: "Guía práctica",
    breadcrumbParent: { label: "Guías", href: "/guias-y-recursos" },
    ctaPrimaryText: "Solicitar demo",
    ctaPrimaryUrl: "/demo",
    ctaSecondaryText: "Analiza tu carta",
    ctaSecondaryUrl: "/analisis-carta",
    ctaFinalTitle: "Diseña una carta de vinos que venda",
    ctaFinalDescription: "Winerim te ayuda a crear, optimizar y gestionar tu carta de vinos con datos, IA y herramientas pensadas para restaurantes.",
    tableOfContents: [
      "Define el perfil de tu restaurante",
      "Selecciona las referencias adecuadas",
      "Estructura la carta por secciones",
      "Fija los precios correctamente",
      "Diseña la presentación visual",
      "Incluye vino por copa",
      "Actualiza y optimiza periódicamente",
    ],
    sections: [
      {
        heading: "1. Define el perfil de tu restaurante",
        content: "Antes de elegir un solo vino, necesitas entender qué tipo de experiencia ofrece tu restaurante. La carta de vinos debe estar alineada con tu cocina, tu público y tu ticket medio.\n\nUn steakhouse no necesita la misma carta que un restaurante japonés. Un wine bar no tiene las mismas necesidades que un hotel con restaurante.",
        tips: [
          "Analiza tu menú gastronómico: ¿qué tipo de platos predominan?",
          "Identifica a tu cliente tipo: ¿busca explorar vinos o quiere una elección segura?",
          "Define tu rango de precios objetivo: ¿cuál es el ticket medio que buscas en vino?",
          "Estudia a tu competencia directa: ¿qué ofrecen y dónde puedes diferenciarte?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Selecciona las referencias adecuadas",
        content: "El número de referencias es clave. Demasiadas generan parálisis de elección y aumentan el stock muerto. Muy pocas limitan las oportunidades de venta.\n\nLa regla general es: entre 40 y 80 referencias para un restaurante medio, entre 100 y 200 para restaurantes con foco en vino.",
        tips: [
          "Incluye un equilibrio entre blancos, tintos, rosados y espumosos",
          "No olvides opciones accesibles: el vino de entrada es el que más se vende",
          "Añade 2-3 referencias premium que eleven el ticket medio",
          "Incorpora vinos locales o de denominación que conecten con tu identidad",
          "Rota las referencias que no se venden en 60-90 días",
        ],
        icon: "list",
      },
      {
        heading: "3. Estructura la carta por secciones",
        content: "Una carta bien estructurada guía al cliente hacia la decisión de compra. No se trata de listar vinos, sino de crear un recorrido lógico.\n\nLas estructuras más efectivas agrupan por estilo (fresco, afrutado, estructurado) o por momento de consumo, no solo por región o uva.",
        tips: [
          "Agrupa por estilo sensorial: fresco, afrutado, intenso, elegante",
          "Crea categorías claras con títulos descriptivos, no técnicos",
          "Coloca los vinos con mejor margen en las posiciones de mayor visibilidad",
          "Usa la técnica del ʻanclajeʼ: sitúa un vino premium junto a los de margen objetivo",
        ],
        icon: "check",
      },
      {
        heading: "4. Fija los precios correctamente",
        content: "El pricing del vino es uno de los factores que más impactan en la rentabilidad del restaurante. Un error común es aplicar un multiplicador fijo (x2, x3) sin considerar la elasticidad del precio.\n\nLos vinos de entrada deben tener un margen porcentual menor pero un volumen de venta alto. Los vinos premium pueden tener un margen bruto mayor con menor rotación.",
        tips: [
          "No uses un multiplicador fijo: adapta el margen por franja de precio",
          "Los vinos de 15-25€ en carta son los más vendidos: optimiza esa franja",
          "El vino más barato de la carta marca la percepción de precio: cuídalo",
          "Revisa los precios cada trimestre en función de las ventas reales",
        ],
        icon: "alert",
      },
      {
        heading: "5. Diseña la presentación visual",
        content: "La forma en que presentas la carta influye directamente en la decisión del cliente. Una carta clara, limpia y bien diseñada genera confianza y facilita la elección.\n\nLas cartas digitales permiten añadir notas de cata, maridajes y filtros que una carta en papel no puede ofrecer.",
        tips: [
          "Usa tipografías legibles y un diseño limpio sin saturar de información",
          "Incluye notas de cata breves que ayuden al cliente a elegir",
          "Añade sugerencias de maridaje junto a cada vino o sección",
          "Considera una carta digital que permita filtros y recomendaciones inteligentes",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Incluye vino por copa",
        content: "El vino por copa es una de las herramientas más potentes para aumentar las ventas de vino. Reduce la barrera de entrada, permite explorar y genera márgenes superiores.\n\nLa selección de vino por copa debe rotar y estar alineada con la temporada y el menú.",
        tips: [
          "Ofrece entre 6 y 12 referencias por copa como punto de partida",
          "Incluye al menos un espumoso, un blanco, un rosado y dos tintos",
          "Fija el precio de la copa al equivalente del 30-40% de la botella",
          "Rota las referencias por copa cada 2-4 semanas para generar novedad",
        ],
        icon: "check",
      },
      {
        heading: "7. Actualiza y optimiza periódicamente",
        content: "Una carta de vinos no es estática. Debe evolucionar con los datos de venta, la temporada y la oferta gastronómica.\n\nLos restaurantes que revisan su carta trimestralmente venden entre un 15% y un 25% más de vino que los que la mantienen fija durante todo el año.",
        tips: [
          "Revisa las ventas por referencia cada mes y elimina los vinos que no rotan",
          "Ajusta la carta a la temporada: blancos frescos en verano, tintos potentes en invierno",
          "Analiza qué secciones de la carta generan más conversión",
          "Usa herramientas como Winerim para obtener datos reales de rendimiento",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "¿Cuántos vinos debe tener una carta de restaurante?", a: "Depende del tipo de restaurante. Un restaurante medio debería tener entre 40 y 80 referencias. Los restaurantes con foco en vino pueden llegar a 150-200. Lo importante es que cada referencia justifique su presencia con datos de venta." },
      { q: "¿Es mejor organizar la carta por región o por estilo?", a: "Organizar por estilo sensorial (fresco, afrutado, intenso) es más efectivo para la mayoría de restaurantes. Facilita la elección del cliente y permite recomendar mejor. La organización por región funciona mejor en restaurantes especializados." },
      { q: "¿Qué margen debe tener el vino en un restaurante?", a: "No hay un margen único. Los vinos de entrada (coste < 5€) suelen venderse con un multiplicador x3-x4. Los vinos de gama media (5-15€ coste) con x2.5-x3. Los premium (>15€ coste) con x2-x2.5. Lo importante es optimizar el margen bruto total, no el porcentaje individual." },
      { q: "¿Cómo sé si mi carta de vinos funciona bien?", a: "Mide tres indicadores clave: porcentaje de mesas que piden vino, ticket medio en vino por mesa, y rotación de referencias. Si más del 30% de las referencias no se venden en 90 días, tu carta necesita optimización." },
      { q: "¿Qué ventajas tiene una carta de vinos digital?", a: "Una carta digital permite filtros inteligentes, recomendaciones personalizadas, maridajes automáticos, actualización en tiempo real y análisis de datos de consumo. Todo esto se traduce en más ventas y mejor experiencia." },
    ],
    relatedTools: [
      { label: "Calculadora de margen de vino", url: "/calculadora-margen-vino" },
      { label: "Analizador de carta de vinos", url: "/analisis-carta" },
    ],
    relatedGuides: [
      { label: "Cómo vender más vino en un restaurante", url: "/como-vender-mas-vino-en-un-restaurante" },
      { label: "Cómo fijar el precio del vino", url: "/precio-vino-restaurante" },
      { label: "Vino por copa en restaurante", url: "/vino-por-copa-restaurante" },
      { label: "Carta papel vs carta digital", url: "/carta-papel-vs-digital" },
    ],
  },
  en: {
    slug: "how-to-create-a-wine-list",
    metaTitle: "How to Create a Profitable Wine List | Complete Guide",
    metaDescription: "Learn how to design a wine list that sells: structure, reference selection, pricing and presentation step by step for restaurants.",
    heroTitle: "How to Create a Wine List",
    heroSubtitle: "Step-by-step guide to designing a profitable, well-structured wine list built to sell more at your restaurant.",
    heroBadge: "Practical guide",
    breadcrumbParent: { label: "Guides", href: "/en/guides" },
    ctaPrimaryText: "Request demo",
    ctaPrimaryUrl: "/en/demo",
    ctaSecondaryText: "Analyze your list",
    ctaSecondaryUrl: "/en/wine-list-analysis",
    ctaFinalTitle: "Design a wine list that sells",
    ctaFinalDescription: "Winerim helps you create, optimize and manage your wine list with data, AI and tools built for restaurants.",
    tableOfContents: [
      "Define your restaurant's profile",
      "Select the right references",
      "Structure the list by sections",
      "Set prices correctly",
      "Design the visual presentation",
      "Include wine by the glass",
      "Update and optimize regularly",
    ],
    sections: [
      {
        heading: "1. Define your restaurant's profile",
        content: "Before choosing a single wine, you need to understand what kind of experience your restaurant offers. The wine list must align with your cuisine, clientele and average ticket.\n\nA steakhouse doesn't need the same list as a Japanese restaurant. A wine bar has different needs than a hotel restaurant.",
        tips: [
          "Analyze your food menu: what type of dishes predominate?",
          "Identify your typical guest: are they looking to explore or want a safe choice?",
          "Define your target price range: what average wine ticket are you aiming for?",
          "Study your direct competitors: what do they offer and where can you differentiate?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Select the right references",
        content: "The number of references is key. Too many create choice paralysis and increase dead stock. Too few limit sales opportunities.\n\nThe general rule: 40 to 80 references for an average restaurant, 100 to 200 for wine-focused venues.",
        tips: [
          "Include a balance of whites, reds, rosés and sparkling wines",
          "Don't forget accessible options: entry-level wine sells the most",
          "Add 2-3 premium references to raise the average ticket",
          "Include local or appellation wines that connect with your identity",
          "Rotate references that haven't sold in 60-90 days",
        ],
        icon: "list",
      },
      {
        heading: "3. Structure the list by sections",
        content: "A well-structured list guides the guest toward a purchase decision. It's not about listing wines, but creating a logical journey.\n\nThe most effective structures group by style (fresh, fruity, structured) or by consumption moment, not just by region or grape.",
        tips: [
          "Group by sensory style: fresh, fruity, intense, elegant",
          "Create clear categories with descriptive, non-technical titles",
          "Place highest-margin wines in the most visible positions",
          "Use the anchoring technique: place a premium wine next to your target-margin options",
        ],
        icon: "check",
      },
      {
        heading: "4. Set prices correctly",
        content: "Wine pricing is one of the factors that most impact restaurant profitability. A common mistake is applying a fixed multiplier (x2, x3) without considering price elasticity.\n\nEntry wines should have a lower percentage margin but high sales volume. Premium wines can have a higher gross margin with lower turnover.",
        tips: [
          "Don't use a fixed multiplier: adapt the margin by price range",
          "Wines priced €15-25 on the list are the best sellers: optimize that range",
          "The cheapest wine on the list sets the price perception: choose carefully",
          "Review prices quarterly based on actual sales data",
        ],
        icon: "alert",
      },
      {
        heading: "5. Design the visual presentation",
        content: "How you present the list directly influences the guest's decision. A clear, clean, well-designed list builds trust and makes choosing easier.\n\nDigital lists allow tasting notes, pairings and filters that a paper list can't offer.",
        tips: [
          "Use legible fonts and a clean design without information overload",
          "Include brief tasting notes to help guests choose",
          "Add pairing suggestions next to each wine or section",
          "Consider a digital list with smart filters and recommendations",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Include wine by the glass",
        content: "Wine by the glass is one of the most powerful tools for boosting wine sales. It lowers the barrier to entry, encourages exploration and generates higher margins.\n\nThe by-the-glass selection should rotate and align with the season and menu.",
        tips: [
          "Offer 6 to 12 by-the-glass references as a starting point",
          "Include at least one sparkling, one white, one rosé and two reds",
          "Set the glass price at 30-40% of the bottle price",
          "Rotate by-the-glass references every 2-4 weeks to create novelty",
        ],
        icon: "check",
      },
      {
        heading: "7. Update and optimize regularly",
        content: "A wine list is not static. It must evolve with sales data, seasonality and the food offer.\n\nRestaurants that review their list quarterly sell 15-25% more wine than those that keep it fixed all year.",
        tips: [
          "Review sales by reference every month and remove wines that don't rotate",
          "Adjust the list to the season: fresh whites in summer, bold reds in winter",
          "Analyze which sections of the list generate the most conversions",
          "Use tools like Winerim to get real performance data",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "How many wines should a restaurant list have?", a: "It depends on the type of restaurant. An average restaurant should have 40-80 references. Wine-focused venues can reach 150-200. The key is that each reference justifies its presence with sales data." },
      { q: "Is it better to organize by region or by style?", a: "Organizing by sensory style (fresh, fruity, intense) is more effective for most restaurants. It facilitates guest choice and enables better recommendations. Regional organization works better in specialized venues." },
      { q: "What margin should wine have in a restaurant?", a: "There's no single margin. Entry wines (cost < €5) typically sell at x3-x4 markup. Mid-range (€5-15 cost) at x2.5-x3. Premium (>€15 cost) at x2-x2.5. The key is optimizing total gross margin, not individual percentages." },
      { q: "How do I know if my wine list is performing well?", a: "Measure three key indicators: percentage of tables ordering wine, average wine ticket per table, and reference rotation. If more than 30% of references don't sell in 90 days, your list needs optimization." },
      { q: "What are the advantages of a digital wine list?", a: "A digital list enables smart filters, personalized recommendations, automatic pairings, real-time updates and consumption data analysis. All of this translates into more sales and a better experience." },
    ],
    relatedTools: [
      { label: "Wine margin calculator", url: "/en/wine-margin-calculator" },
      { label: "Wine list analyzer", url: "/en/wine-list-analysis" },
    ],
    relatedGuides: [
      { label: "How to sell more wine in restaurants", url: "/en/how-to-sell-more-wine-in-restaurants" },
      { label: "How to price wine at a restaurant", url: "/en/wine-pricing-restaurant" },
      { label: "Wine by the glass at restaurants", url: "/en/wine-by-glass-restaurant" },
      { label: "Paper vs digital wine list", url: "/en/paper-vs-digital-wine-list" },
    ],
  },
  it: {
    slug: "come-creare-una-carta-dei-vini",
    metaTitle: "Come Creare una Carta dei Vini Redditizia | Guida Completa",
    metaDescription: "Scopri come progettare una carta dei vini che venda: struttura, selezione referenze, pricing e presentazione passo dopo passo per ristoranti.",
    heroTitle: "Come Creare una Carta dei Vini",
    heroSubtitle: "Guida passo dopo passo per progettare una carta dei vini redditizia, ben strutturata e pensata per vendere di più nel tuo ristorante.",
    heroBadge: "Guida pratica",
    breadcrumbParent: { label: "Guide", href: "/it/guide" },
    ctaPrimaryText: "Richiedi demo",
    ctaPrimaryUrl: "/it/demo",
    ctaSecondaryText: "Analizza la tua carta",
    ctaSecondaryUrl: "/it/analisi-carta",
    ctaFinalTitle: "Progetta una carta dei vini che venda",
    ctaFinalDescription: "Winerim ti aiuta a creare, ottimizzare e gestire la tua carta dei vini con dati, IA e strumenti pensati per la ristorazione.",
    tableOfContents: [
      "Definisci il profilo del tuo ristorante",
      "Seleziona le referenze giuste",
      "Struttura la carta per sezioni",
      "Fissa i prezzi correttamente",
      "Progetta la presentazione visiva",
      "Includi il vino al calice",
      "Aggiorna e ottimizza periodicamente",
    ],
    sections: [
      {
        heading: "1. Definisci il profilo del tuo ristorante",
        content: "Prima di scegliere un solo vino, devi capire che tipo di esperienza offre il tuo ristorante. La carta dei vini deve essere allineata con la tua cucina, il tuo pubblico e il tuo scontrino medio.\n\nUna steakhouse non ha bisogno della stessa carta di un ristorante giapponese. Un wine bar ha esigenze diverse da un hotel con ristorante.",
        tips: [
          "Analizza il tuo menu gastronomico: quale tipo di piatti predomina?",
          "Identifica il tuo cliente tipo: cerca di esplorare vini o vuole una scelta sicura?",
          "Definisci la tua fascia di prezzo obiettivo: quale scontrino medio punti per il vino?",
          "Studia la concorrenza diretta: cosa offrono e dove puoi differenziarti?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Seleziona le referenze giuste",
        content: "Il numero di referenze è fondamentale. Troppe generano paralisi della scelta e aumentano lo stock morto. Troppo poche limitano le opportunità di vendita.\n\nLa regola generale: tra 40 e 80 referenze per un ristorante medio, tra 100 e 200 per ristoranti focalizzati sul vino.",
        tips: [
          "Includi un equilibrio tra bianchi, rossi, rosati e spumanti",
          "Non dimenticare le opzioni accessibili: il vino d'ingresso è quello che si vende di più",
          "Aggiungi 2-3 referenze premium per alzare lo scontrino medio",
          "Inserisci vini locali o di denominazione che si colleghino alla tua identità",
          "Ruota le referenze che non si vendono in 60-90 giorni",
        ],
        icon: "list",
      },
      {
        heading: "3. Struttura la carta per sezioni",
        content: "Una carta ben strutturata guida il cliente verso la decisione d'acquisto. Non si tratta di elencare vini, ma di creare un percorso logico.\n\nLe strutture più efficaci raggruppano per stile (fresco, fruttato, strutturato) o per momento di consumo, non solo per regione o vitigno.",
        tips: [
          "Raggruppa per stile sensoriale: fresco, fruttato, intenso, elegante",
          "Crea categorie chiare con titoli descrittivi, non tecnici",
          "Posiziona i vini con margine migliore nelle posizioni di maggiore visibilità",
          "Usa la tecnica dell'ancoraggio: posiziona un vino premium accanto a quelli a margine obiettivo",
        ],
        icon: "check",
      },
      {
        heading: "4. Fissa i prezzi correttamente",
        content: "Il pricing del vino è uno dei fattori che più impattano sulla redditività del ristorante. Un errore comune è applicare un moltiplicatore fisso (x2, x3) senza considerare l'elasticità del prezzo.\n\nI vini d'ingresso devono avere un margine percentuale inferiore ma un volume di vendita alto. I vini premium possono avere un margine lordo maggiore con minore rotazione.",
        tips: [
          "Non usare un moltiplicatore fisso: adatta il margine per fascia di prezzo",
          "I vini tra 15-25€ in carta sono i più venduti: ottimizza quella fascia",
          "Il vino più economico in carta segna la percezione del prezzo: curalo",
          "Rivedi i prezzi ogni trimestre in base alle vendite reali",
        ],
        icon: "alert",
      },
      {
        heading: "5. Progetta la presentazione visiva",
        content: "Il modo in cui presenti la carta influenza direttamente la decisione del cliente. Una carta chiara, pulita e ben progettata genera fiducia e facilita la scelta.\n\nLe carte digitali permettono di aggiungere note di degustazione, abbinamenti e filtri che una carta cartacea non può offrire.",
        tips: [
          "Usa font leggibili e un design pulito senza sovraccaricare di informazioni",
          "Includi brevi note di degustazione per aiutare il cliente a scegliere",
          "Aggiungi suggerimenti di abbinamento accanto a ogni vino o sezione",
          "Considera una carta digitale con filtri e raccomandazioni intelligenti",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Includi il vino al calice",
        content: "Il vino al calice è uno degli strumenti più potenti per aumentare le vendite di vino. Riduce la barriera d'ingresso, permette di esplorare e genera margini superiori.\n\nLa selezione al calice deve ruotare ed essere allineata con la stagione e il menu.",
        tips: [
          "Offri tra 6 e 12 referenze al calice come punto di partenza",
          "Includi almeno uno spumante, un bianco, un rosato e due rossi",
          "Fissa il prezzo del calice al 30-40% equivalente della bottiglia",
          "Ruota le referenze al calice ogni 2-4 settimane per creare novità",
        ],
        icon: "check",
      },
      {
        heading: "7. Aggiorna e ottimizza periodicamente",
        content: "Una carta dei vini non è statica. Deve evolvere con i dati di vendita, la stagionalità e l'offerta gastronomica.\n\nI ristoranti che revisionano la carta trimestralmente vendono il 15-25% in più di vino rispetto a quelli che la mantengono fissa tutto l'anno.",
        tips: [
          "Rivedi le vendite per referenza ogni mese ed elimina i vini che non ruotano",
          "Adatta la carta alla stagione: bianchi freschi in estate, rossi potenti in inverno",
          "Analizza quali sezioni della carta generano più conversione",
          "Usa strumenti come Winerim per ottenere dati reali di performance",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Quanti vini deve avere una carta di un ristorante?", a: "Dipende dal tipo di ristorante. Un ristorante medio dovrebbe avere tra 40 e 80 referenze. I ristoranti focalizzati sul vino possono arrivare a 150-200. L'importante è che ogni referenza giustifichi la sua presenza con dati di vendita." },
      { q: "È meglio organizzare per regione o per stile?", a: "Organizzare per stile sensoriale (fresco, fruttato, intenso) è più efficace per la maggior parte dei ristoranti. Facilita la scelta del cliente e permette di consigliare meglio. L'organizzazione per regione funziona meglio nei ristoranti specializzati." },
      { q: "Quale margine deve avere il vino in un ristorante?", a: "Non esiste un margine unico. I vini d'ingresso (costo < 5€) si vendono con moltiplicatore x3-x4. I vini di gamma media (5-15€ costo) con x2,5-x3. I premium (>15€ costo) con x2-x2,5. L'importante è ottimizzare il margine lordo totale." },
      { q: "Come faccio a sapere se la mia carta dei vini funziona bene?", a: "Misura tre indicatori chiave: percentuale di tavoli che ordinano vino, scontrino medio vino per tavolo e rotazione delle referenze. Se più del 30% delle referenze non si vende in 90 giorni, la tua carta ha bisogno di ottimizzazione." },
      { q: "Quali vantaggi ha una carta dei vini digitale?", a: "Una carta digitale permette filtri intelligenti, raccomandazioni personalizzate, abbinamenti automatici, aggiornamento in tempo reale e analisi dei dati di consumo. Tutto questo si traduce in più vendite e migliore esperienza." },
    ],
    relatedTools: [
      { label: "Calcolatrice margini vino", url: "/it/calcolatrice-margini-vino" },
      { label: "Analizzatore carta dei vini", url: "/it/analisi-carta" },
    ],
    relatedGuides: [
      { label: "Come vendere più vino al ristorante", url: "/it/come-vendere-piu-vino-ristorante" },
      { label: "Come fissare il prezzo del vino", url: "/it/prezzo-vino-ristorante" },
      { label: "Vino al calice al ristorante", url: "/it/vino-al-calice-ristorante" },
      { label: "Carta cartacea vs digitale", url: "/it/carta-cartacea-vs-digitale" },
    ],
  },
  fr: {
    slug: "comment-creer-une-carte-des-vins",
    metaTitle: "Comment Créer une Carte des Vins Rentable | Guide Complet",
    metaDescription: "Apprenez à concevoir une carte des vins qui vend : structure, sélection de références, pricing et présentation étape par étape pour restaurants.",
    heroTitle: "Comment Créer une Carte des Vins",
    heroSubtitle: "Guide étape par étape pour concevoir une carte des vins rentable, bien structurée et conçue pour vendre plus dans votre restaurant.",
    heroBadge: "Guide pratique",
    breadcrumbParent: { label: "Guides", href: "/fr/guides" },
    ctaPrimaryText: "Demander une démo",
    ctaPrimaryUrl: "/fr/demo",
    ctaSecondaryText: "Analyser votre carte",
    ctaSecondaryUrl: "/fr/analyse-carte",
    ctaFinalTitle: "Concevez une carte des vins qui vend",
    ctaFinalDescription: "Winerim vous aide à créer, optimiser et gérer votre carte des vins avec des données, l'IA et des outils conçus pour la restauration.",
    tableOfContents: [
      "Définissez le profil de votre restaurant",
      "Sélectionnez les bonnes références",
      "Structurez la carte par sections",
      "Fixez les prix correctement",
      "Concevez la présentation visuelle",
      "Incluez le vin au verre",
      "Mettez à jour et optimisez régulièrement",
    ],
    sections: [
      {
        heading: "1. Définissez le profil de votre restaurant",
        content: "Avant de choisir un seul vin, vous devez comprendre quel type d'expérience votre restaurant propose. La carte des vins doit être alignée avec votre cuisine, votre clientèle et votre ticket moyen.\n\nUn steakhouse n'a pas besoin de la même carte qu'un restaurant japonais. Un bar à vin n'a pas les mêmes besoins qu'un hôtel-restaurant.",
        tips: [
          "Analysez votre menu gastronomique : quel type de plats prédomine ?",
          "Identifiez votre client type : cherche-t-il à explorer ou veut-il un choix sûr ?",
          "Définissez votre fourchette de prix cible : quel ticket moyen vin visez-vous ?",
          "Étudiez vos concurrents directs : que proposent-ils et où pouvez-vous vous différencier ?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Sélectionnez les bonnes références",
        content: "Le nombre de références est clé. Trop de références créent la paralysie du choix et augmentent le stock mort. Trop peu limitent les opportunités de vente.\n\nLa règle générale : entre 40 et 80 références pour un restaurant moyen, entre 100 et 200 pour les établissements axés sur le vin.",
        tips: [
          "Incluez un équilibre entre blancs, rouges, rosés et effervescents",
          "N'oubliez pas les options accessibles : le vin d'entrée est celui qui se vend le plus",
          "Ajoutez 2-3 références premium pour augmenter le ticket moyen",
          "Intégrez des vins locaux ou d'appellation qui résonnent avec votre identité",
          "Faites tourner les références qui ne se vendent pas en 60-90 jours",
        ],
        icon: "list",
      },
      {
        heading: "3. Structurez la carte par sections",
        content: "Une carte bien structurée guide le client vers la décision d'achat. Il ne s'agit pas de lister des vins, mais de créer un parcours logique.\n\nLes structures les plus efficaces regroupent par style (frais, fruité, structuré) ou par moment de consommation, pas uniquement par région ou cépage.",
        tips: [
          "Regroupez par style sensoriel : frais, fruité, intense, élégant",
          "Créez des catégories claires avec des titres descriptifs, pas techniques",
          "Placez les vins à meilleure marge aux positions les plus visibles",
          "Utilisez la technique d'ancrage : placez un vin premium à côté de vos options à marge cible",
        ],
        icon: "check",
      },
      {
        heading: "4. Fixez les prix correctement",
        content: "Le pricing du vin est l'un des facteurs qui impactent le plus la rentabilité du restaurant. Une erreur courante est d'appliquer un multiplicateur fixe (x2, x3) sans considérer l'élasticité des prix.\n\nLes vins d'entrée doivent avoir une marge en pourcentage plus faible mais un volume de vente élevé. Les vins premium peuvent avoir une marge brute plus élevée avec une rotation plus faible.",
        tips: [
          "N'utilisez pas un multiplicateur fixe : adaptez la marge par tranche de prix",
          "Les vins à 15-25€ en carte sont les plus vendus : optimisez cette tranche",
          "Le vin le moins cher de la carte fixe la perception du prix : soignez-le",
          "Revoyez les prix chaque trimestre en fonction des ventes réelles",
        ],
        icon: "alert",
      },
      {
        heading: "5. Concevez la présentation visuelle",
        content: "La façon dont vous présentez la carte influence directement la décision du client. Une carte claire, épurée et bien conçue inspire confiance et facilite le choix.\n\nLes cartes digitales permettent d'ajouter des notes de dégustation, des accords et des filtres qu'une carte papier ne peut pas offrir.",
        tips: [
          "Utilisez des typographies lisibles et un design épuré sans surcharger d'informations",
          "Incluez de brèves notes de dégustation pour aider le client à choisir",
          "Ajoutez des suggestions d'accord à côté de chaque vin ou section",
          "Envisagez une carte digitale avec filtres et recommandations intelligentes",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Incluez le vin au verre",
        content: "Le vin au verre est l'un des outils les plus puissants pour augmenter les ventes de vin. Il réduit la barrière à l'entrée, permet d'explorer et génère des marges supérieures.\n\nLa sélection au verre doit tourner et être alignée avec la saison et le menu.",
        tips: [
          "Proposez 6 à 12 références au verre comme point de départ",
          "Incluez au moins un effervescent, un blanc, un rosé et deux rouges",
          "Fixez le prix du verre à l'équivalent de 30-40% de la bouteille",
          "Faites tourner les références au verre toutes les 2-4 semaines pour créer de la nouveauté",
        ],
        icon: "check",
      },
      {
        heading: "7. Mettez à jour et optimisez régulièrement",
        content: "Une carte des vins n'est pas statique. Elle doit évoluer avec les données de vente, la saisonnalité et l'offre gastronomique.\n\nLes restaurants qui révisent leur carte trimestriellement vendent 15-25% de vin en plus par rapport à ceux qui la maintiennent fixe toute l'année.",
        tips: [
          "Passez en revue les ventes par référence chaque mois et éliminez les vins qui ne tournent pas",
          "Adaptez la carte à la saison : blancs frais en été, rouges puissants en hiver",
          "Analysez quelles sections de la carte génèrent le plus de conversions",
          "Utilisez des outils comme Winerim pour obtenir des données de performance réelles",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Combien de vins doit avoir une carte de restaurant ?", a: "Cela dépend du type de restaurant. Un restaurant moyen devrait avoir 40 à 80 références. Les établissements axés sur le vin peuvent aller jusqu'à 150-200. L'essentiel est que chaque référence justifie sa présence par des données de vente." },
      { q: "Vaut-il mieux organiser par région ou par style ?", a: "Organiser par style sensoriel (frais, fruité, intense) est plus efficace pour la plupart des restaurants. Cela facilite le choix du client et permet de mieux conseiller. L'organisation par région fonctionne mieux dans les établissements spécialisés." },
      { q: "Quelle marge doit avoir le vin dans un restaurant ?", a: "Il n'y a pas de marge unique. Les vins d'entrée (coût < 5€) se vendent avec un multiplicateur x3-x4. Les vins de gamme moyenne (5-15€ coût) en x2,5-x3. Les premium (>15€ coût) en x2-x2,5. L'essentiel est d'optimiser la marge brute totale." },
      { q: "Comment savoir si ma carte des vins fonctionne bien ?", a: "Mesurez trois indicateurs clés : pourcentage de tables qui commandent du vin, ticket moyen vin par table et rotation des références. Si plus de 30% des références ne se vendent pas en 90 jours, votre carte a besoin d'optimisation." },
      { q: "Quels sont les avantages d'une carte des vins digitale ?", a: "Une carte digitale permet des filtres intelligents, des recommandations personnalisées, des accords automatiques, une mise à jour en temps réel et une analyse des données de consommation. Tout cela se traduit par plus de ventes et une meilleure expérience." },
    ],
    relatedTools: [
      { label: "Calculateur de marge vin", url: "/fr/calculateur-marge-vin" },
      { label: "Analyseur de carte des vins", url: "/fr/analyse-carte" },
    ],
    relatedGuides: [
      { label: "Comment vendre plus de vin au restaurant", url: "/fr/comment-vendre-plus-vin-restaurant" },
      { label: "Comment fixer le prix du vin", url: "/fr/prix-vin-restaurant" },
      { label: "Vin au verre au restaurant", url: "/fr/vin-au-verre-restaurant" },
      { label: "Carte papier vs digitale", url: "/fr/carte-papier-vs-digitale" },
    ],
  },
};

const ComoHacerCartaVinos = () => {
  const { lang } = useLanguage();
  return <GuideTemplate data={i18n[lang]} />;
};

export default ComoHacerCartaVinos;
