import GuideTemplate from "@/components/templates/GuideTemplate";
import type { GuidePageData } from "@/components/templates/GuideTemplate";
import { useLanguage } from "@/i18n/LanguageContext";
import type { SupportedLang, I18nMap } from "@/i18n/types";
import { getI18n } from "@/i18n/types";

const i18n: I18nMap<GuidePageData> = {
  es: {
    slug: "como-hacer-una-carta-de-vinos",
    metaTitle: "Cómo Hacer una Carta de Vinos Rentable | Guía Completa",
    metaDescription: "Aprende a diseñar una carta de vinos que venda: estructura, selección de referencias, pricing y presentación paso a paso para restaurantes.",
    heroTitle: "Cómo Hacer una Carta de Vinos",
    heroSubtitle: "Guía paso a paso para diseñar una carta de vinos rentable, bien estructurada y pensada para vender más en tu restaurante.",
    heroBadge: "Guía práctica",
    breadcrumbParent: { label: "Guías", href: "/guias-y-recursos" },
    ctaPrimaryText: "Solicitar demo",
    ctaPrimaryUrl: "/demo",
    ctaSecondaryText: "Analiza tu carta",
    ctaSecondaryUrl: "/analisis-carta",
    ctaFinalTitle: "Diseña una carta de vinos que venda",
    ctaFinalDescription: "Winerim te ayuda a crear, optimizar y gestionar tu carta de vinos con datos, IA y herramientas pensadas para restaurantes.",
    tableOfContents: [
      "Define el perfil de tu restaurante",
      "Selecciona las referencias adecuadas",
      "Estructura la carta por secciones",
      "Fija los precios correctamente",
      "Diseña la presentación visual",
      "Incluye vino por copa",
      "Actualiza y optimiza periódicamente",
    ],
    sections: [
      {
        heading: "1. Define el perfil de tu restaurante",
        content: "Antes de elegir un solo vino, necesitas entender qué tipo de experiencia ofrece tu restaurante. La carta de vinos debe estar alineada con tu cocina, tu público y tu ticket medio.\n\nUn steakhouse no necesita la misma carta que un restaurante japonés. Un wine bar no tiene las mismas necesidades que un hotel con restaurante.",
        tips: [
          "Analiza tu menú gastronómico: ¿qué tipo de platos predominan?",
          "Identifica a tu cliente tipo: ¿busca explorar vinos o quiere una elección segura?",
          "Define tu rango de precios objetivo: ¿cuál es el ticket medio que buscas en vino?",
          "Estudia a tu competencia directa: ¿qué ofrecen y dónde puedes diferenciarte?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Selecciona las referencias adecuadas",
        content: "El número de referencias es clave. Demasiadas generan parálisis de elección y aumentan el stock muerto. Muy pocas limitan las oportunidades de venta.\n\nLa regla general es: entre 40 y 80 referencias para un restaurante medio, entre 100 y 200 para restaurantes con foco en vino.",
        tips: [
          "Incluye un equilibrio entre blancos, tintos, rosados y espumosos",
          "No olvides opciones accesibles: el vino de entrada es el que más se vende",
          "Añade 2-3 referencias premium que eleven el ticket medio",
          "Incorpora vinos locales o de denominación que conecten con tu identidad",
          "Rota las referencias que no se venden en 60-90 días",
        ],
        icon: "list",
      },
      {
        heading: "3. Estructura la carta por secciones",
        content: "Una carta bien estructurada guía al cliente hacia la decisión de compra. No se trata de listar vinos, sino de crear un recorrido lógico.\n\nLas estructuras más efectivas agrupan por estilo (fresco, afrutado, estructurado) o por momento de consumo, no solo por región o uva.",
        tips: [
          "Agrupa por estilo sensorial: fresco, afrutado, intenso, elegante",
          "Crea categorías claras con títulos descriptivos, no técnicos",
          "Coloca los vinos con mejor margen en las posiciones de mayor visibilidad",
          "Usa la técnica del ʻanclajeʼ: sitúa un vino premium junto a los de margen objetivo",
        ],
        icon: "check",
      },
      {
        heading: "4. Fija los precios correctamente",
        content: "El pricing del vino es uno de los factores que más impactan en la rentabilidad del restaurante. Un error común es aplicar un multiplicador fijo (x2, x3) sin considerar la elasticidad del precio.\n\nLos vinos de entrada deben tener un margen porcentual menor pero un volumen de venta alto. Los vinos premium pueden tener un margen bruto mayor con menor rotación.",
        tips: [
          "No uses un multiplicador fijo: adapta el margen por franja de precio",
          "Los vinos de 15-25€ en carta son los más vendidos: optimiza esa franja",
          "El vino más barato de la carta marca la percepción de precio: cuídalo",
          "Revisa los precios cada trimestre en función de las ventas reales",
        ],
        icon: "alert",
      },
      {
        heading: "5. Diseña la presentación visual",
        content: "La forma en que presentas la carta influye directamente en la decisión del cliente. Una carta clara, limpia y bien diseñada genera confianza y facilita la elección.\n\nLas cartas digitales permiten añadir notas de cata, maridajes y filtros que una carta en papel no puede ofrecer.",
        tips: [
          "Usa tipografías legibles y un diseño limpio sin saturar de información",
          "Incluye notas de cata breves que ayuden al cliente a elegir",
          "Añade sugerencias de maridaje junto a cada vino o sección",
          "Considera una carta digital que permita filtros y recomendaciones inteligentes",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Incluye vino por copa",
        content: "El vino por copa es una de las herramientas más potentes para aumentar las ventas de vino. Reduce la barrera de entrada, permite explorar y genera márgenes superiores.\n\nLa selección de vino por copa debe rotar y estar alineada con la temporada y el menú.",
        tips: [
          "Ofrece entre 6 y 12 referencias por copa como punto de partida",
          "Incluye al menos un espumoso, un blanco, un rosado y dos tintos",
          "Fija el precio de la copa al equivalente del 30-40% de la botella",
          "Rota las referencias por copa cada 2-4 semanas para generar novedad",
        ],
        icon: "check",
      },
      {
        heading: "7. Actualiza y optimiza periódicamente",
        content: "Una carta de vinos no es estática. Debe evolucionar con los datos de venta, la temporada y la oferta gastronómica.\n\nLos restaurantes que revisan su carta trimestralmente venden entre un 15% y un 25% más de vino que los que la mantienen fija durante todo el año.",
        tips: [
          "Revisa las ventas por referencia cada mes y elimina los vinos que no rotan",
          "Ajusta la carta a la temporada: blancos frescos en verano, tintos potentes en invierno",
          "Analiza qué secciones de la carta generan más conversión",
          "Usa herramientas como Winerim para obtener datos reales de rendimiento",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "¿Cuántos vinos debe tener una carta de restaurante?", a: "Depende del tipo de restaurante. Un restaurante medio debería tener entre 40 y 80 referencias. Los restaurantes con foco en vino pueden llegar a 150-200. Lo importante es que cada referencia justifique su presencia con datos de venta." },
      { q: "¿Es mejor organizar la carta por región o por estilo?", a: "Organizar por estilo sensorial (fresco, afrutado, intenso) es más efectivo para la mayoría de restaurantes. Facilita la elección del cliente y permite recomendar mejor. La organización por región funciona mejor en restaurantes especializados." },
      { q: "¿Qué margen debe tener el vino en un restaurante?", a: "No hay un margen único. Los vinos de entrada (coste < 5€) suelen venderse con un multiplicador x3-x4. Los vinos de gama media (5-15€ coste) con x2.5-x3. Los premium (>15€ coste) con x2-x2.5. Lo importante es optimizar el margen bruto total, no el porcentaje individual." },
      { q: "¿Cómo sé si mi carta de vinos funciona bien?", a: "Mide tres indicadores clave: porcentaje de mesas que piden vino, ticket medio en vino por mesa, y rotación de referencias. Si más del 30% de las referencias no se venden en 90 días, tu carta necesita optimización." },
      { q: "¿Qué ventajas tiene una carta de vinos digital?", a: "Una carta digital permite filtros inteligentes, recomendaciones personalizadas, maridajes automáticos, actualización en tiempo real y análisis de datos de consumo. Todo esto se traduce en más ventas y mejor experiencia." },
    ],
    relatedTools: [
      { label: "Calculadora de margen de vino", url: "/calculadora-margen-vino" },
      { label: "Analizador de carta de vinos", url: "/analisis-carta" },
    ],
    relatedGuides: [
      { label: "Cómo vender más vino en un restaurante", url: "/como-vender-mas-vino-en-un-restaurante" },
      { label: "Cómo fijar el precio del vino", url: "/precio-vino-restaurante" },
      { label: "Vino por copa en restaurante", url: "/vino-por-copa-restaurante" },
      { label: "Carta papel vs carta digital", url: "/carta-papel-vs-digital" },
    ],
  },
  en: {
    slug: "how-to-create-a-wine-list",
    metaTitle: "How to Create a Profitable Wine List | Complete Guide",
    metaDescription: "Learn how to design a wine list that sells: structure, reference selection, pricing and presentation step by step for restaurants.",
    heroTitle: "How to Create a Wine List",
    heroSubtitle: "Step-by-step guide to designing a profitable, well-structured wine list built to sell more at your restaurant.",
    heroBadge: "Practical guide",
    breadcrumbParent: { label: "Guides", href: "/en/guides" },
    ctaPrimaryText: "Request demo",
    ctaPrimaryUrl: "/en/demo",
    ctaSecondaryText: "Analyze your list",
    ctaSecondaryUrl: "/en/wine-list-analysis",
    ctaFinalTitle: "Design a wine list that sells",
    ctaFinalDescription: "Winerim helps you create, optimize and manage your wine list with data, AI and tools built for restaurants.",
    tableOfContents: [
      "Define your restaurant's profile",
      "Select the right references",
      "Structure the list by sections",
      "Set prices correctly",
      "Design the visual presentation",
      "Include wine by the glass",
      "Update and optimize regularly",
    ],
    sections: [
      {
        heading: "1. Define your restaurant's profile",
        content: "Before choosing a single wine, you need to understand what kind of experience your restaurant offers. The wine list must align with your cuisine, clientele and average ticket.\n\nA steakhouse doesn't need the same list as a Japanese restaurant. A wine bar has different needs than a hotel restaurant.",
        tips: [
          "Analyze your food menu: what type of dishes predominate?",
          "Identify your typical guest: are they looking to explore or want a safe choice?",
          "Define your target price range: what average wine ticket are you aiming for?",
          "Study your direct competitors: what do they offer and where can you differentiate?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Select the right references",
        content: "The number of references is key. Too many create choice paralysis and increase dead stock. Too few limit sales opportunities.\n\nThe general rule: 40 to 80 references for an average restaurant, 100 to 200 for wine-focused venues.",
        tips: [
          "Include a balance of whites, reds, rosés and sparkling wines",
          "Don't forget accessible options: entry-level wine sells the most",
          "Add 2-3 premium references to raise the average ticket",
          "Include local or appellation wines that connect with your identity",
          "Rotate references that haven't sold in 60-90 days",
        ],
        icon: "list",
      },
      {
        heading: "3. Structure the list by sections",
        content: "A well-structured list guides the guest toward a purchase decision. It's not about listing wines, but creating a logical journey.\n\nThe most effective structures group by style (fresh, fruity, structured) or by consumption moment, not just by region or grape.",
        tips: [
          "Group by sensory style: fresh, fruity, intense, elegant",
          "Create clear categories with descriptive, non-technical titles",
          "Place highest-margin wines in the most visible positions",
          "Use the anchoring technique: place a premium wine next to your target-margin options",
        ],
        icon: "check",
      },
      {
        heading: "4. Set prices correctly",
        content: "Wine pricing is one of the factors that most impact restaurant profitability. A common mistake is applying a fixed multiplier (x2, x3) without considering price elasticity.\n\nEntry wines should have a lower percentage margin but high sales volume. Premium wines can have a higher gross margin with lower turnover.",
        tips: [
          "Don't use a fixed multiplier: adapt the margin by price range",
          "Wines priced €15-25 on the list are the best sellers: optimize that range",
          "The cheapest wine on the list sets the price perception: choose carefully",
          "Review prices quarterly based on actual sales data",
        ],
        icon: "alert",
      },
      {
        heading: "5. Design the visual presentation",
        content: "How you present the list directly influences the guest's decision. A clear, clean, well-designed list builds trust and makes choosing easier.\n\nDigital lists allow tasting notes, pairings and filters that a paper list can't offer.",
        tips: [
          "Use legible fonts and a clean design without information overload",
          "Include brief tasting notes to help guests choose",
          "Add pairing suggestions next to each wine or section",
          "Consider a digital list with smart filters and recommendations",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Include wine by the glass",
        content: "Wine by the glass is one of the most powerful tools for boosting wine sales. It lowers the barrier to entry, encourages exploration and generates higher margins.\n\nThe by-the-glass selection should rotate and align with the season and menu.",
        tips: [
          "Offer 6 to 12 by-the-glass references as a starting point",
          "Include at least one sparkling, one white, one rosé and two reds",
          "Set the glass price at 30-40% of the bottle price",
          "Rotate by-the-glass references every 2-4 weeks to create novelty",
        ],
        icon: "check",
      },
      {
        heading: "7. Update and optimize regularly",
        content: "A wine list is not static. It must evolve with sales data, seasonality and the food offer.\n\nRestaurants that review their list quarterly sell 15-25% more wine than those that keep it fixed all year.",
        tips: [
          "Review sales by reference every month and remove wines that don't rotate",
          "Adjust the list to the season: fresh whites in summer, bold reds in winter",
          "Analyze which sections of the list generate the most conversions",
          "Use tools like Winerim to get real performance data",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "How many wines should a restaurant list have?", a: "It depends on the type of restaurant. An average restaurant should have 40-80 references. Wine-focused venues can reach 150-200. The key is that each reference justifies its presence with sales data." },
      { q: "Is it better to organize by region or by style?", a: "Organizing by sensory style (fresh, fruity, intense) is more effective for most restaurants. It facilitates guest choice and enables better recommendations. Regional organization works better in specialized venues." },
      { q: "What margin should wine have in a restaurant?", a: "There's no single margin. Entry wines (cost < €5) typically sell at x3-x4 markup. Mid-range (€5-15 cost) at x2.5-x3. Premium (>€15 cost) at x2-x2.5. The key is optimizing total gross margin, not individual percentages." },
      { q: "How do I know if my wine list is performing well?", a: "Measure three key indicators: percentage of tables ordering wine, average wine ticket per table, and reference rotation. If more than 30% of references don't sell in 90 days, your list needs optimization." },
      { q: "What are the advantages of a digital wine list?", a: "A digital list enables smart filters, personalized recommendations, automatic pairings, real-time updates and consumption data analysis. All of this translates into more sales and a better experience." },
    ],
    relatedTools: [
      { label: "Wine margin calculator", url: "/en/wine-margin-calculator" },
      { label: "Wine list analyzer", url: "/en/wine-list-analysis" },
    ],
    relatedGuides: [
      { label: "How to sell more wine in restaurants", url: "/en/how-to-sell-more-wine-in-restaurants" },
      { label: "How to price wine at a restaurant", url: "/en/wine-pricing-restaurant" },
      { label: "Wine by the glass at restaurants", url: "/en/wine-by-glass-restaurant" },
      { label: "Paper vs digital wine list", url: "/en/paper-vs-digital-wine-list" },
    ],
  },
  it: {
    slug: "come-creare-una-carta-dei-vini",
    metaTitle: "Come Creare una Carta dei Vini Redditizia | Guida Completa",
    metaDescription: "Scopri come progettare una carta dei vini che venda: struttura, selezione referenze, pricing e presentazione passo dopo passo per ristoranti.",
    heroTitle: "Come Creare una Carta dei Vini",
    heroSubtitle: "Guida passo dopo passo per progettare una carta dei vini redditizia, ben strutturata e pensata per vendere di più nel tuo ristorante.",
    heroBadge: "Guida pratica",
    breadcrumbParent: { label: "Guide", href: "/it/guide" },
    ctaPrimaryText: "Richiedi demo",
    ctaPrimaryUrl: "/it/demo",
    ctaSecondaryText: "Analizza la tua carta",
    ctaSecondaryUrl: "/it/analisi-carta",
    ctaFinalTitle: "Progetta una carta dei vini che venda",
    ctaFinalDescription: "Winerim ti aiuta a creare, ottimizzare e gestire la tua carta dei vini con dati, IA e strumenti pensati per la ristorazione.",
    tableOfContents: [
      "Definisci il profilo del tuo ristorante",
      "Seleziona le referenze giuste",
      "Struttura la carta per sezioni",
      "Fissa i prezzi correttamente",
      "Progetta la presentazione visiva",
      "Includi il vino al calice",
      "Aggiorna e ottimizza periodicamente",
    ],
    sections: [
      {
        heading: "1. Definisci il profilo del tuo ristorante",
        content: "Prima di scegliere un solo vino, devi capire che tipo di esperienza offre il tuo ristorante. La carta dei vini deve essere allineata con la tua cucina, il tuo pubblico e il tuo scontrino medio.\n\nUna steakhouse non ha bisogno della stessa carta di un ristorante giapponese. Un wine bar ha esigenze diverse da un hotel con ristorante.",
        tips: [
          "Analizza il tuo menu gastronomico: quale tipo di piatti predomina?",
          "Identifica il tuo cliente tipo: cerca di esplorare vini o vuole una scelta sicura?",
          "Definisci la tua fascia di prezzo obiettivo: quale scontrino medio punti per il vino?",
          "Studia la concorrenza diretta: cosa offrono e dove puoi differenziarti?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Seleziona le referenze giuste",
        content: "Il numero di referenze è fondamentale. Troppe generano paralisi della scelta e aumentano lo stock morto. Troppo poche limitano le opportunità di vendita.\n\nLa regola generale: tra 40 e 80 referenze per un ristorante medio, tra 100 e 200 per ristoranti focalizzati sul vino.",
        tips: [
          "Includi un equilibrio tra bianchi, rossi, rosati e spumanti",
          "Non dimenticare le opzioni accessibili: il vino d'ingresso è quello che si vende di più",
          "Aggiungi 2-3 referenze premium per alzare lo scontrino medio",
          "Inserisci vini locali o di denominazione che si colleghino alla tua identità",
          "Ruota le referenze che non si vendono in 60-90 giorni",
        ],
        icon: "list",
      },
      {
        heading: "3. Struttura la carta per sezioni",
        content: "Una carta ben strutturata guida il cliente verso la decisione d'acquisto. Non si tratta di elencare vini, ma di creare un percorso logico.\n\nLe strutture più efficaci raggruppano per stile (fresco, fruttato, strutturato) o per momento di consumo, non solo per regione o vitigno.",
        tips: [
          "Raggruppa per stile sensoriale: fresco, fruttato, intenso, elegante",
          "Crea categorie chiare con titoli descrittivi, non tecnici",
          "Posiziona i vini con margine migliore nelle posizioni di maggiore visibilità",
          "Usa la tecnica dell'ancoraggio: posiziona un vino premium accanto a quelli a margine obiettivo",
        ],
        icon: "check",
      },
      {
        heading: "4. Fissa i prezzi correttamente",
        content: "Il pricing del vino è uno dei fattori che più impattano sulla redditività del ristorante. Un errore comune è applicare un moltiplicatore fisso (x2, x3) senza considerare l'elasticità del prezzo.\n\nI vini d'ingresso devono avere un margine percentuale inferiore ma un volume di vendita alto. I vini premium possono avere un margine lordo maggiore con minore rotazione.",
        tips: [
          "Non usare un moltiplicatore fisso: adatta il margine per fascia di prezzo",
          "I vini tra 15-25€ in carta sono i più venduti: ottimizza quella fascia",
          "Il vino più economico in carta segna la percezione del prezzo: curalo",
          "Rivedi i prezzi ogni trimestre in base alle vendite reali",
        ],
        icon: "alert",
      },
      {
        heading: "5. Progetta la presentazione visiva",
        content: "Il modo in cui presenti la carta influenza direttamente la decisione del cliente. Una carta chiara, pulita e ben progettata genera fiducia e facilita la scelta.\n\nLe carte digitali permettono di aggiungere note di degustazione, abbinamenti e filtri che una carta cartacea non può offrire.",
        tips: [
          "Usa font leggibili e un design pulito senza sovraccaricare di informazioni",
          "Includi brevi note di degustazione per aiutare il cliente a scegliere",
          "Aggiungi suggerimenti di abbinamento accanto a ogni vino o sezione",
          "Considera una carta digitale con filtri e raccomandazioni intelligenti",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Includi il vino al calice",
        content: "Il vino al calice è uno degli strumenti più potenti per aumentare le vendite di vino. Riduce la barriera d'ingresso, permette di esplorare e genera margini superiori.\n\nLa selezione al calice deve ruotare ed essere allineata con la stagione e il menu.",
        tips: [
          "Offri tra 6 e 12 referenze al calice come punto di partenza",
          "Includi almeno uno spumante, un bianco, un rosato e due rossi",
          "Fissa il prezzo del calice al 30-40% equivalente della bottiglia",
          "Ruota le referenze al calice ogni 2-4 settimane per creare novità",
        ],
        icon: "check",
      },
      {
        heading: "7. Aggiorna e ottimizza periodicamente",
        content: "Una carta dei vini non è statica. Deve evolvere con i dati di vendita, la stagionalità e l'offerta gastronomica.\n\nI ristoranti che revisionano la carta trimestralmente vendono il 15-25% in più di vino rispetto a quelli che la mantengono fissa tutto l'anno.",
        tips: [
          "Rivedi le vendite per referenza ogni mese ed elimina i vini che non ruotano",
          "Adatta la carta alla stagione: bianchi freschi in estate, rossi potenti in inverno",
          "Analizza quali sezioni della carta generano più conversione",
          "Usa strumenti come Winerim per ottenere dati reali di performance",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Quanti vini deve avere una carta di un ristorante?", a: "Dipende dal tipo di ristorante. Un ristorante medio dovrebbe avere tra 40 e 80 referenze. I ristoranti focalizzati sul vino possono arrivare a 150-200. L'importante è che ogni referenza giustifichi la sua presenza con dati di vendita." },
      { q: "È meglio organizzare per regione o per stile?", a: "Organizzare per stile sensoriale (fresco, fruttato, intenso) è più efficace per la maggior parte dei ristoranti. Facilita la scelta del cliente e permette di consigliare meglio. L'organizzazione per regione funziona meglio nei ristoranti specializzati." },
      { q: "Quale margine deve avere il vino in un ristorante?", a: "Non esiste un margine unico. I vini d'ingresso (costo < 5€) si vendono con moltiplicatore x3-x4. I vini di gamma media (5-15€ costo) con x2,5-x3. I premium (>15€ costo) con x2-x2,5. L'importante è ottimizzare il margine lordo totale." },
      { q: "Come faccio a sapere se la mia carta dei vini funziona bene?", a: "Misura tre indicatori chiave: percentuale di tavoli che ordinano vino, scontrino medio vino per tavolo e rotazione delle referenze. Se più del 30% delle referenze non si vende in 90 giorni, la tua carta ha bisogno di ottimizzazione." },
      { q: "Quali vantaggi ha una carta dei vini digitale?", a: "Una carta digitale permette filtri intelligenti, raccomandazioni personalizzate, abbinamenti automatici, aggiornamento in tempo reale e analisi dei dati di consumo. Tutto questo si traduce in più vendite e migliore esperienza." },
    ],
    relatedTools: [
      { label: "Calcolatrice margini vino", url: "/it/calcolatrice-margini-vino" },
      { label: "Analizzatore carta dei vini", url: "/it/analisi-carta" },
    ],
    relatedGuides: [
      { label: "Come vendere più vino al ristorante", url: "/it/come-vendere-piu-vino-ristorante" },
      { label: "Come fissare il prezzo del vino", url: "/it/prezzo-vino-ristorante" },
      { label: "Vino al calice al ristorante", url: "/it/vino-al-calice-ristorante" },
      { label: "Carta cartacea vs digitale", url: "/it/carta-cartacea-vs-digitale" },
    ],
  },
  fr: {
    slug: "comment-creer-une-carte-des-vins",
    metaTitle: "Comment Créer une Carte des Vins Rentable | Guide Complet",
    metaDescription: "Apprenez à concevoir une carte des vins qui vend : structure, sélection de références, pricing et présentation étape par étape pour restaurants.",
    heroTitle: "Comment Créer une Carte des Vins",
    heroSubtitle: "Guide étape par étape pour concevoir une carte des vins rentable, bien structurée et conçue pour vendre plus dans votre restaurant.",
    heroBadge: "Guide pratique",
    breadcrumbParent: { label: "Guides", href: "/fr/guides" },
    ctaPrimaryText: "Demander une démo",
    ctaPrimaryUrl: "/fr/demo",
    ctaSecondaryText: "Analyser votre carte",
    ctaSecondaryUrl: "/fr/analyse-carte",
    ctaFinalTitle: "Concevez une carte des vins qui vend",
    ctaFinalDescription: "Winerim vous aide à créer, optimiser et gérer votre carte des vins avec des données, l'IA et des outils conçus pour la restauration.",
    tableOfContents: [
      "Définissez le profil de votre restaurant",
      "Sélectionnez les bonnes références",
      "Structurez la carte par sections",
      "Fixez les prix correctement",
      "Concevez la présentation visuelle",
      "Incluez le vin au verre",
      "Mettez à jour et optimisez régulièrement",
    ],
    sections: [
      {
        heading: "1. Définissez le profil de votre restaurant",
        content: "Avant de choisir un seul vin, vous devez comprendre quel type d'expérience votre restaurant propose. La carte des vins doit être alignée avec votre cuisine, votre clientèle et votre ticket moyen.\n\nUn steakhouse n'a pas besoin de la même carte qu'un restaurant japonais. Un bar à vin n'a pas les mêmes besoins qu'un hôtel-restaurant.",
        tips: [
          "Analysez votre menu gastronomique : quel type de plats prédomine ?",
          "Identifiez votre client type : cherche-t-il à explorer ou veut-il un choix sûr ?",
          "Définissez votre fourchette de prix cible : quel ticket moyen vin visez-vous ?",
          "Étudiez vos concurrents directs : que proposent-ils et où pouvez-vous vous différencier ?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Sélectionnez les bonnes références",
        content: "Le nombre de références est clé. Trop de références créent la paralysie du choix et augmentent le stock mort. Trop peu limitent les opportunités de vente.\n\nLa règle générale : entre 40 et 80 références pour un restaurant moyen, entre 100 et 200 pour les établissements axés sur le vin.",
        tips: [
          "Incluez un équilibre entre blancs, rouges, rosés et effervescents",
          "N'oubliez pas les options accessibles : le vin d'entrée est celui qui se vend le plus",
          "Ajoutez 2-3 références premium pour augmenter le ticket moyen",
          "Intégrez des vins locaux ou d'appellation qui résonnent avec votre identité",
          "Faites tourner les références qui ne se vendent pas en 60-90 jours",
        ],
        icon: "list",
      },
      {
        heading: "3. Structurez la carte par sections",
        content: "Une carte bien structurée guide le client vers la décision d'achat. Il ne s'agit pas de lister des vins, mais de créer un parcours logique.\n\nLes structures les plus efficaces regroupent par style (frais, fruité, structuré) ou par moment de consommation, pas uniquement par région ou cépage.",
        tips: [
          "Regroupez par style sensoriel : frais, fruité, intense, élégant",
          "Créez des catégories claires avec des titres descriptifs, pas techniques",
          "Placez les vins à meilleure marge aux positions les plus visibles",
          "Utilisez la technique d'ancrage : placez un vin premium à côté de vos options à marge cible",
        ],
        icon: "check",
      },
      {
        heading: "4. Fixez les prix correctement",
        content: "Le pricing du vin est l'un des facteurs qui impactent le plus la rentabilité du restaurant. Une erreur courante est d'appliquer un multiplicateur fixe (x2, x3) sans considérer l'élasticité des prix.\n\nLes vins d'entrée doivent avoir une marge en pourcentage plus faible mais un volume de vente élevé. Les vins premium peuvent avoir une marge brute plus élevée avec une rotation plus faible.",
        tips: [
          "N'utilisez pas un multiplicateur fixe : adaptez la marge par tranche de prix",
          "Les vins à 15-25€ en carte sont les plus vendus : optimisez cette tranche",
          "Le vin le moins cher de la carte fixe la perception du prix : soignez-le",
          "Revoyez les prix chaque trimestre en fonction des ventes réelles",
        ],
        icon: "alert",
      },
      {
        heading: "5. Concevez la présentation visuelle",
        content: "La façon dont vous présentez la carte influence directement la décision du client. Une carte claire, épurée et bien conçue inspire confiance et facilite le choix.\n\nLes cartes digitales permettent d'ajouter des notes de dégustation, des accords et des filtres qu'une carte papier ne peut pas offrir.",
        tips: [
          "Utilisez des typographies lisibles et un design épuré sans surcharger d'informations",
          "Incluez de brèves notes de dégustation pour aider le client à choisir",
          "Ajoutez des suggestions d'accord à côté de chaque vin ou section",
          "Envisagez une carte digitale avec filtres et recommandations intelligentes",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Incluez le vin au verre",
        content: "Le vin au verre est l'un des outils les plus puissants pour augmenter les ventes de vin. Il réduit la barrière à l'entrée, permet d'explorer et génère des marges supérieures.\n\nLa sélection au verre doit tourner et être alignée avec la saison et le menu.",
        tips: [
          "Proposez 6 à 12 références au verre comme point de départ",
          "Incluez au moins un effervescent, un blanc, un rosé et deux rouges",
          "Fixez le prix du verre à l'équivalent de 30-40% de la bouteille",
          "Faites tourner les références au verre toutes les 2-4 semaines pour créer de la nouveauté",
        ],
        icon: "check",
      },
      {
        heading: "7. Mettez à jour et optimisez régulièrement",
        content: "Une carte des vins n'est pas statique. Elle doit évoluer avec les données de vente, la saisonnalité et l'offre gastronomique.\n\nLes restaurants qui révisent leur carte trimestriellement vendent 15-25% de vin en plus par rapport à ceux qui la maintiennent fixe toute l'année.",
        tips: [
          "Passez en revue les ventes par référence chaque mois et éliminez les vins qui ne tournent pas",
          "Adaptez la carte à la saison : blancs frais en été, rouges puissants en hiver",
          "Analysez quelles sections de la carte génèrent le plus de conversions",
          "Utilisez des outils comme Winerim pour obtenir des données de performance réelles",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Combien de vins doit avoir une carte de restaurant ?", a: "Cela dépend du type de restaurant. Un restaurant moyen devrait avoir 40 à 80 références. Les établissements axés sur le vin peuvent aller jusqu'à 150-200. L'essentiel est que chaque référence justifie sa présence par des données de vente." },
      { q: "Vaut-il mieux organiser par région ou par style ?", a: "Organiser par style sensoriel (frais, fruité, intense) est plus efficace pour la plupart des restaurants. Cela facilite le choix du client et permet de mieux conseiller. L'organisation par région fonctionne mieux dans les établissements spécialisés." },
      { q: "Quelle marge doit avoir le vin dans un restaurant ?", a: "Il n'y a pas de marge unique. Les vins d'entrée (coût < 5€) se vendent avec un multiplicateur x3-x4. Les vins de gamme moyenne (5-15€ coût) en x2,5-x3. Les premium (>15€ coût) en x2-x2,5. L'essentiel est d'optimiser la marge brute totale." },
      { q: "Comment savoir si ma carte des vins fonctionne bien ?", a: "Mesurez trois indicateurs clés : pourcentage de tables qui commandent du vin, ticket moyen vin par table et rotation des références. Si plus de 30% des références ne se vendent pas en 90 jours, votre carte a besoin d'optimisation." },
      { q: "Quels sont les avantages d'une carte des vins digitale ?", a: "Une carte digitale permet des filtres intelligents, des recommandations personnalisées, des accords automatiques, une mise à jour en temps réel et une analyse des données de consommation. Tout cela se traduit par plus de ventes et une meilleure expérience." },
    ],
    relatedTools: [
      { label: "Calculateur de marge vin", url: "/fr/calculateur-marge-vin" },
      { label: "Analyseur de carte des vins", url: "/fr/analyse-carte" },
    ],
    relatedGuides: [
      { label: "Comment vendre plus de vin au restaurant", url: "/fr/comment-vendre-plus-vin-restaurant" },
      { label: "Comment fixer le prix du vin", url: "/fr/prix-vin-restaurant" },
      { label: "Vin au verre au restaurant", url: "/fr/vin-au-verre-restaurant" },
      { label: "Carte papier vs digitale", url: "/fr/carte-papier-vs-digitale" },
    ],
  },
  de: {
    slug: "wie-weinkarte-erstellen",
    metaTitle: "Wie erstellt man eine rentable Weinkarte | Vollständiger Leitfaden",
    metaDescription: "Lernen Sie, eine verkaufsstarke Weinkarte zu gestalten: Struktur, Auswahl der Positionen, Pricing und Präsentation Schritt für Schritt für Restaurants.",
    heroTitle: "Wie man eine Weinkarte erstellt",
    heroSubtitle: "Schritt-für-Schritt-Leitfaden zur Gestaltung einer rentablen, gut strukturierten Weinkarte, die in Ihrem Restaurant mehr verkauft.",
    heroBadge: "Praktischer Leitfaden",
    breadcrumbParent: { label: "Leitfäden", href: "/de/leitfaeden" },
    ctaPrimaryText: "Demo anfordern",
    ctaPrimaryUrl: "/de/demo",
    ctaSecondaryText: "Weinkarte analysieren",
    ctaSecondaryUrl: "/de/weinkarten-analyse",
    ctaFinalTitle: "Gestalten Sie eine Weinkarte, die verkauft",
    ctaFinalDescription: "Winerim hilft Ihnen, Ihre Weinkarte mit Daten, KI und für die Gastronomie konzipierten Werkzeugen zu erstellen, zu optimieren und zu verwalten.",
    tableOfContents: [
      "Definieren Sie das Profil Ihres Restaurants",
      "Wählen Sie die passenden Positionen aus",
      "Strukturieren Sie die Karte in Sektionen",
      "Legen Sie die Preise richtig fest",
      "Gestalten Sie die visuelle Präsentation",
      "Nehmen Sie Glaswein auf",
      "Aktualisieren und optimieren Sie regelmäßig",
    ],
    sections: [
      {
        heading: "1. Definieren Sie das Profil Ihres Restaurants",
        content: "Bevor Sie auch nur einen einzigen Wein auswählen, müssen Sie verstehen, welche Art von Erlebnis Ihr Restaurant bietet. Die Weinkarte muss zu Ihrer Küche, Ihrem Publikum und Ihrem Durchschnittsbon passen.\n\nEin Steakhouse braucht nicht dieselbe Karte wie ein japanisches Restaurant. Eine Weinbar hat andere Bedürfnisse als ein Hotel mit Restaurant.",
        tips: [
          "Analysieren Sie Ihr gastronomisches Menü: Welche Gerichte dominieren?",
          "Identifizieren Sie Ihren typischen Gast: Will er Weine erkunden oder sucht er eine sichere Wahl?",
          "Legen Sie Ihren Zielpreisbereich fest: Welchen Wein-Durchschnittsbon peilen Sie an?",
          "Studieren Sie Ihre direkte Konkurrenz: Was bieten sie und wo können Sie sich abheben?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Wählen Sie die passenden Positionen aus",
        content: "Die Anzahl der Positionen ist entscheidend. Zu viele erzeugen Entscheidungslähmung und erhöhen den Totbestand. Zu wenige begrenzen die Verkaufschancen.\n\nDie allgemeine Regel: zwischen 40 und 80 Positionen für ein mittleres Restaurant, zwischen 100 und 200 für weinorientierte Betriebe.",
        tips: [
          "Sorgen Sie für ein Gleichgewicht zwischen Weißweinen, Rotweinen, Rosés und Schaumweinen",
          "Vergessen Sie zugängliche Optionen nicht: der Einstiegswein verkauft sich am meisten",
          "Nehmen Sie 2–3 Premium-Positionen auf, um den Durchschnittsbon zu erhöhen",
          "Integrieren Sie lokale oder Herkunftsweine, die zu Ihrer Identität passen",
          "Rotieren Sie Positionen, die sich in 60–90 Tagen nicht verkaufen",
        ],
        icon: "list",
      },
      {
        heading: "3. Strukturieren Sie die Karte in Sektionen",
        content: "Eine gut strukturierte Karte führt den Gast zur Kaufentscheidung. Es geht nicht darum, Weine aufzulisten, sondern einen logischen Pfad zu schaffen.\n\nDie effektivsten Strukturen gruppieren nach Stil (frisch, fruchtig, strukturiert) oder nach Konsummoment, nicht nur nach Region oder Rebsorte.",
        tips: [
          "Gruppieren Sie nach sensorischem Stil: frisch, fruchtig, intensiv, elegant",
          "Schaffen Sie klare Kategorien mit beschreibenden, nicht technischen Titeln",
          "Platzieren Sie Weine mit besseren Margen an den sichtbarsten Positionen",
          "Nutzen Sie die Verankerungstechnik: platzieren Sie einen Premiumwein neben Weinen mit Zielmarge",
        ],
        icon: "check",
      },
      {
        heading: "4. Legen Sie die Preise richtig fest",
        content: "Das Pricing des Weins ist einer der Faktoren mit dem größten Einfluss auf die Rentabilität des Restaurants. Ein häufiger Fehler ist die Anwendung eines festen Multiplikators (x2, x3), ohne die Preiselastizität zu berücksichtigen.\n\nEinstiegsweine sollten eine niedrigere prozentuale Marge, aber ein hohes Verkaufsvolumen haben. Premiumweine können eine höhere Bruttomarge bei geringerer Rotation haben.",
        tips: [
          "Verwenden Sie keinen festen Multiplikator: passen Sie die Marge nach Preisspanne an",
          "Weine mit 15–25 € auf der Karte sind die meistverkauften: optimieren Sie diese Spanne",
          "Der günstigste Wein der Karte prägt die Preiswahrnehmung: pflegen Sie ihn",
          "Überprüfen Sie die Preise quartalsweise anhand der tatsächlichen Verkäufe",
        ],
        icon: "alert",
      },
      {
        heading: "5. Gestalten Sie die visuelle Präsentation",
        content: "Wie Sie die Karte präsentieren, beeinflusst direkt die Entscheidung des Gastes. Eine klare, aufgeräumte und gut gestaltete Karte schafft Vertrauen und erleichtert die Wahl.\n\nDigitale Weinkarten ermöglichen Verkostungsnotizen, Speisenbegleitung und Filter, die eine Papierkarte nicht bieten kann.",
        tips: [
          "Verwenden Sie lesbare Schriften und ein aufgeräumtes Design ohne Informationsüberlastung",
          "Nehmen Sie kurze Verkostungsnotizen auf, die dem Gast die Wahl erleichtern",
          "Fügen Sie Speisenbegleitungsvorschläge neben jedem Wein oder jeder Sektion hinzu",
          "Erwägen Sie eine digitale Weinkarte mit Filtern und intelligenten Empfehlungen",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Nehmen Sie Glaswein auf",
        content: "Glaswein ist eines der wirksamsten Mittel, um die Weinverkäufe zu steigern. Er senkt die Einstiegshürde, ermöglicht Erkundung und erzeugt höhere Margen.\n\nDie Glaswein-Auswahl sollte rotieren und zur Saison und zum Menü passen.",
        tips: [
          "Bieten Sie 6 bis 12 Glaswein-Positionen als Ausgangspunkt an",
          "Nehmen Sie mindestens einen Schaumwein, einen Weißen, einen Rosé und zwei Rote auf",
          "Setzen Sie den Glaspreis auf 30–40 % des Flaschenpreises fest",
          "Rotieren Sie die Glaswein-Positionen alle 2–4 Wochen, um Neuheit zu erzeugen",
        ],
        icon: "check",
      },
      {
        heading: "7. Aktualisieren und optimieren Sie regelmäßig",
        content: "Eine Weinkarte ist nicht statisch. Sie muss sich mit den Verkaufsdaten, der Saisonalität und dem gastronomischen Angebot entwickeln.\n\nRestaurants, die ihre Karte quartalsweise überprüfen, verkaufen 15–25 % mehr Wein als Restaurants, die sie das ganze Jahr über unverändert lassen.",
        tips: [
          "Überprüfen Sie monatlich die Verkäufe pro Position und entfernen Sie Weine, die nicht rotieren",
          "Passen Sie die Karte an die Saison an: frische Weißweine im Sommer, kräftige Rote im Winter",
          "Analysieren Sie, welche Sektionen der Karte die meisten Conversions generieren",
          "Nutzen Sie Werkzeuge wie Winerim, um echte Performance-Daten zu erhalten",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Wie viele Weine sollte eine Restaurantkarte haben?", a: "Das hängt vom Restauranttyp ab. Ein mittleres Restaurant sollte 40 bis 80 Positionen haben. Weinorientierte Betriebe können 150–200 erreichen. Entscheidend ist, dass jede Position ihre Präsenz mit Verkaufsdaten rechtfertigt." },
      { q: "Ist es besser, nach Region oder nach Stil zu organisieren?", a: "Eine Organisation nach sensorischem Stil (frisch, fruchtig, intensiv) ist für die meisten Restaurants effektiver. Sie erleichtert die Wahl des Gastes und ermöglicht bessere Empfehlungen. Die Organisation nach Region funktioniert besser in spezialisierten Restaurants." },
      { q: "Welche Marge sollte Wein in einem Restaurant haben?", a: "Es gibt keine einheitliche Marge. Einstiegsweine (Einkauf < 5 €) verkaufen sich mit Multiplikator x3–x4. Mittelklasse (5–15 € Einkauf) mit x2,5–x3. Premium (>15 € Einkauf) mit x2–x2,5. Entscheidend ist die Optimierung der gesamten Bruttomarge, nicht einzelner Prozentsätze." },
      { q: "Wie weiß ich, ob meine Weinkarte gut funktioniert?", a: "Messen Sie drei Schlüsselindikatoren: Prozentsatz der Tische, die Wein bestellen, Durchschnittsbon Wein pro Tisch und Rotation der Positionen. Wenn mehr als 30 % der Positionen sich in 90 Tagen nicht verkaufen, braucht Ihre Karte Optimierung." },
      { q: "Welche Vorteile hat eine digitale Weinkarte?", a: "Eine digitale Weinkarte ermöglicht intelligente Filter, personalisierte Empfehlungen, automatische Speisenbegleitung, Echtzeit-Aktualisierung und Konsumdatenanalyse. All das übersetzt sich in mehr Verkäufe und ein besseres Erlebnis." },
    ],
    relatedTools: [
      { label: "Wein-Margen-Rechner", url: "/de/wein-margen-rechner" },
      { label: "Weinkarten-Analyse-Tool", url: "/de/weinkarten-analyse" },
    ],
    relatedGuides: [
      { label: "Wie verkauft man mehr Wein im Restaurant", url: "/de/mehr-wein-verkaufen-restaurant" },
      { label: "Wie man den Weinpreis festlegt", url: "/de/weinpreis-restaurant" },
      { label: "Glaswein im Restaurant", url: "/de/glaswein-restaurant" },
      { label: "Papier vs digitale Weinkarte", url: "/de/papier-vs-digitale-weinkarte" },
    ],
  },
  pt: {
    slug: "como-fazer-uma-carta-de-vinhos",
    metaTitle: "Como Fazer uma Carta de Vinhos Rentável | Guia Completo",
    metaDescription: "Aprenda a desenhar uma carta de vinhos que vende: estrutura, seleção de referências, pricing e apresentação passo a passo para restaurantes.",
    heroTitle: "Como Fazer uma Carta de Vinhos",
    heroSubtitle: "Guia passo a passo para desenhar uma carta de vinhos rentável, bem estruturada e pensada para vender mais no seu restaurante.",
    heroBadge: "Guia prático",
    breadcrumbParent: { label: "Guias", href: "/pt/guias-e-recursos" },
    ctaPrimaryText: "Pedir demo",
    ctaPrimaryUrl: "/pt/demo",
    ctaSecondaryText: "Analisar a sua carta",
    ctaSecondaryUrl: "/pt/analise-carta",
    ctaFinalTitle: "Desenhe uma carta de vinhos que vende",
    ctaFinalDescription: "A Winerim ajuda-o a criar, otimizar e gerir a sua carta de vinhos com dados, IA e ferramentas pensadas para a restauração.",
    tableOfContents: [
      "Defina o perfil do seu restaurante",
      "Selecione as referências adequadas",
      "Estruture a carta por secções",
      "Fixe os preços corretamente",
      "Desenhe a apresentação visual",
      "Inclua vinho a copo",
      "Atualize e otimize periodicamente",
    ],
    sections: [
      {
        heading: "1. Defina o perfil do seu restaurante",
        content: "Antes de escolher um único vinho, precisa de perceber que tipo de experiência o seu restaurante oferece. A carta de vinhos deve estar alinhada com a sua cozinha, o seu público e o seu bilhete médio.\n\nUma steakhouse não precisa da mesma carta que um restaurante japonês. Um wine bar não tem as mesmas necessidades que um hotel com restaurante.",
        tips: [
          "Analise a sua ementa gastronómica: que tipo de pratos predominam?",
          "Identifique o seu cliente-tipo: procura explorar vinhos ou quer uma escolha segura?",
          "Defina a sua faixa de preço-alvo: que bilhete médio de vinho pretende?",
          "Estude a sua concorrência direta: o que oferecem e onde se pode diferenciar?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Selecione as referências adequadas",
        content: "O número de referências é chave. Demasiadas geram paralisia de escolha e aumentam o stock morto. Poucas limitam as oportunidades de venda.\n\nA regra geral: entre 40 e 80 referências para um restaurante médio, entre 100 e 200 para restaurantes com foco no vinho.",
        tips: [
          "Inclua um equilíbrio entre brancos, tintos, rosés e espumantes",
          "Não esqueça opções acessíveis: o vinho de entrada é o que mais se vende",
          "Acrescente 2–3 referências premium que elevem o bilhete médio",
          "Incorpore vinhos locais ou de denominação que liguem à sua identidade",
          "Rode as referências que não se vendem em 60–90 dias",
        ],
        icon: "list",
      },
      {
        heading: "3. Estruture a carta por secções",
        content: "Uma carta bem estruturada guia o cliente para a decisão de compra. Não se trata de listar vinhos, mas de criar um percurso lógico.\n\nAs estruturas mais eficazes agrupam por estilo (fresco, frutado, estruturado) ou por momento de consumo, não apenas por região ou casta.",
        tips: [
          "Agrupe por estilo sensorial: fresco, frutado, intenso, elegante",
          "Crie categorias claras com títulos descritivos, não técnicos",
          "Coloque os vinhos com melhor margem nas posições de maior visibilidade",
          "Use a técnica de ancoragem: coloque um vinho premium ao lado dos de margem-alvo",
        ],
        icon: "check",
      },
      {
        heading: "4. Fixe os preços corretamente",
        content: "O pricing do vinho é um dos fatores que mais impacta a rentabilidade do restaurante. Um erro comum é aplicar um multiplicador fixo (x2, x3) sem considerar a elasticidade do preço.\n\nOs vinhos de entrada devem ter uma margem percentual menor mas um volume de venda alto. Os vinhos premium podem ter uma margem bruta maior com menor rotação.",
        tips: [
          "Não use um multiplicador fixo: adapte a margem por faixa de preço",
          "Os vinhos entre 15–25 € na carta são os mais vendidos: otimize essa faixa",
          "O vinho mais barato da carta marca a perceção de preço: cuide-o",
          "Reveja os preços cada trimestre em função das vendas reais",
        ],
        icon: "alert",
      },
      {
        heading: "5. Desenhe a apresentação visual",
        content: "A forma como apresenta a carta influencia diretamente a decisão do cliente. Uma carta clara, limpa e bem desenhada gera confiança e facilita a escolha.\n\nAs cartas digitais permitem adicionar notas de prova, harmonizações e filtros que uma carta em papel não pode oferecer.",
        tips: [
          "Use tipografias legíveis e um design limpo sem saturar de informação",
          "Inclua notas de prova breves que ajudem o cliente a escolher",
          "Acrescente sugestões de harmonização junto a cada vinho ou secção",
          "Considere uma carta digital que permita filtros e recomendações inteligentes",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Inclua vinho a copo",
        content: "O vinho a copo é uma das ferramentas mais potentes para aumentar as vendas de vinho. Reduz a barreira de entrada, permite explorar e gera margens superiores.\n\nA seleção de vinho a copo deve rodar e estar alinhada com a estação e a ementa.",
        tips: [
          "Ofereça entre 6 e 12 referências a copo como ponto de partida",
          "Inclua pelo menos um espumante, um branco, um rosé e dois tintos",
          "Fixe o preço do copo ao equivalente a 30–40 % da garrafa",
          "Rode as referências a copo a cada 2–4 semanas para gerar novidade",
        ],
        icon: "check",
      },
      {
        heading: "7. Atualize e otimize periodicamente",
        content: "Uma carta de vinhos não é estática. Deve evoluir com os dados de venda, a estação e a oferta gastronómica.\n\nOs restaurantes que revêem a sua carta trimestralmente vendem entre 15 % e 25 % mais vinho do que os que a mantêm fixa durante todo o ano.",
        tips: [
          "Reveja as vendas por referência cada mês e elimine os vinhos que não rodam",
          "Ajuste a carta à estação: brancos frescos no verão, tintos potentes no inverno",
          "Analise que secções da carta geram mais conversão",
          "Use ferramentas como a Winerim para obter dados reais de desempenho",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Quantos vinhos deve ter uma carta de restaurante?", a: "Depende do tipo de restaurante. Um restaurante médio deve ter entre 40 e 80 referências. Os restaurantes com foco no vinho podem chegar a 150–200. O importante é que cada referência justifique a sua presença com dados de venda." },
      { q: "É melhor organizar a carta por região ou por estilo?", a: "Organizar por estilo sensorial (fresco, frutado, intenso) é mais eficaz para a maioria dos restaurantes. Facilita a escolha do cliente e permite recomendar melhor. A organização por região funciona melhor em restaurantes especializados." },
      { q: "Que margem deve ter o vinho num restaurante?", a: "Não há uma margem única. Os vinhos de entrada (custo < 5 €) costumam vender-se com um multiplicador x3–x4. Os de gama média (5–15 € custo) com x2,5–x3. Os premium (>15 € custo) com x2–x2,5. O importante é otimizar a margem bruta total, não a percentagem individual." },
      { q: "Como sei se a minha carta de vinhos funciona bem?", a: "Meça três indicadores-chave: percentagem de mesas que pedem vinho, bilhete médio de vinho por mesa e rotação de referências. Se mais de 30 % das referências não se vendem em 90 dias, a sua carta precisa de otimização." },
      { q: "Que vantagens tem uma carta de vinhos digital?", a: "Uma carta digital permite filtros inteligentes, recomendações personalizadas, harmonizações automáticas, atualização em tempo real e análise de dados de consumo. Tudo isto traduz-se em mais vendas e melhor experiência." },
    ],
    relatedTools: [
      { label: "Calculadora de margem de vinho", url: "/pt/calculadora-margem-vinho" },
      { label: "Analisador de carta de vinhos", url: "/pt/analise-carta" },
    ],
    relatedGuides: [
      { label: "Como vender mais vinho num restaurante", url: "/pt/como-vender-mais-vinho-restaurante" },
      { label: "Como fixar o preço do vinho", url: "/pt/preco-vinho-restaurante" },
      { label: "Vinho a copo no restaurante", url: "/pt/vinho-a-copo-restaurante" },
      { label: "Carta papel vs carta digital", url: "/pt/carta-papel-vs-digital" },
    ],
  },
  de: {
    slug: "wie-weinkarte-erstellen",
    metaTitle: "Wie erstellt man eine rentable Weinkarte | Vollständiger Leitfaden",
    metaDescription: "Lernen Sie, eine verkaufsstarke Weinkarte zu gestalten: Struktur, Auswahl der Positionen, Pricing und Präsentation Schritt für Schritt für Restaurants.",
    heroTitle: "Wie man eine Weinkarte erstellt",
    heroSubtitle: "Schritt-für-Schritt-Leitfaden zur Gestaltung einer rentablen, gut strukturierten Weinkarte, die in Ihrem Restaurant mehr verkauft.",
    heroBadge: "Praktischer Leitfaden",
    breadcrumbParent: { label: "Leitfäden", href: "/de/leitfaeden" },
    ctaPrimaryText: "Demo anfordern",
    ctaPrimaryUrl: "/de/demo",
    ctaSecondaryText: "Weinkarte analysieren",
    ctaSecondaryUrl: "/de/weinkarten-analyse",
    ctaFinalTitle: "Gestalten Sie eine Weinkarte, die verkauft",
    ctaFinalDescription: "Winerim hilft Ihnen, Ihre Weinkarte mit Daten, KI und für die Gastronomie konzipierten Werkzeugen zu erstellen, zu optimieren und zu verwalten.",
    tableOfContents: [
      "Definieren Sie das Profil Ihres Restaurants",
      "Wählen Sie die passenden Positionen aus",
      "Strukturieren Sie die Karte in Sektionen",
      "Legen Sie die Preise richtig fest",
      "Gestalten Sie die visuelle Präsentation",
      "Nehmen Sie Glaswein auf",
      "Aktualisieren und optimieren Sie regelmäßig",
    ],
    sections: [
      {
        heading: "1. Definieren Sie das Profil Ihres Restaurants",
        content: "Bevor Sie auch nur einen einzigen Wein auswählen, müssen Sie verstehen, welche Art von Erlebnis Ihr Restaurant bietet. Die Weinkarte muss zu Ihrer Küche, Ihrem Publikum und Ihrem Durchschnittsbon passen.\n\nEin Steakhouse braucht nicht dieselbe Karte wie ein japanisches Restaurant. Eine Weinbar hat andere Bedürfnisse als ein Hotel mit Restaurant.",
        tips: [
          "Analysieren Sie Ihr gastronomisches Menü: Welche Gerichte dominieren?",
          "Identifizieren Sie Ihren typischen Gast: Will er Weine erkunden oder sucht er eine sichere Wahl?",
          "Legen Sie Ihren Zielpreisbereich fest: Welchen Wein-Durchschnittsbon peilen Sie an?",
          "Studieren Sie Ihre direkte Konkurrenz: Was bieten sie und wo können Sie sich abheben?",
        ],
        icon: "lightbulb",
      },
      {
        heading: "2. Wählen Sie die passenden Positionen aus",
        content: "Die Anzahl der Positionen ist entscheidend. Zu viele erzeugen Entscheidungslähmung und erhöhen den Totbestand. Zu wenige begrenzen die Verkaufschancen.\n\nDie allgemeine Regel: zwischen 40 und 80 Positionen für ein mittleres Restaurant, zwischen 100 und 200 für weinorientierte Betriebe.",
        tips: [
          "Sorgen Sie für ein Gleichgewicht zwischen Weißweinen, Rotweinen, Rosés und Schaumweinen",
          "Vergessen Sie zugängliche Optionen nicht: der Einstiegswein verkauft sich am meisten",
          "Nehmen Sie 2–3 Premium-Positionen auf, um den Durchschnittsbon zu erhöhen",
          "Integrieren Sie lokale oder Herkunftsweine, die zu Ihrer Identität passen",
          "Rotieren Sie Positionen, die sich in 60–90 Tagen nicht verkaufen",
        ],
        icon: "list",
      },
      {
        heading: "3. Strukturieren Sie die Karte in Sektionen",
        content: "Eine gut strukturierte Karte führt den Gast zur Kaufentscheidung. Es geht nicht darum, Weine aufzulisten, sondern einen logischen Pfad zu schaffen.\n\nDie effektivsten Strukturen gruppieren nach Stil (frisch, fruchtig, strukturiert) oder nach Konsummoment, nicht nur nach Region oder Rebsorte.",
        tips: [
          "Gruppieren Sie nach sensorischem Stil: frisch, fruchtig, intensiv, elegant",
          "Schaffen Sie klare Kategorien mit beschreibenden, nicht technischen Titeln",
          "Platzieren Sie Weine mit besseren Margen an den sichtbarsten Positionen",
          "Nutzen Sie die Verankerungstechnik: platzieren Sie einen Premiumwein neben Weinen mit Zielmarge",
        ],
        icon: "check",
      },
      {
        heading: "4. Legen Sie die Preise richtig fest",
        content: "Das Pricing des Weins ist einer der Faktoren mit dem größten Einfluss auf die Rentabilität des Restaurants. Ein häufiger Fehler ist die Anwendung eines festen Multiplikators (x2, x3), ohne die Preiselastizität zu berücksichtigen.\n\nEinstiegsweine sollten eine niedrigere prozentuale Marge, aber ein hohes Verkaufsvolumen haben. Premiumweine können eine höhere Bruttomarge bei geringerer Rotation haben.",
        tips: [
          "Verwenden Sie keinen festen Multiplikator: passen Sie die Marge nach Preisspanne an",
          "Weine mit 15–25 € auf der Karte sind die meistverkauften: optimieren Sie diese Spanne",
          "Der günstigste Wein der Karte prägt die Preiswahrnehmung: pflegen Sie ihn",
          "Überprüfen Sie die Preise quartalsweise anhand der tatsächlichen Verkäufe",
        ],
        icon: "alert",
      },
      {
        heading: "5. Gestalten Sie die visuelle Präsentation",
        content: "Wie Sie die Karte präsentieren, beeinflusst direkt die Entscheidung des Gastes. Eine klare, aufgeräumte und gut gestaltete Karte schafft Vertrauen und erleichtert die Wahl.\n\nDigitale Weinkarten ermöglichen Verkostungsnotizen, Speisenbegleitung und Filter, die eine Papierkarte nicht bieten kann.",
        tips: [
          "Verwenden Sie lesbare Schriften und ein aufgeräumtes Design ohne Informationsüberlastung",
          "Nehmen Sie kurze Verkostungsnotizen auf, die dem Gast die Wahl erleichtern",
          "Fügen Sie Speisenbegleitungsvorschläge neben jedem Wein oder jeder Sektion hinzu",
          "Erwägen Sie eine digitale Weinkarte mit Filtern und intelligenten Empfehlungen",
        ],
        icon: "lightbulb",
      },
      {
        heading: "6. Nehmen Sie Glaswein auf",
        content: "Glaswein ist eines der wirksamsten Mittel, um die Weinverkäufe zu steigern. Er senkt die Einstiegshürde, ermöglicht Erkundung und erzeugt höhere Margen.\n\nDie Glaswein-Auswahl sollte rotieren und zur Saison und zum Menü passen.",
        tips: [
          "Bieten Sie 6 bis 12 Glaswein-Positionen als Ausgangspunkt an",
          "Nehmen Sie mindestens einen Schaumwein, einen Weißen, einen Rosé und zwei Rote auf",
          "Setzen Sie den Glaspreis auf 30–40 % des Flaschenpreises fest",
          "Rotieren Sie die Glaswein-Positionen alle 2–4 Wochen, um Neuheit zu erzeugen",
        ],
        icon: "check",
      },
      {
        heading: "7. Aktualisieren und optimieren Sie regelmäßig",
        content: "Eine Weinkarte ist nicht statisch. Sie muss sich mit den Verkaufsdaten, der Saisonalität und dem gastronomischen Angebot entwickeln.\n\nRestaurants, die ihre Karte quartalsweise überprüfen, verkaufen 15–25 % mehr Wein als Restaurants, die sie das ganze Jahr über unverändert lassen.",
        tips: [
          "Überprüfen Sie monatlich die Verkäufe pro Position und entfernen Sie Weine, die nicht rotieren",
          "Passen Sie die Karte an die Saison an: frische Weißweine im Sommer, kräftige Rote im Winter",
          "Analysieren Sie, welche Sektionen der Karte die meisten Conversions generieren",
          "Nutzen Sie Werkzeuge wie Winerim, um echte Performance-Daten zu erhalten",
        ],
        icon: "check",
      },
    ],
    faqs: [
      { q: "Wie viele Weine sollte eine Restaurantkarte haben?", a: "Das hängt vom Restauranttyp ab. Ein mittleres Restaurant sollte 40 bis 80 Positionen haben. Weinorientierte Betriebe können 150–200 erreichen. Entscheidend ist, dass jede Position ihre Präsenz mit Verkaufsdaten rechtfertigt." },
      { q: "Ist es besser, nach Region oder nach Stil zu organisieren?", a: "Eine Organisation nach sensorischem Stil (frisch, fruchtig, intensiv) ist für die meisten Restaurants effektiver. Sie erleichtert die Wahl des Gastes und ermöglicht bessere Empfehlungen. Die Organisation nach Region funktioniert besser in spezialisierten Restaurants." },
      { q: "Welche Marge sollte Wein in einem Restaurant haben?", a: "Es gibt keine einheitliche Marge. Einstiegsweine (Einkauf < 5 €) verkaufen sich mit Multiplikator x3–x4. Mittelklasse (5–15 € Einkauf) mit x2,5–x3. Premium (>15 € Einkauf) mit x2–x2,5. Entscheidend ist die Optimierung der gesamten Bruttomarge, nicht einzelner Prozentsätze." },
      { q: "Wie weiß ich, ob meine Weinkarte gut funktioniert?", a: "Messen Sie drei Schlüsselindikatoren: Prozentsatz der Tische, die Wein bestellen, Durchschnittsbon Wein pro Tisch und Rotation der Positionen. Wenn mehr als 30 % der Positionen sich in 90 Tagen nicht verkaufen, braucht Ihre Karte Optimierung." },
      { q: "Welche Vorteile hat eine digitale Weinkarte?", a: "Eine digitale Weinkarte ermöglicht intelligente Filter, personalisierte Empfehlungen, automatische Speisenbegleitung, Echtzeit-Aktualisierung und Konsumdatenanalyse. All das übersetzt sich in mehr Verkäufe und ein besseres Erlebnis." },
    ],
    relatedTools: [
      { label: "Wein-Margen-Rechner", url: "/de/wein-margen-rechner" },
      { label: "Weinkarten-Analyse-Tool", url: "/de/weinkarten-analyse" },
    ],
    relatedGuides: [
      { label: "Wie verkauft man mehr Wein im Restaurant", url: "/de/mehr-wein-verkaufen-restaurant" },
      { label: "Wie man den Weinpreis festlegt", url: "/de/weinpreis-restaurant" },
      { label: "Glaswein im Restaurant", url: "/de/glaswein-restaurant" },
      { label: "Papier vs digitale Weinkarte", url: "/de/papier-vs-digitale-weinkarte" },
    ],
  },
};

const ComoHacerCartaVinos = () => {
  const { lang } = useLanguage();
  return <GuideTemplate data={getI18n(i18n, lang)} />;
};

export default ComoHacerCartaVinos;
