import GuideTemplate from "@/components/templates/GuideTemplate";
import type { GuidePageData } from "@/components/templates/GuideTemplate";

const es: GuidePageData = {
  slug: "guias/como-mejorar-la-rotacion-de-vinos-en-un-restaurante",
  metaTitle: "Cómo Mejorar la Rotación de Vinos en un Restaurante | Guía",
  metaDescription: "Guía práctica para mejorar la rotación de vinos en tu restaurante: selección, posicionamiento en carta.",
  heroTitle: "Cómo mejorar la rotación de vinos en un restaurante",
  heroSubtitle: "La rotación de vinos es uno de los indicadores más importantes de rentabilidad. Descubre cómo evitar que tus vinos se queden inmovilizados en bodega.",
  heroBadge: "Guía práctica",
  breadcrumbParent: { label: "Guías", href: "/guias-y-recursos" },
  ctaPrimaryText: "Analizar mi carta", ctaPrimaryUrl: "/analisis-carta",
  ctaSecondaryText: "Solicitar demo", ctaSecondaryUrl: "/demo",
  ctaFinalTitle: "No dejes que tu bodega acumule stock muerto",
  ctaFinalDescription: "Winerim te da los datos para saber qué vinos rotan, cuáles sobran y cómo optimizar tu selección para maximizar la rentabilidad.",
  tableOfContents: [
    "Por qué la rotación es clave para la rentabilidad",
    "Problemas comunes que frenan la rotación",
    "Estrategias para mejorar la rotación",
    "Cómo usar datos para tomar decisiones",
    "Cómo ayuda Winerim",
  ],
  sections: [
    { heading: "1. Por qué la rotación de vinos es clave para la rentabilidad", content: "Cada botella en tu bodega es dinero inmovilizado. Si un vino no se vende en 60-90 días, no solo ocupa espacio — está destruyendo valor.\n\nLa rotación de vinos mide cuántas veces se renueva el stock de cada referencia al año. Un restaurante con buena rotación vende y repone sus vinos 8-12 veces al año. Uno con mala rotación, 3-4 veces.\n\nLa diferencia en rentabilidad es enorme. Con la misma inversión en stock, el restaurante que rota bien genera el doble o triple de ingresos en vino.", tips: ["Un vino que no se vende en 90 días debería salir de la carta sin excepción", "El capital inmovilizado en vinos sin rotación podría invertirse en referencias que sí se venden", "Los vinos que se deterioran en bodega generan pérdidas directas, no solo coste de oportunidad", "La rotación media ideal es de 8-12 veces al año para la mayoría de referencias"], icon: "alert" },
    { heading: "2. Demasiadas referencias", content: "El primer enemigo de la rotación es el exceso de referencias. Cuantos más vinos tienes, más difícil es que cada uno se venda regularmente.\n\nUna carta con 180 referencias donde solo 60 se venden mensualmente significa 120 vinos acumulando polvo. Es el patrón más común que vemos en restaurantes con problemas de rotación.", tips: ["Revisa cuántas referencias tienes vs cuántas se venden realmente cada mes", "Aplica la regla del 80/20: el 80% de tus ventas viene del 20% de tus referencias", "Reduce a 50-80 referencias bien seleccionadas en restaurantes medios", "Cada vino debe cumplir una función clara: entrada, volumen, premium o descubrimiento"], icon: "list" },
    { heading: "3. Vinos mal posicionados en la carta", content: "Muchos vinos no se venden porque el cliente no los encuentra o no los entiende. El posicionamiento en la carta es tan importante como la selección.\n\nUn gran vino escondido en la página 3, dentro de una categoría confusa y sin descripción, es un vino invisible. Un vino mediocre en la primera sección, destacado como recomendación del sommelier, se vende mucho más.", tips: ["Los vinos que quieres vender deben estar en las posiciones de mayor visibilidad", "Las primeras y últimas posiciones de cada sección son las más consultadas", "Usa badges de 'Recomendado' o 'Selección del chef' para dirigir la atención", "Incluye notas de cata breves que ayuden al cliente a decidir sin depender del camarero"], icon: "lightbulb" },
    { heading: "4. Falta de recomendación activa", content: "Si el personal de sala no recomienda vino, las referencias menos conocidas simplemente no se venden. Los comensales eligen lo que conocen o lo más barato.\n\nLa recomendación activa es el motor de la rotación. Cuando un camarero sugiere un vino con convicción, la probabilidad de venta se multiplica.", tips: ["Forma al personal para que conozca 3-5 vinos y pueda recomendarlos con una frase clara", "Implementa un 'vino de la semana' que todo el equipo haya probado", "Vincula las recomendaciones a los platos del menú para que la sugerencia sea natural", "Si no puedes formar al equipo, usa herramientas digitales que recomienden por ti"], icon: "check" },
    { heading: "5. Estrategias para mejorar la rotación", content: "Mejorar la rotación requiere actuar en tres frentes simultáneamente: selección, posicionamiento y promoción.\n\nNo basta con quitar vinos que no se venden. Hay que crear las condiciones para que los que están se vendan mejor y más rápido.", tips: ["Selección: elige vinos que encajen con tu cocina, tu público y tu ticket medio", "Posicionamiento: coloca los vinos de alta rotación en posiciones privilegiadas de la carta", "Vino por copa: es la herramienta más potente para rotar referencias. Incluye 6-8 opciones que cambien cada 2-4 semanas", "Estacionalidad: adapta la carta a la temporada. Blancos frescos en verano, tintos potentes en invierno", "Promociones inteligentes: un vino que no rota puede venderse como maridaje recomendado o como copa del día"], icon: "check" },
    { heading: "6. Cómo usar datos para tomar decisiones", content: "La diferencia entre un restaurante que mejora su rotación y uno que no es una: datos.\n\nSin datos, las decisiones se basan en intuición. Con datos, puedes identificar exactamente qué funciona y qué no, y tomar acciones correctivas antes de que el stock se acumule.", tips: ["Mide la rotación de cada referencia mensualmente: unidades vendidas / stock medio", "Identifica los vinos con más de 60 días sin venta y decide si sustituirlos o promocionarlos", "Analiza qué franja de precio tiene mejor rotación y refuerza esa zona", "Compara la rotación entre categorías: si los blancos rotan más que los tintos, quizás tienes demasiados tintos", "Establece alertas automáticas para vinos que lleven 30+ días sin venderse"], icon: "lightbulb" },
    { heading: "7. Cómo ayuda Winerim", content: "Winerim está diseñado para resolver exactamente este problema. La plataforma te da visibilidad completa sobre la rotación de tu carta y herramientas para actuar.\n\nNo se trata de más informes. Se trata de recomendaciones accionables que puedes implementar en minutos.", tips: ["Dashboard de rotación: visualiza qué vinos se venden, cuáles no y desde cuándo", "Alertas de stock muerto: notificaciones automáticas cuando un vino lleva demasiado tiempo sin venderse", "Recomendador inteligente: el sistema recomienda vinos infravendidos a los comensales adecuados", "Maridajes automáticos: vincula vinos con baja rotación a platos del menú para darles visibilidad", "Gestión de vino por copa: optimiza la selección y rotación de tu programa de copas"], icon: "check" },
  ],
  faqs: [
    { q: "¿Cuál es una buena tasa de rotación para el vino en un restaurante?", a: "Para la mayoría de restaurantes, una rotación de 8-12 veces al año es saludable. Esto significa que cada referencia se vende y repone cada 4-6 semanas. Los vinos por copa deberían rotar más rápido: cada 1-2 semanas." },
    { q: "¿Cada cuánto debería revisar mi carta de vinos?", a: "Idealmente cada mes a nivel de datos (qué se vende, qué no) y cada trimestre a nivel de selección (quitar, añadir o sustituir referencias). Los vinos por copa deberían revisarse cada 2-4 semanas." },
    { q: "¿Qué hago con los vinos que no se venden?", a: "Tres opciones: 1) Reposiciónalos en la carta con mejor visibilidad y descripción. 2) Inclúyelos como vino por copa o maridaje recomendado. 3) Si en 30 días más no se venden, retíralos de la carta y liquídalos en eventos o promociones." },
    { q: "¿Tener menos vinos mejora la rotación automáticamente?", a: "Reducir referencias es condición necesaria pero no suficiente. También necesitas buen posicionamiento, recomendaciones activas y pricing adecuado. Pero sí, una carta más reducida concentra la demanda en menos referencias y mejora la rotación media." },
  ],
  relatedTools: [
    { label: "Calculadora de margen de vino", url: "/calculadora-margen-vino" },
    { label: "Calculadora de precio por copa", url: "/herramientas/calculadora-precio-vino-por-copa" },
    { label: "Analizador de carta de vinos", url: "/analisis-carta" },
  ],
  relatedGuides: [
    { label: "Cómo hacer una carta de vinos rentable", url: "/como-hacer-una-carta-de-vinos" },
    { label: "Cómo vender más vino en un restaurante", url: "/como-vender-mas-vino-en-un-restaurante" },
    { label: "Vino por copa en restaurante", url: "/vino-por-copa-restaurante" },
    { label: "Tu carta de vinos no vende", url: "/problemas/carta-de-vinos-no-vende" },
  ],
};

const en: GuidePageData = {
  slug: "en/guides/how-to-improve-wine-rotation-in-restaurants",
  metaTitle: "How to Improve Wine Rotation in a Restaurant | Guide",
  metaDescription: "Practical guide to improving wine rotation in your restaurant: selection, list positioning.",
  heroTitle: "How to improve wine rotation in a restaurant",
  heroSubtitle: "Wine rotation is one of the most important profitability indicators. Discover how to prevent wines from sitting idle in your cellar.",
  heroBadge: "Practical guide",
  breadcrumbParent: { label: "Guides", href: "/en/guides" },
  ctaPrimaryText: "Analyse my wine list", ctaPrimaryUrl: "/en/wine-list-analysis",
  ctaSecondaryText: "Request demo", ctaSecondaryUrl: "/en/demo",
  ctaFinalTitle: "Don't let your cellar accumulate dead stock",
  ctaFinalDescription: "Winerim gives you the data to know which wines rotate, which are surplus and how to optimise your selection for maximum profitability.",
  tableOfContents: [
    "Why rotation is key to profitability",
    "Common problems that slow rotation",
    "Strategies to improve rotation",
    "How to use data for decisions",
    "How Winerim helps",
  ],
  sections: [
    { heading: "1. Why wine rotation is key to profitability", content: "Every bottle in your cellar is tied-up capital. If a wine doesn't sell within 60-90 days it is not just taking up space — it is destroying value.\n\nWine rotation measures how many times each reference's stock is renewed per year. A restaurant with good rotation sells and replenishes its wines 8-12 times a year. One with poor rotation, 3-4 times.\n\nThe profitability difference is enormous. With the same stock investment, the restaurant that rotates well generates double or triple the wine revenue.", tips: ["A wine unsold for 90 days should leave the list without exception", "Capital tied up in non-rotating wines could be invested in references that do sell", "Wines that deteriorate in the cellar generate direct losses, not just opportunity cost", "The ideal average rotation is 8-12 times per year for most references"], icon: "alert" },
    { heading: "2. Too many references", content: "The first enemy of rotation is excess references. The more wines you have, the harder it is for each one to sell regularly.\n\nA list with 180 references where only 60 sell monthly means 120 wines gathering dust. It is the most common pattern we see in restaurants with rotation problems.", tips: ["Review how many references you have vs how many actually sell each month", "Apply the 80/20 rule: 80% of your sales come from 20% of your references", "Reduce to 50-80 well-selected references for mid-size restaurants", "Each wine must fulfil a clear role: entry-level, volume, premium or discovery"], icon: "list" },
    { heading: "3. Poorly positioned wines on the list", content: "Many wines don't sell because the guest can't find them or doesn't understand them. Positioning on the list is as important as selection.\n\nA great wine hidden on page 3, inside a confusing category with no description, is an invisible wine. A mediocre wine in the first section, highlighted as the sommelier's pick, sells far more.", tips: ["Wines you want to sell should be in the highest-visibility positions", "The first and last positions of each section are the most viewed", "Use 'Recommended' or 'Chef's selection' badges to direct attention", "Include brief tasting notes that help the guest decide without relying on the waiter"], icon: "lightbulb" },
    { heading: "4. Lack of active recommendation", content: "If floor staff don't recommend wine, lesser-known references simply don't sell. Diners choose what they know or the cheapest option.\n\nActive recommendation is the engine of rotation. When a waiter suggests a wine with conviction, the probability of a sale multiplies.", tips: ["Train staff to know 3-5 wines and recommend them with a clear sentence", "Implement a 'wine of the week' the whole team has tasted", "Link recommendations to menu dishes so the suggestion feels natural", "If you can't train the team, use digital tools that recommend for you"], icon: "check" },
    { heading: "5. Strategies to improve rotation", content: "Improving rotation requires action on three fronts simultaneously: selection, positioning and promotion.\n\nIt's not enough to remove wines that don't sell. You need to create the conditions for the remaining wines to sell better and faster.", tips: ["Selection: choose wines that match your cuisine, your audience and your average ticket", "Positioning: place high-rotation wines in privileged list positions", "Wine by the glass: the most powerful tool for rotating references. Include 6-8 options that change every 2-4 weeks", "Seasonality: adapt the list to the season. Fresh whites in summer, powerful reds in winter", "Smart promotions: a wine that doesn't rotate can be sold as a recommended pairing or glass of the day"], icon: "check" },
    { heading: "6. How to use data for decisions", content: "The difference between a restaurant that improves its rotation and one that doesn't is one thing: data.\n\nWithout data, decisions are based on intuition. With data, you can identify exactly what works and what doesn't, and take corrective action before stock accumulates.", tips: ["Measure each reference's rotation monthly: units sold / average stock", "Identify wines with 60+ days without a sale and decide whether to replace or promote them", "Analyse which price band has the best rotation and reinforce that zone", "Compare rotation across categories: if whites rotate more than reds, perhaps you have too many reds", "Set automatic alerts for wines unsold for 30+ days"], icon: "lightbulb" },
    { heading: "7. How Winerim helps", content: "Winerim is designed to solve exactly this problem. The platform gives you complete visibility over your list's rotation and tools to act.\n\nIt's not about more reports. It's about actionable recommendations you can implement in minutes.", tips: ["Rotation dashboard: see which wines sell, which don't and since when", "Dead stock alerts: automatic notifications when a wine has been unsold too long", "Smart recommender: the system recommends under-sold wines to the right diners", "Automatic pairings: link low-rotation wines to menu dishes for visibility", "By-the-glass management: optimise your glass programme's selection and rotation"], icon: "check" },
  ],
  faqs: [
    { q: "What is a good wine rotation rate for a restaurant?", a: "For most restaurants, a rotation of 8-12 times per year is healthy. This means each reference sells and is replenished every 4-6 weeks. Wines by the glass should rotate faster: every 1-2 weeks." },
    { q: "How often should I review my wine list?", a: "Ideally every month at a data level (what sells, what doesn't) and every quarter at a selection level (remove, add or replace references). Wines by the glass should be reviewed every 2-4 weeks." },
    { q: "What do I do with wines that don't sell?", a: "Three options: 1) Reposition them on the list with better visibility and description. 2) Include them as a wine by the glass or recommended pairing. 3) If they still don't sell after 30 more days, remove them and liquidate at events or promotions." },
    { q: "Does having fewer wines automatically improve rotation?", a: "Reducing references is necessary but not sufficient. You also need good positioning, active recommendations and appropriate pricing. But yes, a smaller list concentrates demand on fewer references and improves average rotation." },
  ],
  relatedTools: [
    { label: "Wine margin calculator", url: "/en/wine-margin-calculator" },
    { label: "Wine by glass price calculator", url: "/en/tools/wine-by-glass-price-calculator" },
    { label: "Wine list analyser", url: "/en/wine-list-analysis" },
  ],
  relatedGuides: [
    { label: "How to sell more wine in restaurants", url: "/en/how-to-sell-more-wine-in-restaurants" },
    { label: "Wine by the glass in restaurants", url: "/en/wine-by-glass-restaurant" },
    { label: "How to detect dead stock wines", url: "/en/guides/how-to-detect-dead-stock-wines" },
  ],
};

const it: GuidePageData = {
  slug: "it/guide/come-migliorare-rotazione-vini-ristorante",
  metaTitle: "Come Migliorare la Rotazione dei Vini in un Ristorante | Guida",
  metaDescription: "Guida pratica per migliorare la rotazione dei vini nel tuo ristorante: selezione, posizionamento in carta.",
  heroTitle: "Come migliorare la rotazione dei vini in un ristorante",
  heroSubtitle: "La rotazione dei vini è uno degli indicatori di redditività più importanti. Scopri come evitare che i tuoi vini restino immobilizzati in cantina.",
  heroBadge: "Guida pratica",
  breadcrumbParent: { label: "Guide", href: "/it/guide" },
  ctaPrimaryText: "Analizza la mia carta", ctaPrimaryUrl: "/it/analisi-carta",
  ctaSecondaryText: "Richiedi demo", ctaSecondaryUrl: "/it/demo",
  ctaFinalTitle: "Non lasciare che la tua cantina accumuli stock morto",
  ctaFinalDescription: "Winerim ti fornisce i dati per sapere quali vini ruotano, quali sono in eccesso e come ottimizzare la selezione per massimizzare la redditività.",
  tableOfContents: [
    "Perché la rotazione è fondamentale per la redditività",
    "Problemi comuni che frenano la rotazione",
    "Strategie per migliorare la rotazione",
    "Come usare i dati per decidere",
    "Come aiuta Winerim",
  ],
  sections: [
    { heading: "1. Perché la rotazione dei vini è fondamentale per la redditività", content: "Ogni bottiglia nella tua cantina è capitale immobilizzato. Se un vino non si vende in 60-90 giorni, non solo occupa spazio — sta distruggendo valore.\n\nLa rotazione dei vini misura quante volte lo stock di ogni referenza si rinnova all'anno. Un ristorante con buona rotazione vende e riordina i suoi vini 8-12 volte l'anno. Uno con cattiva rotazione, 3-4 volte.\n\nLa differenza di redditività è enorme. Con lo stesso investimento in stock, il ristorante che ruota bene genera il doppio o il triplo dei ricavi dal vino.", tips: ["Un vino invenduto per 90 giorni dovrebbe uscire dalla carta senza eccezioni", "Il capitale immobilizzato in vini senza rotazione potrebbe essere investito in referenze che si vendono", "I vini che si deteriorano in cantina generano perdite dirette, non solo costo opportunità", "La rotazione media ideale è di 8-12 volte l'anno per la maggior parte delle referenze"], icon: "alert" },
    { heading: "2. Troppe referenze", content: "Il primo nemico della rotazione è l'eccesso di referenze. Più vini hai, più difficile è che ciascuno si venda regolarmente.\n\nUna carta con 180 referenze dove solo 60 si vendono mensilmente significa 120 vini che accumulano polvere. È il pattern più comune che vediamo nei ristoranti con problemi di rotazione.", tips: ["Verifica quante referenze hai rispetto a quante si vendono realmente ogni mese", "Applica la regola 80/20: l'80% delle vendite viene dal 20% delle referenze", "Riduci a 50-80 referenze ben selezionate nei ristoranti medi", "Ogni vino deve avere una funzione chiara: ingresso, volume, premium o scoperta"], icon: "list" },
    { heading: "3. Vini mal posizionati nella carta", content: "Molti vini non si vendono perché il cliente non li trova o non li capisce. Il posizionamento in carta è importante quanto la selezione.\n\nUn grande vino nascosto a pagina 3, in una categoria confusa e senza descrizione, è un vino invisibile. Un vino mediocre nella prima sezione, evidenziato come scelta del sommelier, si vende molto di più.", tips: ["I vini che vuoi vendere devono essere nelle posizioni di maggiore visibilità", "Le prime e ultime posizioni di ogni sezione sono le più consultate", "Usa badge 'Consigliato' o 'Selezione dello chef' per dirigere l'attenzione", "Includi note di degustazione brevi che aiutino il cliente a decidere senza dipendere dal cameriere"], icon: "lightbulb" },
    { heading: "4. Mancanza di raccomandazione attiva", content: "Se il personale di sala non raccomanda vino, le referenze meno conosciute semplicemente non si vendono. I commensali scelgono ciò che conoscono o il più economico.\n\nLa raccomandazione attiva è il motore della rotazione. Quando un cameriere suggerisce un vino con convinzione, la probabilità di vendita si moltiplica.", tips: ["Forma il personale affinché conosca 3-5 vini e possa raccomandarli con una frase chiara", "Implementa un 'vino della settimana' che tutto il team abbia assaggiato", "Collega le raccomandazioni ai piatti del menù perché il suggerimento sia naturale", "Se non puoi formare il team, usa strumenti digitali che raccomandano per te"], icon: "check" },
    { heading: "5. Strategie per migliorare la rotazione", content: "Migliorare la rotazione richiede di agire su tre fronti contemporaneamente: selezione, posizionamento e promozione.\n\nNon basta togliere i vini che non si vendono. Bisogna creare le condizioni perché quelli presenti si vendano meglio e più velocemente.", tips: ["Selezione: scegli vini che si adattino alla tua cucina, al tuo pubblico e al tuo scontrino medio", "Posizionamento: metti i vini ad alta rotazione in posizioni privilegiate della carta", "Vino al calice: lo strumento più potente per far ruotare le referenze. Includi 6-8 opzioni che cambino ogni 2-4 settimane", "Stagionalità: adatta la carta alla stagione. Bianchi freschi d'estate, rossi potenti d'inverno", "Promozioni intelligenti: un vino che non ruota può essere venduto come abbinamento consigliato o calice del giorno"], icon: "check" },
    { heading: "6. Come usare i dati per decidere", content: "La differenza tra un ristorante che migliora la rotazione e uno che non lo fa è una: dati.\n\nSenza dati, le decisioni si basano sull'intuizione. Con i dati, puoi identificare esattamente cosa funziona e cosa no, e intraprendere azioni correttive prima che lo stock si accumuli.", tips: ["Misura la rotazione di ogni referenza mensilmente: unità vendute / stock medio", "Identifica i vini con più di 60 giorni senza vendita e decidi se sostituirli o promuoverli", "Analizza quale fascia di prezzo ha la migliore rotazione e rafforza quella zona", "Confronta la rotazione tra categorie: se i bianchi ruotano più dei rossi, forse hai troppi rossi", "Imposta avvisi automatici per vini invenduti da 30+ giorni"], icon: "lightbulb" },
    { heading: "7. Come aiuta Winerim", content: "Winerim è progettato per risolvere esattamente questo problema. La piattaforma ti dà visibilità completa sulla rotazione della tua carta e strumenti per agire.\n\nNon si tratta di più report. Si tratta di raccomandazioni azionabili che puoi implementare in pochi minuti.", tips: ["Dashboard di rotazione: visualizza quali vini si vendono, quali no e da quando", "Avvisi stock morto: notifiche automatiche quando un vino resta invenduto troppo a lungo", "Raccomandatore intelligente: il sistema suggerisce vini poco venduti ai commensali giusti", "Abbinamenti automatici: collega vini a bassa rotazione ai piatti del menù per dar loro visibilità", "Gestione vino al calice: ottimizza la selezione e la rotazione del tuo programma al calice"], icon: "check" },
  ],
  faqs: [
    { q: "Qual è un buon tasso di rotazione per il vino in un ristorante?", a: "Per la maggior parte dei ristoranti, una rotazione di 8-12 volte l'anno è sana. Significa che ogni referenza si vende e si riordina ogni 4-6 settimane. I vini al calice dovrebbero ruotare più velocemente: ogni 1-2 settimane." },
    { q: "Ogni quanto dovrei rivedere la mia carta dei vini?", a: "Idealmente ogni mese a livello di dati (cosa si vende, cosa no) e ogni trimestre a livello di selezione (togliere, aggiungere o sostituire referenze). I vini al calice dovrebbero essere rivisti ogni 2-4 settimane." },
    { q: "Cosa faccio con i vini che non si vendono?", a: "Tre opzioni: 1) Riposizionali in carta con migliore visibilità e descrizione. 2) Includili come vino al calice o abbinamento consigliato. 3) Se in 30 giorni ancora non si vendono, ritirali e liquidali in eventi o promozioni." },
    { q: "Avere meno vini migliora automaticamente la rotazione?", a: "Ridurre le referenze è condizione necessaria ma non sufficiente. Servono anche buon posizionamento, raccomandazioni attive e pricing adeguato. Ma sì, una carta più ridotta concentra la domanda su meno referenze e migliora la rotazione media." },
  ],
  relatedTools: [
    { label: "Calcolatrice margini vino", url: "/it/calcolatrice-margini-vino" },
    { label: "Calcolatrice prezzo vino al calice", url: "/it/strumenti/calcolatrice-prezzo-vino-al-calice" },
    { label: "Analizzatore carta vini", url: "/it/analisi-carta" },
  ],
  relatedGuides: [
    { label: "Come vendere più vino al ristorante", url: "/it/come-vendere-piu-vino-ristorante" },
    { label: "Vino al calice al ristorante", url: "/it/vino-al-calice-ristorante" },
    { label: "Come rilevare vini morti", url: "/it/guide/come-rilevare-vini-morti" },
  ],
};

const fr: GuidePageData = {
  slug: "fr/guides/comment-ameliorer-rotation-vins-restaurant",
  metaTitle: "Comment Améliorer la Rotation des Vins dans un Restaurant | Guide",
  metaDescription: "Guide pratique pour améliorer la rotation des vins dans votre restaurant : sélection, positionnement en carte.",
  heroTitle: "Comment améliorer la rotation des vins dans un restaurant",
  heroSubtitle: "La rotation des vins est l'un des indicateurs de rentabilité les plus importants. Découvrez comment éviter que vos vins restent immobilisés en cave.",
  heroBadge: "Guide pratique",
  breadcrumbParent: { label: "Guides", href: "/fr/guides" },
  ctaPrimaryText: "Analyser ma carte", ctaPrimaryUrl: "/fr/analyse-carte",
  ctaSecondaryText: "Demander une démo", ctaSecondaryUrl: "/fr/demo",
  ctaFinalTitle: "Ne laissez pas votre cave accumuler du stock mort",
  ctaFinalDescription: "Winerim vous donne les données pour savoir quels vins tournent, lesquels sont en surplus et comment optimiser votre sélection pour maximiser la rentabilité.",
  tableOfContents: [
    "Pourquoi la rotation est clé pour la rentabilité",
    "Problèmes courants qui freinent la rotation",
    "Stratégies pour améliorer la rotation",
    "Comment utiliser les données pour décider",
    "Comment Winerim vous aide",
  ],
  sections: [
    { heading: "1. Pourquoi la rotation des vins est clé pour la rentabilité", content: "Chaque bouteille dans votre cave est du capital immobilisé. Si un vin ne se vend pas en 60-90 jours, il ne fait pas qu'occuper de l'espace — il détruit de la valeur.\n\nLa rotation des vins mesure combien de fois le stock de chaque référence se renouvelle par an. Un restaurant avec une bonne rotation vend et réapprovisionne ses vins 8-12 fois par an. Un avec une mauvaise rotation, 3-4 fois.\n\nLa différence de rentabilité est énorme. Avec le même investissement en stock, le restaurant qui tourne bien génère le double ou le triple du chiffre d'affaires vin.", tips: ["Un vin invendu depuis 90 jours devrait quitter la carte sans exception", "Le capital immobilisé dans des vins sans rotation pourrait être investi dans des références qui se vendent", "Les vins qui se détériorent en cave génèrent des pertes directes, pas seulement un coût d'opportunité", "La rotation moyenne idéale est de 8-12 fois par an pour la plupart des références"], icon: "alert" },
    { heading: "2. Trop de références", content: "Le premier ennemi de la rotation est l'excès de références. Plus vous avez de vins, plus il est difficile que chacun se vende régulièrement.\n\nUne carte avec 180 références dont seulement 60 se vendent chaque mois signifie 120 vins qui prennent la poussière. C'est le pattern le plus courant que nous observons dans les restaurants ayant des problèmes de rotation.", tips: ["Vérifiez combien de références vous avez vs combien se vendent réellement chaque mois", "Appliquez la règle 80/20 : 80% de vos ventes viennent de 20% de vos références", "Réduisez à 50-80 références bien sélectionnées pour les restaurants de taille moyenne", "Chaque vin doit remplir un rôle clair : entrée de gamme, volume, premium ou découverte"], icon: "list" },
    { heading: "3. Vins mal positionnés sur la carte", content: "Beaucoup de vins ne se vendent pas parce que le client ne les trouve pas ou ne les comprend pas. Le positionnement sur la carte est aussi important que la sélection.\n\nUn grand vin caché en page 3, dans une catégorie confuse sans description, est un vin invisible. Un vin moyen dans la première section, mis en avant comme choix du sommelier, se vend beaucoup plus.", tips: ["Les vins que vous voulez vendre doivent être dans les positions de plus grande visibilité", "Les premières et dernières positions de chaque section sont les plus consultées", "Utilisez des badges « Recommandé » ou « Sélection du chef » pour diriger l'attention", "Incluez des notes de dégustation brèves qui aident le client à décider sans dépendre du serveur"], icon: "lightbulb" },
    { heading: "4. Manque de recommandation active", content: "Si le personnel de salle ne recommande pas de vin, les références moins connues ne se vendent tout simplement pas. Les convives choisissent ce qu'ils connaissent ou le moins cher.\n\nLa recommandation active est le moteur de la rotation. Quand un serveur suggère un vin avec conviction, la probabilité de vente se multiplie.", tips: ["Formez le personnel pour qu'il connaisse 3-5 vins et puisse les recommander avec une phrase claire", "Instaurez un « vin de la semaine » que toute l'équipe a goûté", "Liez les recommandations aux plats du menu pour que la suggestion soit naturelle", "Si vous ne pouvez pas former l'équipe, utilisez des outils digitaux qui recommandent pour vous"], icon: "check" },
    { heading: "5. Stratégies pour améliorer la rotation", content: "Améliorer la rotation nécessite d'agir sur trois fronts simultanément : sélection, positionnement et promotion.\n\nIl ne suffit pas de retirer les vins qui ne se vendent pas. Il faut créer les conditions pour que ceux qui restent se vendent mieux et plus vite.", tips: ["Sélection : choisissez des vins qui correspondent à votre cuisine, votre clientèle et votre ticket moyen", "Positionnement : placez les vins à haute rotation dans les positions privilégiées de la carte", "Vin au verre : l'outil le plus puissant pour faire tourner les références. Incluez 6-8 options changeant toutes les 2-4 semaines", "Saisonnalité : adaptez la carte à la saison. Blancs frais en été, rouges puissants en hiver", "Promotions intelligentes : un vin qui ne tourne pas peut être vendu comme accord recommandé ou verre du jour"], icon: "check" },
    { heading: "6. Comment utiliser les données pour décider", content: "La différence entre un restaurant qui améliore sa rotation et un qui ne le fait pas se résume à un mot : données.\n\nSans données, les décisions reposent sur l'intuition. Avec des données, vous pouvez identifier exactement ce qui fonctionne et ce qui ne fonctionne pas, et prendre des mesures correctives avant que le stock ne s'accumule.", tips: ["Mesurez la rotation de chaque référence mensuellement : unités vendues / stock moyen", "Identifiez les vins avec 60+ jours sans vente et décidez s'il faut les remplacer ou les promouvoir", "Analysez quelle gamme de prix a la meilleure rotation et renforcez cette zone", "Comparez la rotation entre catégories : si les blancs tournent plus que les rouges, peut-être avez-vous trop de rouges", "Paramétrez des alertes automatiques pour les vins invendus depuis 30+ jours"], icon: "lightbulb" },
    { heading: "7. Comment Winerim vous aide", content: "Winerim est conçu pour résoudre exactement ce problème. La plateforme vous donne une visibilité complète sur la rotation de votre carte et des outils pour agir.\n\nIl ne s'agit pas de plus de rapports. Il s'agit de recommandations actionnables que vous pouvez mettre en œuvre en quelques minutes.", tips: ["Dashboard de rotation : visualisez quels vins se vendent, lesquels non et depuis quand", "Alertes stock mort : notifications automatiques quand un vin est invendu depuis trop longtemps", "Recommandeur intelligent : le système recommande les vins sous-vendus aux bons convives", "Accords automatiques : liez les vins à faible rotation aux plats du menu pour leur donner de la visibilité", "Gestion du vin au verre : optimisez la sélection et la rotation de votre programme au verre"], icon: "check" },
  ],
  faqs: [
    { q: "Quel est un bon taux de rotation pour le vin dans un restaurant ?", a: "Pour la plupart des restaurants, une rotation de 8-12 fois par an est saine. Cela signifie que chaque référence se vend et se réapprovisionne toutes les 4-6 semaines. Les vins au verre devraient tourner plus vite : toutes les 1-2 semaines." },
    { q: "À quelle fréquence devrais-je réviser ma carte des vins ?", a: "Idéalement chaque mois au niveau des données (ce qui se vend, ce qui ne se vend pas) et chaque trimestre au niveau de la sélection (retirer, ajouter ou remplacer des références). Les vins au verre devraient être révisés toutes les 2-4 semaines." },
    { q: "Que faire des vins qui ne se vendent pas ?", a: "Trois options : 1) Repositionnez-les sur la carte avec une meilleure visibilité et description. 2) Incluez-les comme vin au verre ou accord recommandé. 3) S'ils ne se vendent toujours pas après 30 jours supplémentaires, retirez-les et liquidez-les lors d'événements ou promotions." },
    { q: "Avoir moins de vins améliore-t-il automatiquement la rotation ?", a: "Réduire les références est nécessaire mais pas suffisant. Il faut aussi un bon positionnement, des recommandations actives et un pricing adapté. Mais oui, une carte plus réduite concentre la demande sur moins de références et améliore la rotation moyenne." },
  ],
  relatedTools: [
    { label: "Calculateur de marge vin", url: "/fr/calculateur-marge-vin" },
    { label: "Calculateur prix vin au verre", url: "/fr/outils/calculateur-prix-vin-au-verre" },
    { label: "Analyseur de carte des vins", url: "/fr/analyse-carte" },
  ],
  relatedGuides: [
    { label: "Comment vendre plus de vin au restaurant", url: "/fr/comment-vendre-plus-vin-restaurant" },
    { label: "Vin au verre au restaurant", url: "/fr/vin-au-verre-restaurant" },
    { label: "Comment détecter les vins morts", url: "/fr/guides/comment-detecter-vins-morts" },
  ],
};

const de: GuidePageData = {
  slug: "de/ratgeber/wie-man-die-weinrotation-im-restaurant-verbessert",
  metaTitle: "Wie man die Weinrotation im Restaurant verbessert | Ratgeber",
  metaDescription: "Praktischer Ratgeber zur Verbesserung der Weinrotation in Ihrem Restaurant: Auswahl, Positionierung auf der Karte.",
  heroTitle: "Wie man die Weinrotation im Restaurant verbessert",
  heroSubtitle: "Die Weinrotation ist einer der wichtigsten Rentabilitätsindikatoren. Erfahren Sie, wie Sie verhindern, dass Ihre Weine ungenutzt im Keller liegen bleiben.",
  heroBadge: "Praktischer Ratgeber",
  breadcrumbParent: { label: "Ratgeber", href: "/de/ratgeber" },
  ctaPrimaryText: "Meine Karte analysieren", ctaPrimaryUrl: "/de/weinkarten-analyse",
  ctaSecondaryText: "Demo anfordern", ctaSecondaryUrl: "/de/demo",
  ctaFinalTitle: "Lassen Sie nicht zu, dass Ihr Weinkeller Totbestand anhäuft",
  ctaFinalDescription: "Winerim liefert Ihnen die Daten, um zu wissen, welche Weine rotieren, welche überflüssig sind und wie Sie Ihre Auswahl für maximale Rentabilität optimieren.",
  tableOfContents: [
    "Warum die Rotation entscheidend für die Rentabilität ist",
    "Häufige Probleme, die die Rotation bremsen",
    "Strategien zur Verbesserung der Rotation",
    "Wie man Daten für Entscheidungen nutzt",
    "Wie Winerim hilft",
  ],
  sections: [
    { heading: "1. Warum die Weinrotation entscheidend für die Rentabilität ist", content: "Jede Flasche in Ihrem Keller ist gebundenes Kapital. Wenn sich ein Wein innerhalb von 60-90 Tagen nicht verkauft, nimmt er nicht nur Platz weg — er vernichtet Wert.\n\nDie Weinrotation misst, wie oft der Bestand jeder Referenz pro Jahr erneuert wird. Ein Restaurant mit guter Rotation verkauft und bestellt seine Weine 8-12 Mal im Jahr nach. Eines mit schlechter Rotation nur 3-4 Mal.\n\nDer Rentabilitätsunterschied ist enorm. Bei gleicher Bestandsinvestition erwirtschaftet das rotierende Restaurant den doppelten oder dreifachen Weinumsatz.", tips: ["Ein Wein, der 90 Tage unverkauft ist, sollte ohne Ausnahme von der Karte verschwinden", "Das in nicht rotierenden Weinen gebundene Kapital könnte in verkaufsstarke Referenzen investiert werden", "Weine, die im Keller verderben, verursachen direkte Verluste, nicht nur Opportunitätskosten", "Die ideale Durchschnittsrotation liegt für die meisten Referenzen bei 8-12 Mal pro Jahr"], icon: "alert" },
    { heading: "2. Zu viele Referenzen", content: "Der erste Feind der Rotation ist der Überschuss an Referenzen. Je mehr Weine Sie haben, desto schwieriger ist es, dass jeder einzelne regelmäßig verkauft wird.\n\nEine Karte mit 180 Referenzen, von denen sich monatlich nur 60 verkaufen, bedeutet 120 Weine, die Staub ansetzen. Das ist das häufigste Muster, das wir in Restaurants mit Rotationsproblemen sehen.", tips: ["Überprüfen Sie, wie viele Referenzen Sie haben im Vergleich zu denen, die sich tatsächlich monatlich verkaufen", "Wenden Sie die 80/20-Regel an: 80 % Ihrer Verkäufe stammen von 20 % Ihrer Referenzen", "Reduzieren Sie auf 50-80 gut ausgewählte Referenzen in mittelgroßen Restaurants", "Jeder Wein muss eine klare Rolle erfüllen: Einstieg, Volumen, Premium oder Entdeckung"], icon: "list" },
    { heading: "3. Schlecht positionierte Weine auf der Karte", content: "Viele Weine verkaufen sich nicht, weil der Gast sie nicht findet oder nicht versteht. Die Positionierung auf der Karte ist genauso wichtig wie die Auswahl.\n\nEin großartiger Wein, versteckt auf Seite 3 in einer verwirrenden Kategorie ohne Beschreibung, ist ein unsichtbarer Wein. Ein mittelmäßiger Wein im ersten Abschnitt, hervorgehoben als Sommelier-Empfehlung, verkauft sich viel besser.", tips: ["Weine, die Sie verkaufen möchten, sollten an den sichtbarsten Positionen stehen", "Die ersten und letzten Positionen jedes Abschnitts werden am häufigsten gelesen", "Verwenden Sie \"Empfohlen\"- oder \"Chef-Auswahl\"-Abzeichen, um Aufmerksamkeit zu lenken", "Fügen Sie kurze Verkostungsnotizen hinzu, die dem Gast helfen, ohne Kellner zu entscheiden"], icon: "lightbulb" },
    { heading: "4. Fehlende aktive Empfehlung", content: "Wenn das Servicepersonal keinen Wein empfiehlt, verkaufen sich weniger bekannte Referenzen einfach nicht. Die Gäste wählen, was sie kennen, oder das Günstigste.\n\nDie aktive Empfehlung ist der Motor der Rotation. Wenn ein Kellner einen Wein mit Überzeugung vorschlägt, vervielfacht sich die Verkaufswahrscheinlichkeit.", tips: ["Schulen Sie das Personal so, dass es 3-5 Weine kennt und mit einem klaren Satz empfehlen kann", "Führen Sie einen \"Wein der Woche\" ein, den das gesamte Team verkostet hat", "Verknüpfen Sie Empfehlungen mit Gerichten auf der Speisekarte, damit der Vorschlag natürlich wirkt", "Wenn Sie das Team nicht schulen können, nutzen Sie digitale Tools, die für Sie empfehlen"], icon: "check" },
    { heading: "5. Strategien zur Verbesserung der Rotation", content: "Die Verbesserung der Rotation erfordert gleichzeitiges Handeln an drei Fronten: Auswahl, Positionierung und Promotion.\n\nEs reicht nicht, Weine zu entfernen, die sich nicht verkaufen. Man muss die Bedingungen schaffen, damit die verbleibenden sich besser und schneller verkaufen.", tips: ["Auswahl: Wählen Sie Weine, die zu Ihrer Küche, Ihrem Publikum und Ihrem Durchschnittsbon passen", "Positionierung: Platzieren Sie rotationsstarke Weine an privilegierten Stellen der Karte", "Glaswein: das wirkungsvollste Instrument zur Rotation von Referenzen. Bieten Sie 6-8 Optionen an, die alle 2-4 Wochen wechseln", "Saisonalität: Passen Sie die Karte an die Jahreszeit an. Frische Weißweine im Sommer, kräftige Rotweine im Winter", "Intelligente Aktionen: Ein Wein, der nicht rotiert, kann als empfohlene Speisenbegleitung oder Glas des Tages verkauft werden"], icon: "check" },
    { heading: "6. Wie man Daten für Entscheidungen nutzt", content: "Der Unterschied zwischen einem Restaurant, das seine Rotation verbessert, und einem, das es nicht tut, liegt in einem Wort: Daten.\n\nOhne Daten basieren Entscheidungen auf Intuition. Mit Daten können Sie genau identifizieren, was funktioniert und was nicht, und Korrekturmaßnahmen ergreifen, bevor sich der Bestand anhäuft.", tips: ["Messen Sie die Rotation jeder Referenz monatlich: verkaufte Einheiten / durchschnittlicher Bestand", "Identifizieren Sie Weine mit mehr als 60 Tagen ohne Verkauf und entscheiden Sie, ob Sie sie ersetzen oder bewerben", "Analysieren Sie, welche Preisklasse die beste Rotation aufweist, und stärken Sie diese Zone", "Vergleichen Sie die Rotation zwischen Kategorien: Wenn Weißweine mehr rotieren als Rotweine, haben Sie vielleicht zu viele Rotweine", "Richten Sie automatische Warnungen für Weine ein, die 30+ Tage unverkauft sind"], icon: "lightbulb" },
    { heading: "7. Wie Winerim hilft", content: "Winerim wurde entwickelt, um genau dieses Problem zu lösen. Die Plattform bietet Ihnen vollständige Sichtbarkeit über die Rotation Ihrer Karte und Werkzeuge zum Handeln.\n\nEs geht nicht um mehr Berichte. Es geht um umsetzbare Empfehlungen, die Sie in wenigen Minuten implementieren können.", tips: ["Rotations-Dashboard: visualisieren Sie, welche Weine sich verkaufen, welche nicht und seit wann", "Totbestand-Warnungen: automatische Benachrichtigungen, wenn ein Wein zu lange unverkauft ist", "Intelligenter Empfehlungsassistent: das System empfiehlt unterverkaufte Weine den passenden Gästen", "Automatische Speisenbegleitungen: verknüpfen Sie Weine mit niedriger Rotation mit Gerichten der Karte, um ihnen Sichtbarkeit zu geben", "Glaswein-Management: optimieren Sie Auswahl und Rotation Ihres Glaswein-Programms"], icon: "check" },
  ],
  faqs: [
    { q: "Was ist eine gute Weinrotationsrate für ein Restaurant?", a: "Für die meisten Restaurants ist eine Rotation von 8-12 Mal pro Jahr gesund. Das bedeutet, dass sich jede Referenz alle 4-6 Wochen verkauft und nachbestellt wird. Glasweine sollten schneller rotieren: alle 1-2 Wochen." },
    { q: "Wie oft sollte ich meine Weinkarte überprüfen?", a: "Idealerweise monatlich auf Datenebene (was sich verkauft, was nicht) und vierteljährlich auf Auswahlebene (Referenzen entfernen, hinzufügen oder ersetzen). Glasweine sollten alle 2-4 Wochen überprüft werden." },
    { q: "Was mache ich mit Weinen, die sich nicht verkaufen?", a: "Drei Optionen: 1) Repositionieren Sie sie auf der Karte mit besserer Sichtbarkeit und Beschreibung. 2) Nehmen Sie sie als Glaswein oder empfohlene Speisenbegleitung auf. 3) Wenn sie sich nach weiteren 30 Tagen immer noch nicht verkaufen, nehmen Sie sie von der Karte und verwerten Sie sie bei Events oder Aktionen." },
    { q: "Verbessert eine kleinere Weinauswahl die Rotation automatisch?", a: "Die Reduzierung der Referenzen ist notwendig, aber nicht ausreichend. Sie benötigen auch gute Positionierung, aktive Empfehlungen und angemessenes Pricing. Aber ja, eine kleinere Karte bündelt die Nachfrage auf weniger Referenzen und verbessert die Durchschnittsrotation." },
  ],
  relatedTools: [
    { label: "Weinmargen-Rechner", url: "/de/weinmargen-rechner" },
    { label: "Glasweinpreis-Rechner", url: "/de/tools/glasweinpreis-rechner" },
    { label: "Weinkarten-Analyzer", url: "/de/weinkarten-analyse" },
  ],
  relatedGuides: [
    { label: "Mehr Wein im Restaurant verkaufen", url: "/de/mehr-wein-verkaufen-restaurant" },
    { label: "Glaswein im Restaurant", url: "/de/glaswein-restaurant" },
    { label: "Totbestand erkennen", url: "/de/ratgeber/totbestand-erkennen" },
  ],
};

const pt: GuidePageData = {
  slug: "pt/guias/como-melhorar-a-rotacao-de-vinhos-num-restaurante",
  metaTitle: "Como Melhorar a Rotação de Vinhos num Restaurante | Guia",
  metaDescription: "Guia prático para melhorar a rotação de vinhos no seu restaurante: seleção, posicionamento na carta.",
  heroTitle: "Como melhorar a rotação de vinhos num restaurante",
  heroSubtitle: "A rotação de vinhos é um dos indicadores de rentabilidade mais importantes. Descubra como evitar que os seus vinhos fiquem imobilizados na garrafeira.",
  heroBadge: "Guia prático",
  breadcrumbParent: { label: "Guias", href: "/pt/guias" },
  ctaPrimaryText: "Analisar a minha carta", ctaPrimaryUrl: "/pt/analisador-carta-de-vinhos",
  ctaSecondaryText: "Pedir demonstração", ctaSecondaryUrl: "/pt/demo",
  ctaFinalTitle: "Não deixe a sua garrafeira acumular stock morto",
  ctaFinalDescription: "A Winerim dá-lhe os dados para saber que vinhos rodam, quais estão a mais e como otimizar a sua seleção para maximizar a rentabilidade.",
  tableOfContents: [
    "Porque a rotação é crucial para a rentabilidade",
    "Problemas comuns que travam a rotação",
    "Estratégias para melhorar a rotação",
    "Como usar dados para decidir",
    "Como a Winerim ajuda",
  ],
  sections: [
    { heading: "1. Porque a rotação de vinhos é crucial para a rentabilidade", content: "Cada garrafa na sua garrafeira é capital imobilizado. Se um vinho não se vende em 60-90 dias, não só ocupa espaço — está a destruir valor.\n\nA rotação de vinhos mede quantas vezes o stock de cada referência se renova por ano. Um restaurante com boa rotação vende e repõe os seus vinhos 8-12 vezes por ano. Um com má rotação, 3-4 vezes.\n\nA diferença de rentabilidade é enorme. Com o mesmo investimento em stock, o restaurante que roda bem gera o dobro ou o triplo das receitas de vinho.", tips: ["Um vinho por vender há 90 dias deve sair da carta sem exceção", "O capital imobilizado em vinhos sem rotação poderia ser investido em referências que se vendem", "Os vinhos que se deterioram na garrafeira geram perdas diretas, não apenas custo de oportunidade", "A rotação média ideal é de 8-12 vezes por ano para a maioria das referências"], icon: "alert" },
    { heading: "2. Demasiadas referências", content: "O primeiro inimigo da rotação é o excesso de referências. Quantos mais vinhos tem, mais difícil é que cada um se venda regularmente.\n\nUma carta com 180 referências em que só 60 se vendem mensalmente significa 120 vinhos a ganhar pó. É o padrão mais comum que vemos em restaurantes com problemas de rotação.", tips: ["Verifique quantas referências tem face às que realmente se vendem todos os meses", "Aplique a regra 80/20: 80 % das vendas vêm de 20 % das referências", "Reduza para 50-80 referências bem selecionadas em restaurantes médios", "Cada vinho deve cumprir uma função clara: entrada, volume, premium ou descoberta"], icon: "list" },
    { heading: "3. Vinhos mal posicionados na carta", content: "Muitos vinhos não se vendem porque o cliente não os encontra ou não os percebe. O posicionamento na carta é tão importante como a seleção.\n\nUm grande vinho escondido na página 3, numa categoria confusa e sem descrição, é um vinho invisível. Um vinho médio na primeira secção, destacado como escolha do escanção, vende-se muito mais.", tips: ["Os vinhos que quer vender devem estar nas posições de maior visibilidade", "As primeiras e últimas posições de cada secção são as mais consultadas", "Use selos \"Recomendado\" ou \"Seleção do chef\" para dirigir a atenção", "Inclua notas de prova breves que ajudem o cliente a decidir sem depender do empregado"], icon: "lightbulb" },
    { heading: "4. Falta de recomendação ativa", content: "Se o pessoal de sala não recomenda vinho, as referências menos conhecidas simplesmente não se vendem. Os comensais escolhem o que conhecem ou o mais barato.\n\nA recomendação ativa é o motor da rotação. Quando um empregado sugere um vinho com convicção, a probabilidade de venda multiplica-se.", tips: ["Forme o pessoal para que conheça 3-5 vinhos e os possa recomendar com uma frase clara", "Implemente um \"vinho da semana\" que toda a equipa tenha provado", "Ligue as recomendações aos pratos da ementa para que a sugestão seja natural", "Se não puder formar a equipa, use ferramentas digitais que recomendam por si"], icon: "check" },
    { heading: "5. Estratégias para melhorar a rotação", content: "Melhorar a rotação exige atuar em três frentes em simultâneo: seleção, posicionamento e promoção.\n\nNão basta retirar vinhos que não se vendem. Há que criar as condições para que os que ficam se vendam melhor e mais depressa.", tips: ["Seleção: escolha vinhos que encaixem na sua cozinha, público e bilhete médio", "Posicionamento: coloque vinhos de alta rotação em posições privilegiadas da carta", "Vinho a copo: a ferramenta mais poderosa para rodar referências. Inclua 6-8 opções que mudem a cada 2-4 semanas", "Sazonalidade: adapte a carta à estação. Brancos frescos no verão, tintos potentes no inverno", "Promoções inteligentes: um vinho que não roda pode ser vendido como harmonização recomendada ou copo do dia"], icon: "check" },
    { heading: "6. Como usar dados para decidir", content: "A diferença entre um restaurante que melhora a rotação e outro que não é uma: dados.\n\nSem dados, as decisões baseiam-se na intuição. Com dados, pode identificar exatamente o que funciona e o que não, e agir antes que o stock se acumule.", tips: ["Meça a rotação de cada referência mensalmente: unidades vendidas / stock médio", "Identifique os vinhos com mais de 60 dias sem venda e decida se os substitui ou promove", "Analise que gama de preço tem melhor rotação e reforce essa zona", "Compare a rotação entre categorias: se os brancos rodam mais que os tintos, talvez tenha tintos a mais", "Configure alertas automáticos para vinhos por vender há 30+ dias"], icon: "lightbulb" },
    { heading: "7. Como a Winerim ajuda", content: "A Winerim foi concebida para resolver exatamente este problema. A plataforma dá-lhe visibilidade completa sobre a rotação da sua carta e ferramentas para agir.\n\nNão se trata de mais relatórios. Trata-se de recomendações acionáveis que pode implementar em minutos.", tips: ["Dashboard de rotação: visualize que vinhos se vendem, quais não e desde quando", "Alertas de stock morto: notificações automáticas quando um vinho está sem vender há demasiado tempo", "Recomendador inteligente: o sistema sugere vinhos subvalorizados aos comensais adequados", "Harmonizações automáticas: ligue vinhos de baixa rotação aos pratos da ementa para lhes dar visibilidade", "Gestão de vinho a copo: otimize a seleção e rotação do seu programa a copo"], icon: "check" },
  ],
  faqs: [
    { q: "Qual é uma boa taxa de rotação para o vinho num restaurante?", a: "Para a maioria dos restaurantes, uma rotação de 8-12 vezes por ano é saudável. Significa que cada referência se vende e repõe a cada 4-6 semanas. Os vinhos a copo devem rodar mais depressa: a cada 1-2 semanas." },
    { q: "Com que frequência devo rever a minha carta de vinhos?", a: "Idealmente todos os meses ao nível dos dados (o que se vende, o que não) e a cada trimestre ao nível da seleção (retirar, adicionar ou substituir referências). Os vinhos a copo devem ser revistos a cada 2-4 semanas." },
    { q: "O que faço com os vinhos que não se vendem?", a: "Três opções: 1) Reposicione-os na carta com melhor visibilidade e descrição. 2) Inclua-os como vinho a copo ou harmonização recomendada. 3) Se em mais 30 dias não se venderem, retire-os e liquide-os em eventos ou promoções." },
    { q: "Ter menos vinhos melhora automaticamente a rotação?", a: "Reduzir referências é condição necessária mas não suficiente. Também precisa de bom posicionamento, recomendações ativas e pricing adequado. Mas sim, uma carta mais reduzida concentra a procura em menos referências e melhora a rotação média." },
  ],
  relatedTools: [
    { label: "Calculadora de margem de vinho", url: "/pt/calculadora-margem-vinho" },
    { label: "Calculadora preço vinho a copo", url: "/pt/ferramentas/calculadora-preco-vinho-a-copo" },
    { label: "Analisador de carta de vinhos", url: "/pt/analisador-carta-de-vinhos" },
  ],
  relatedGuides: [
    { label: "Como vender mais vinho no restaurante", url: "/pt/como-vender-mais-vinho-restaurante" },
    { label: "Vinho a copo no restaurante", url: "/pt/vinho-a-copo-restaurante" },
    { label: "Como detetar vinhos mortos", url: "/pt/guias/como-detetar-vinhos-mortos" },
  ],
};

const data: Record<string, GuidePageData> = { es, en, it, fr, de, pt };

const RotacionVinos = () => <GuideTemplate data={data} />;

export default RotacionVinos;
